# 接続先として、データベースの種類(`mysql`)、ユーザ名(`dbuser`)、パスワード(`dbpass`)、ホスト名(`localhost`)、ポート(`3306`)、データベース名(`dbname`)を以下のように記載します
dsn: postgresql://tanishi:@localhost:5432/my_proj_development?sslmode=disable

# ドキュメントのディレクトリを指定します
docPath: doc/schema

# 参考
# https://qiita.com/k1LoW/items/92d1be1437a259827338
# tbls doc --rm-dist
# tbls doc --force
comments:
  -
    table: articles
    tableComment: articles table
    columnComments:
      body: 日記の本文
      user_id: 日記を書いたユーザー
  -
    table: people
    tableComment: 日記に出てきた登場人物
    columnComments:
      name: 日記に出てきた登場人物の名前
      user_id: この登場人物が、本アプリのユーザーである場合には、user_idにそのユーザーのIDを入れる
  -
    table: users
    tableComment: 日記を書くユーザー
    columnComments:
      username: 日記を書くユーザーの名前
