# 接続先として、データベースの種類(`mysql`)、ユーザ名(`dbuser`)、パスワード(`dbpass`)、ホスト名(`localhost`)、ポート(`3306`)、データベース名(`dbname`)を以下のように記載します
dsn: postgresql://tanishi:@localhost:5432/my_proj_development?sslmode=disable

# ドキュメントのディレクトリを指定します
docPath: doc/schema

# 参考
# https://qiita.com/k1LoW/items/92d1be1437a259827338
# tbls doc --rm-dist
# tbls doc --force
comments:
  -
    table: active_storage_attachments
    tableComment: ActiveStorageの添付ファイルの関連付けテーブル
    columnComments:
      name: 添付の名前
      record_type: 添付されているレコードの型
      record_id: 添付されているレコードのID
      blob_id: 添付のblobへの参照ID
      created_at: 作成日時
  -
    table: active_storage_blobs
    tableComment: ActiveStorageのblobテーブル
    columnComments:
      key: blobのキー
      filename: ファイル名
      content_type: コンテンツタイプ
      metadata: メタデータ
      service_name: サービス名
      byte_size: バイトサイズ
      checksum: チェックサム
      created_at: 作成日時
  -
    table: active_storage_variant_records
    tableComment: ActiveStorageの画像のバリアント情報テーブル
    columnComments:
      blob_id: 元のblobへの参照ID
      variation_digest: バリアントのダイジェスト
  -
    table: articles
    tableComment: 求人記事のエントリテーブル
    columnComments:
      body: 求人記事の内容
      user_id: 求人記事を作成したユーザーのID
      created_at: 作成日時
      updated_at: 更新日時
      impressions_count: インプレッションのカウント
      start_time: 求人記事の開始時刻
      end_time: 求人記事の終了時刻
  -
    table: bookmarks
    tableComment: ユーザーがブックマークした求人記事のテーブル
    columnComments:
      user_id: ブックマークしたユーザーのID
      article_id: ブックマークされた求人記事のID
      created_at: 作成日時
      updated_at: 更新日時
  -
    table: categories
    tableComment: 求人記事のカテゴリテーブル
    columnComments:
      name: カテゴリ名
      created_at: 作成日時
      updated_at: 更新日時
  -
    table: category_articles
    tableComment: 求人記事とカテゴリの中間テーブル
    columnComments:
      category_id: カテゴリのID
      article_id: 求人記事のID
      created_at: 作成日時
      updated_at: 更新日時
  -
    table: impressions
    tableComment: インプレッションのテーブル
    columnComments:
      impressionable_type: インプレッションを持つオブジェクトの型
      impressionable_id: インプレッションを持つオブジェクトのID
      user_id: インプレッションを持つユーザーのID
      controller_name: コントローラ名
      action_name: アクション名
      view_name: ビュー名
      request_hash: リクエストハッシュ
      ip_address: IPアドレス
      session_hash: セッションハッシュ
      message: メッセージ
      referrer: 参照元
      params: パラメータ
      created_at: 作成日時
      updated_at: 更新日時
  -
    table: likes
    tableComment: ユーザーがいいねした求人記事のテーブル
    columnComments:
      user_id: いいねしたユーザーのID
      article_id: いいねされた求人記事のID
      created_at: 作成日時
      updated_at: 更新日時
  -
    table: applicants
    tableComment: 求職者テーブル
    columnComments:
      name: 求職者の名前
      user_id: この求職者がアプリのユーザーである場合のID
      created_at: 作成日時
      updated_at: 更新日時
  -
    table: applicant_articles
    tableComment: 求職者と求人記事の関連付けテーブル
    columnComments:
      applicant_id: 求職者のID
      article_id: 求人記事のID
      created_at: 作成日時
      updated_at: 更新日時
  -
    table: users
    tableComment: アプリケーションのユーザー情報テーブル
    columnComments:
      email: メールアドレス
      created_at: 作成日時
      updated_at: 更新日時
