# 接続先として、データベースの種類(`mysql`)、ユーザ名(`dbuser`)、パスワード(`dbpass`)、ホスト名(`localhost`)、ポート(`3306`)、データベース名(`dbname`)を以下のように記載します
dsn: postgresql://tanishi:@localhost:5432/my_proj_development?sslmode=disable

# ドキュメントのディレクトリを指定します
docPath: doc/schema

comments:
  -
    table: articles
    tableComment: articles table
    columnComments:
      body: 日記の本文
      user_id: 日記を書いたユーザー
