version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:latest
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
volumes:
  db-volume:
