---
ja:
  keiho:
    2020:
      1:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。（解答欄は，［No.）］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，Xに対し，暴行や脅迫を用いて，自殺するように執拗に要求し，要求に応じて崖から海に飛び込んで自殺するしかないとの精神状態に陥らせた上で，Xを崖から海に飛び込ませて死亡させた。この場合，甲に，Xに対する殺人罪は成立しない。
          2: 2．甲は，追死する意思がないのにあるように装い，その旨誤信したXに心中を決意させた上で，毒物を渡し，それを飲み込ませて死亡させた。この場合，甲に，Xに対する殺人罪は成立しない。
          3: 3．甲は，財物を奪取するために，当該財物の占有者Xに対し，反抗を抑圧するに足りる程度の暴行や脅迫を用いて，当該財物を差し出すしかないとの精神状態に陥らせた上で，当該財物を差し出させた。この場合，甲に，Xに対する強盗罪は成立せず，窃盗罪の間接正犯が成立する。
          4: 4．甲は，日頃から暴行を加えて自己の意のままに従わせて万引きをさせていた満12歳の実子Xに対し，これまでと同様に万引きを命じて実行させた。この場合，Xが是非善悪の判断能力を有する者であれば，甲に，窃盗罪の間接正犯は成立せず，Xとの間で同罪の共同正犯が成立する。
          5: 5．甲は，Xが管理する工事現場に保管されている同人所有の機械を，同人に成り済まして，甲をXであると誤信した中古機械買取業者Yに売却し，同人に同機械を同所から搬出させた。この場合，甲に，Xに対する窃盗罪の間接正犯が成立する。
          6:
          7:
          8:
      2:
        questions: 横領の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものを2個選びなさい。（解答欄は，［No.，［No.3］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，乙からの委託に基づき，同人所有の衣類が入った，施錠されていたスーツケース1個を預かり保管していたところ，衣類を古着屋に売却して自己の遊興費を得ようと考え，勝手に開錠し，中から衣類を取り出した。この場合，遅くとも衣類を取り出した時点で不法領得の意思の発現と認められる外部的行為があったといえるから，甲には，横領罪が成立する。
          2: 2．甲は，乙と共に一定の目的で積み立てていた現金を1個の金庫の中に入れて共同保管していたところ，乙に無断でその現金全てを抜き取り，自己の遊興費に費消した。この場合，甲には，横領罪が成立する。
          3: 3．株式会社の取締役経理部長甲は，同会社の株式の買い占めに対抗するための工作資金として自ら業務上保管していた会社の現金を第三者に交付した。この場合，甲が，会社の不利益を回避する意図を有していたとしても，当該現金の交付が会社にとって重大な経済的負担を伴うもので，甲が自己の弱みを隠す意図をも有していたなど，専ら会社のためにしたとは認められないときは，甲には，業務上横領罪が成立する。
          4: 4．甲は，乙から某日までに製茶を買い付けてほしい旨の依頼を受け，その買付資金として現金を預かっていたところ，その現金を確実に補填するあてがなかったにもかかわらず，後日補填するつもりで自己の遊興費に費消した。この場合，甲がたまたま補填することができ，約定どおりに製茶の買い付けを行ったとしても，甲には，横領罪が成立する。
          5: 5．甲は，自己が所有し，その旨登記されている土地を乙に売却し，その代金を受領したにもかかわらず，乙への移転登記が完了する前に，同土地に自己を債務者とし丙を抵当権者とする抵当権を設定し，その登記が完了した。この場合，同抵当権が実行されることなく，後日，その登記が抹消されたとしても，甲には，横領罪が成立する。
          6:
          7:
          8:
      3:
        questions: 学生A及びBは，過剰防衛に関する次の【事例】について，後記【会話】のとおり議論している。【会話】の中の①から④までの（）内から適切なものを選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。（解答欄は，［No.）］【事例】Ⅰ．甲は，同じ居室にいた乙が机を押し倒してきたため，反撃として，同机を乙に向けて押し返した。これにより，乙は転倒し，左手中指の腱を断裂した。乙は，机の下敷きになっており，直ちに強い攻撃はできなかったが，体勢を立て直せば間もなく攻撃を再開できる状況であった。甲は，引き続き，防衛の意思で，必要な限度を超えて，乙の顔面を殴ったが，これにより乙に怪我は生じなかった。Ⅱ．甲は，乙からいきなり殴られ，更に攻撃を加えられそうになったので，反撃として，乙の顔面を殴った。乙は転倒して頭部を地面に打ち付け，意識を失って動かなくなったが，腹が立っていた甲は，引き続き，専ら攻撃の意思で，倒れている乙の胸部を蹴り付け，肋骨骨折を負わせた。その後，乙は，頭部を地面に打ち付けた際に生じた脳内出血が原因で死亡した。【会話】学生A.Ⅰの事例で，甲が机を押し返した行為は，急迫不正の侵害に対する反撃だけど，その行為と乙の顔面を殴った行為との関係は，どのように考えるべきだろうか。学生B．その点は，時間的・場所的な関係や甲の主観面等に照らし，①（a．別個の行為・b．一連一体の行為）と捉えるべきだろう。学生A．そうすると，甲には，どのような犯罪が成立するだろうか。学生B．甲には，②（c．過剰防衛としての傷害罪が成立する・d．暴行罪のみが成立する）だろう。学生A．Ⅱの事例でも，甲が乙の顔面を殴った行為は，急迫不正の侵害に対する反撃であることに変わりないよね。甲には，どのような犯罪が成立するだろうか。学生B．乙が意識を失って動かなくなっているのに，専ら攻撃の意思で蹴り付けているのだから，顔面を殴る行為と胸部を蹴り付ける行為の間には断絶があると思う。甲には，③（e．過剰防衛としての傷害致死罪が成立する・f．傷害罪のみが成立する）という結論が妥当だろう。学生A．Ⅱの事例で，B君のように，両暴行の間に断絶があると解すると，④（g．違法性が否定されるべき行為が遡って違法と評価されることになる・h．専ら攻撃の意思で胸部を蹴り付けた場合の方が，防衛の意思で胸部を蹴り付けた場合より軽い罪が成立する）という問題が生じるのではないか。学生B．その点は，量刑上考慮すれば足りるという説明が可能なのではないか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a③e
          2: 2．①b④g
          3: 3．②d③e
          4: 4．②c④g
          5: 5．③f④h
          6:
          7:
          8:
      4:
        questions: 遺棄の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，［No.，[No.6]順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．遺棄罪（刑法第217条）の成立には，生命に対する危険の発生が必要である。
          2: 2．妊婦の依頼を受け，母体保護法上，許されない堕胎を行った産婦人科医師が，それにより出生した未熟児について，医療設備の整った病院に搬送することが容易であり，同病院の医療を受けさせれば，同児が短期間内に死亡することはなく，むしろ生育する可能性がある場合において，そのことを認識しながら，生存に必要な保護を行わず同児を死亡させたときは，同医師に，保護責任者遺棄等致死罪（刑法第219条，第218条）が成立し得る。
          3: 3．保護責任者遺棄等罪（刑法第218条）にいう「老年者，幼年者，身体障害者又は病者」は，例示列挙であり，同罪の客体はそれらの者に限られず，扶助を必要とする者であれば足りる。
          4: 4．保護責任者遺棄等致傷罪（刑法第219条，第218条）には，傷害結果に故意がある場合は含まれない。
          5: 5．保護責任者遺棄等罪（刑法第218条）における遺棄には，置き去りは含まれない。
          6:
          7:
          8:
      5:
        questions: 共犯と錯誤に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの個数を後記1から5までの中から選びなさい。
        answer:
          a: ア．甲及び乙がAに対する暴行を共謀したが，Aの態度に激高した甲が殺意をもってAを殺害した場合，甲及び乙に殺人罪の共同正犯が成立するが，乙は傷害致死罪の刑で処断される。
          i: イ．甲及び乙がAに対する強盗を共謀したが，その強盗の機会に，甲が過失によってAに傷害を負わせた場合，甲及び乙に強盗致傷罪の共同正犯が成立する。
          u: ウ．甲及び乙が共謀して，公務員Aに虚偽の内容の公文書の作成を教唆することにしたが，乙はAを買収することに失敗したため，甲に無断で，Bに公文書を偽造することを教唆し，Bが公文書を偽造した場合，甲に虚偽公文書作成罪の教唆犯が成立する。
          e: エ．甲が乙にA方に侵入して金品を窃取するように教唆して，その犯行を決意させたが，乙はA方と誤認して隣のB方に侵入してしまい，B方から金品を窃取した場合，甲にB方への住居侵入罪及びBに対する窃盗罪の教唆犯は成立しない。
          o: オ．甲が乙の傷害行為を幇助する意思で，乙に包丁を貸与したところ，乙が殺意をもってその包丁でAを刺殺した場合，甲に殺人罪の幇助犯が成立し，傷害致死罪の幇助犯は成立しない。
        additional_answer:
          1: 1．0個
          2: 2．1個
          3: 3．2個
          4: 4．3個
          5: 5．4個
          6:
          7:
          8:
      6:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。（解答欄は，[No.8]）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，乙から，大学の入学試験を代わりに受けてほしいと頼まれてこれを引き受け，乙に成り済まして入学試験を受け，乙名義で答案を作成して提出した。この場合，甲に有印私文書偽造罪が成立する。
          2: 2．甲は，架空請求により金銭をだまし取るために使おうと考え，実在しない「法務局民事訴訟管理センター」名義で，契約不履行による民事訴訟が提起されているので連絡をされたい旨記載されたはがきを印刷し，一般人をして実在する公務所が権限内で作成した公文書であると誤信させるに足りる程度の形式・外観を備えた文書を作成した。この場合，甲に有印公文書偽造罪が成立する。3.甲は，X市立病院の事務長を務める公務員であるが，同病院のために発注書を作成する権限を授与されていないのに，行使の目的で，同病院が業者Aに医療器具を発注していないにもかかわらず，それを発注した旨を記載した内容虚偽の「X市立病院事務長甲」名義の発注書を作成した。この場合，甲に虚偽有印公文書作成罪が成立する。
          3:
          4: 4．甲は，支払督促制度を悪用して乙の財産を不正に差し押さえるなどして金銭を得ようと考え，乙に対する内容虚偽の支払督促を簡易裁判所に申し立てた上，乙宛ての支払督促正本等を配達しようとした郵便配達員に対し，乙本人を装い，郵便送達報告書の「受領者の押印又は署名」欄に乙の氏名を記載して提出し，支払督促正本等を受領した。この場合，甲に有印私文書偽造罪が成立する。
          5: 5．甲は，消費者金融業者に提出する目的で，公文書である乙の国民健康保険被保険者証の氏名欄に自己の氏名が印刷された紙を貼り付けた上で，複写機を使用してこれをコピーし，一般人をして甲の国民健康保険被保険者証の真正なコピーであると誤信させるに足りる程度の形式・外観を備えたものを作成した。この場合，甲に有印公文書偽造罪が成立する。
          6:
          7:
          8:
      7:
        questions: 学生A，B及びCは，後記【会話】のとおり議論している。【会話】中の①から⑤までの（）内から適切なものを選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。（解答欄は，[No.9]）【会話】学生A．人に意図的に害悪を加えることは，本来であれば許されないはずです。それにもかかわらず，刑罰という苦痛を人に与えることが正当化される実質的な根拠は何でしょうか。学生B．私は，刑罰は犯罪に対する非難を含むもので，その意味で①（a．応報・b．社会統制の手段）としての性質を持ち，②（c．犯罪者の改善更生・d．正義の実現）という観点に照らして，犯罪に対する反作用であること自体に刑罰の正当化根拠を見いだすことができると考えます。もう少し詳しく言うと，自らの意思で犯罪行為を行うことを決意し実行した犯罪者に対して，その意思決定を回顧的に非難する点に刑罰の正当化根拠があるということです。学生C．B君は，③（e．非決定論・f．決定論）の立場を前提にしているのですね。しかし，（①）としての刑罰自体に刑罰を正当化する根拠があるという説明では，刑罰を科すことそれ自体が目的ということになりませんか。刑罰は，国家の制度の一種なのだから，国民の現実的な利益を実現する手段として合目的性の観点から正当化されるべきではないでしょうか。私は，刑罰を科すことが許される根拠は，④（g．被害感情の緩和・h．犯罪の予防）にあると思います。犯罪によって得られる快楽を上回る苦痛を刑罰として予告すれば，一般人に対する威嚇的な効果があるからです。刑罰は（④）という公的利益の達成に資するために，人に科すことが正当化されるのだと思います。学生A．私も，基本的にC君の考えに賛成ですが，（④）の観点を強調しすぎると，⑤（i．責任・j．被害感情）の程度を超える刑罰を科すことも肯定されかねず，刑法の基本原則に反する帰結をもたらすことになるのではないでしょうか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a③f
          2: 2．①b⑤j
          3: 3．②d④h
          4: 4．②c⑤i
          5: 5．③e④g
          6:
          7:
          8:
      8:
        questions: 公務執行妨害罪に関する次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．甲は，市役所の生活保護係職員乙による生活保護に関する説明に不満を抱き，同人に罵声を浴びせながら抗議するとともに，丸めたパンフレットを同人の顔面付近に2，3回突き付け，そのうち1回はパンフレットの先端が同人の顎に触れ，さらに，約2回にわたり，乙が座っている椅子を両手で持って椅子の前脚を床から持ち上げては落とすことによりその身体を揺さぶった。甲の行為は，公務執行妨害罪にいう「暴行」に当たらないので，甲に公務執行妨害罪は成立しない。［No.10］
          i: イ．甲は，警察官乙らが捜索差押許可状に基づき甲方の捜索に来た際，乙らにより甲方玄関ドアの鍵が開けられる前に，居室内にあった覚醒剤入りの注射器を足で踏み付けて壊した。甲の行為は，公務執行妨害罪にいう「暴行」に当たらないので，甲に公務執行妨害罪は成立しない。［No.11］
          u: ウ．窃盗犯人甲は，その窃盗行為を目撃した制服警察官乙から追跡されている途中で，逮捕を免れるため，同人に対し，その反抗を抑圧するに足りる程度の暴行を加えて抵抗し，そのまま逃走した。甲には事後強盗罪のみが成立し，公務執行妨害罪は成立しない。［No.12］
          e: エ．甲は，日本国内にある外国大使館の職員乙がその大使館の業務に従事していた際に，同人の顔面を殴った。乙は「公務員」に当たらないので，甲に公務執行妨害罪は成立しない。［No.13］
          o: オ．甲は，税務調査を免れるため，同調査のため甲方に来た所轄税務署職員乙の顔面を殴った。その際，乙は，規則により調査時に携帯が義務付けられている検査章を携帯していなかったが，甲がその呈示を求めることはなかった。乙に規則違反があった以上，乙の調査は職務の権限外の行為であり，甲に公務執行妨害罪は成立しない。［No.14］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      9:
        questions: 原因において自由な行為に関する次の各【見解】に従って後記の各【事例】における甲の罪責を検討した場合，後記1から5までの各【記述】のうち，誤っているものはどれか。【見解】A．責任能力がある状態で行われた原因行為を実行行為と捉える。B．責任能力を欠いた状態で行われた結果行為を実行行為と捉えつつ，責任能力は意思決定時に存在すれば足り，必ずしも実行行為時に存在することは必要ない。【事例】Ⅰ．甲は，X宅に赴いて同人を殺害しようと決意し，心神喪失状態に陥る可能性があることを認識しつつ，自宅において景気づけのために覚醒剤を使用したところ，心神喪失状態に陥り，当初の計画どおりXを殺害した。Ⅱ．甲は，X宅に赴いて同人を殺害しようと決意し，心神喪失状態に陥る可能性があることを認識しつつ，自宅において景気づけのために覚醒剤を使用したところ，心神喪失状態に陥ったが，X宅には赴かず，Xの殺害には及ばなかった。Ⅲ．甲は，覚醒剤を使用すると粗暴になり周囲に暴行を加える習癖があると知りつつ，覚醒剤を使用した結果，心神喪失状態に陥り，Xと口論になり，殺意を生じて同人を殺害した。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．Aの見解によれば，事例Ⅰでは，甲に，Xに対する殺人既遂罪が成立し得る。
          2: 2．Aの見解を採った上で，未遂犯の成立時期は結果発生の現実的な危険性が生じた段階に求められるべきで，それが常に実行行為の開始段階に認められる必然性はないと考えれば，事例Ⅱでは，甲に，Xに対する殺人未遂罪は成立しない。
          3: 3．Aの見解によれば，事例Ⅲでは，甲に，Xに対する殺人既遂罪が成立し得る。
          4: 4．Bの見解によれば，事例Ⅰでは，甲に，Xに対する殺人既遂罪が成立し得る。
          5: 5．Bの見解によれば，事例Ⅱでは，甲に，Xに対する殺人未遂罪は成立しない。
          6:
          7:
          8:
      10:
        questions: 親族間の犯罪に関する特例について次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。（解答欄は，[No.16]）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲が，実母乙の使用するタンスから，乙がその友人丙から預かり同タンスに保管していた丙所有の宝石を窃取した場合，甲の窃取行為について刑は免除されない。
          2: 2．甲が，実父乙の内縁の妻である丙が乙から預かり保管していた乙所有の時計を窃取した場合，甲の窃取行為について刑は免除されない。
          3: 3．甲は，家庭裁判所から実父乙の成年後見人に選任されていたところ，後見の事務として業務上預かり保管中の乙の預金を引き出して自己の借金の返済に充てた場合，甲の横領行為について刑は免除されない。
          4: 4．甲が，友人乙を教唆して，乙の実父丙が所有し，管理している自動車を窃取させた場合，甲の窃盗教唆行為について刑は免除されない。
          5: 5．甲が，同居していない祖父乙を恐喝して同人から現金の交付を受けた場合，甲の恐喝行為について刑は免除されない。
          6:
          7:
          8:
      11:
        questions: 次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからオの順に［No.17］から［No）21］
        answer:
          a: ア．甲及び乙は，深夜，路上を一人で歩いていたV女を見付け，約6キロメートル先のひとけのない工事現場にV女を連れ込んで強制的にV女と性交しようと決意し，二人でV女の背後からその身体を抱きかかえながら，付近に停めていた自動車にV女を押し込んで乗せ，同車を発進させたが，性交には至らなかった。甲及び乙には，強制性交等未遂罪の共同正犯が成立する。［No.17］
          i: イ．甲は，強制的にV女と性交しようと決意し，深夜，路上において，V女を押さえ付けて反抗を抑圧したが，付近から人の声が聞こえたため性交を諦めて，V女のハンドバッグから財布を奪い取ろうと考え，「騒ぐな。殺すぞ。」と申し向けてV女の畏怖心を強めた上，財布を奪い取った。甲には，強盗・強制性交等未遂罪が成立する。［No.18］
          u: ウ．甲は，Vが居住する木造家屋に火をつけて焼損しようと考え，同家屋台所において，プロパンガスを多量かつ長時間にわたり放出するとともに，ガソリン約18リットルを撒布したが，点火行為には至らなかった。甲には，現住建造物等放火未遂罪が成立する。［No.19］
          e: エ．甲は，Vを殺害する意思で，毒入りの菓子を箱詰めし，それをV宅に宛てて宅配便で発送した。しかし，仕事に嫌気が差した配達員により，その菓子は配達途中に川に捨てられた。甲には，殺人未遂罪が成立する。［No.20］
          o: オ．甲は，V宅に侵入し，金品を強取しようと決意し，Vを脅すためのナイフを入手した上，それを携行してV宅に向かった。しかし，V宅に至る手前で，罪悪感を覚え，計画を中止することに決め，自宅に引き返した。甲には，強盗予備罪の中止犯が成立する。［No.21］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      12:
        questions: 業務妨害罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。（解答欄は，[No.22]）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．利用客のキャッシュカードの暗証番号等を盗撮する目的で，現金自動預払機が2台設置されている銀行の無人出張所において，そのうち1台にカメラを設置し，当該現金自動預払機に客を誘導する意図で，一般客を装い，もう1台の現金自動預払機を2時間占拠した場合，偽計業務妨害罪が成立する。
          2: 2．講演会の主催者が閲覧する可能性を認識した上，インターネット上の掲示板に，当該講演会の会場に放火するという趣旨の書き込みをし，当該主催者に閲覧させた結果，当該講演会を中止させた場合，威力業務妨害罪が成立する。
          3: 3．公職選挙法上の選挙長による立候補届出受理事務を妨害する目的で，その届出場所において，突如大声を発し，ボールペンを机にたたき付けるという暴行・脅迫に至らない言動を用いてその事務を滞らせた場合，威力業務妨害罪が成立する。
          4: 4．知人Aに対する嫌がらせの目的で，同人に成り済まし，同人に無断で宅配ピザ店に電話をかけてピザ50枚を注文し，これを同人宅まで配達することを依頼して，同店店員にピザ50枚を作らせ，配達させた場合，偽計業務妨害罪が成立する。
          5: 5．弁護士Xの弁護士としての活動を困難にさせる目的で，同人から，同人が携行し，その業務にとって重要な訴訟記録等が入ったかばんを奪い取った上，自宅に保管した場合，偽計業務妨害罪が成立する。
          6:
          7:
          8:
      13:
        questions: 幇助犯の成否について，学生A及びBが次の【会話】のとおり議論している。【会話】中の①から⑤までの（）内に後記アからオまでの【事例群】から適切な事例を入れた場合，正しいものの組合せは，後記1から5までのうちどれか。（解答欄は［No.）3］【会話】学生A．(①)に，乙に幇助犯は成立すると思うか。学生B．幇助行為と結果との間に，物理的因果性も心理的因果性もないと思うので，乙に幇助犯は成立しないだろう。学生A．(②)は，どうだろうか。学生B．乙の行為の有無にかかわらず，生じた結果は同じだったと考えると，共犯行為と結果との間の因果関係に欠けるという結論になるようにも思えるね。学生A．しかし，幇助犯は，正犯の実行が容易になり，結果の発生が促進されたという関係さえあれば，行為と結果との因果関係を認めるのが判例だろう。学生B．なるほど。乙がいることで甲が安心でき，精神的に後押ししたという心理的因果性がありそうなので，乙に幇助犯の成立を認めるべきだね。学生A．(③)は，どうだろうか。学生B．(②)と同じ理由で，乙に幇助犯の成立が認められるように思う。ただ，教唆犯の成立を認める余地もあるかもしれないね。学生A．(④)は，どうだろうか。学生B．判例は片面的幇助を肯定する以上，乙に幇助犯が成立するんじゃないか。学生A．(⑤)は，どうだろうか。学生B．この場合，乙の立場を考えれば，幇助犯が成立すると思うよ。【事例群】
        answer:
          a: ア．乙が，甲が空き巣に入ろうとしていることを知りながら，甲に黙ってV方玄関の施錠を外したところ，甲が玄関からV方に侵入し，空き巣に成功した場合
          i: イ．乙が，空き巣に入ろうと決意していた甲から頼まれ，甲が空き巣に入る際，見張りをしていたところ，特に何も起きないまま，甲が空き巣に成功した場合
          u: ウ．甲が万引きをしようとしていることを目撃した店員乙が，甲と意思を通じることなく，甲の万引きを黙認し，甲が万引きに成功した場合
          e: エ．甲が空き巣に入ることを知り，乙が甲に黙って見張りをしていたが，特に何も起きないまま，甲が空き巣に成功した場合
          o: オ．乙が空き巣に使うことができるものとしてV方の合鍵を甲に渡したため，甲がV方に行ったが，無施錠であったため合鍵を使わず，空き巣に成功した場合
        additional_answer:
          1: 1．①イ②エ③ア④ウ⑤オ
          2: 2．①イ②エ③オ④ア⑤ウ
          3: 3．①エ②イ③ウ④オ⑤ア
          4: 4．①エ②イ③オ④ア⑤ウ
          5: 5．①エ②イ③オ④ウ⑤ア
          6:
          7:
          8:
      14:
        questions: 放火罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，［No.［No.25］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲が自己の所有する空き家に放火したが，公共の危険が生じなかった場合，甲には，非現住建造物等放火未遂罪が成立する。
          2: 2．甲が乙に頼まれて，乙所有の大型家具を，丙が居住する家屋に近接する甲所有の畑地で燃やし始めたところ，周辺に火の粉が飛び散り，予期に反して，同家屋の屋根のひさしに飛び火して，同ひさしを焼損させたところで火が消し止められた場合，甲には，延焼罪が成立する。
          3: 3．甲が住宅内にいる乙を殺害する目的で放火し，住宅が焼失した上，乙が死亡した場合，甲には，殺人罪は成立せず，現住建造物等放火罪のみが成立する。
          4: 4．甲が，一部の部屋のみが現に住居に使用されている木造の集合住宅の空き部屋に放火し，同室のみを焼損させた場合，甲には，現住建造物等放火罪が成立する。
          5: 5．甲が憂さ晴らしの目的で，甲の世帯を含めて計30世帯が居住するマンション内部に設置されたエレベーターのかご内に，灯油を染み込ませて点火した新聞紙を投げ入れて放火したが，エレベーターのかごの側壁を焼損したにとどまり，住居部分には延焼しなかった場合，甲には，現住建造物等放火未遂罪が成立する。
          6:
          7:
          8:
      15:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものを2個選びなさい。（解答欄は［No.2［No.27］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，火災保険金をだまし取る目的で，同居する家族が不在の間に，自宅に放火して焼失させ，その後，火災原因を偽って火災保険金の支払を受けた。この場合，甲には，現住建造物等放火罪及び詐欺罪が成立し，これらは併合罪となる。
          2: 2．甲は，強盗目的で，乙方に侵入した上，乙及び丙をそれぞれ殴打して緊縛し，その際，両名に怪我を負わせ，乙が管理していた現金100万円を強取した。この場合，甲には，住居侵入罪及び1個の強盗致傷罪が成立し，これらは牽連犯となる。
          3: 3．甲は，乙を教唆して丙占有の自動車を盗むことを決意させ，乙にこれを実行させた後，乙から頼まれて，同自動車を預かり保管した。この場合，甲には，窃盗教唆罪及び盗品等保管罪が成立し，これらは牽連犯となる。
          4: 4．甲は，乙を殺害して金品を強取しようと考え，甲の自宅内で乙を殺害して現金を強取した後，引き続き，その死体を自宅の床下に埋めて遺棄した。この場合，甲には，強盗殺人罪及び死体遺棄罪が成立し，これらは併合罪となる。
          5: 5．甲は，乙名義で預金口座を開設する目的で，同人に成り済まし，同人名義で口座開設申込書を作成し，これを銀行の係員に提出して，乙名義の預金通帳の交付を受けた。この場合，甲には，有印私文書偽造罪，同行使罪及び詐欺罪が成立し，これらは牽連犯となる。
          6:
          7:
          8:
      16:
        questions: 名誉毀損罪及び侮辱罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。（解答欄は，［No.）8］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．名誉毀損罪及び侮辱罪の保護法益は，いずれも人の外部的名誉であり，法人については，侮辱罪の客体になり得ない。
          2: 2．死者であっても，その外部的名誉を保護すべきことに変わりはないので，死者の名誉を毀損する事実が摘示された場合も，その事実の真偽にかかわらず，名誉毀損罪が成立し得る。
          3: 3．特定かつ少数の者に特定人の名誉を毀損する事実を摘示した場合，その内容が拡散する可能性があったとしても，「公然と」事実を摘示したことにはならない。
          4: 4．風評の形式を用いて人の社会的評価を低下させる事実が摘示された場合，刑法第230条の2にいう「真実であることの証明」の対象となるのは，風評が存在することではなく，そのような風評の内容たる事実が存在することである。
          5: 5．表現方法が嘲笑的であるとか，適切な調査がないまま他人の文章を転写しているなどといった，事実を摘示する際の表現方法や事実調査の程度は，摘示された事実が刑法第230条の2にいう「公共の利害に関する事実」に当たるか否かを判断する際に考慮すべき要素の一つである。
          6:
          7:
          8:
      17:
        questions: 緊急避難（刑法第37条第1項）に関する次の【記述】の中の①から⑥までの（）内に，後記アからスまでの【語句群】から適切な語句を入れた場合，（）内に入るものの組合せとして正しいものは，後記1から5までのうちどれか。なお，①から⑥までの（）内にはそれぞれ異なる語句が入る。（解答欄は，[No.29]）【記述】緊急避難を（①）と解する見解によれば，その不処罰の根拠は，切迫した心理状態のために適法な行為を期待し得ないことに求められる。この見解によれば，緊急避難によって侵害を転嫁される第三者は緊急避難行為に対して（②）で対抗できることになる。この見解に対しては，刑法第37条第1項が（③）を守るための緊急避難を認めていることと整合しないという批判がある。他方，緊急避難を（④）と解する見解によれば，その不処罰の根拠は，法益が衝突する状況下で被侵害法益と同等以上の法益を保全する行為は社会全体の利益を（⑤）させるものではないことに求められる。また，この見解に立つと，緊急避難行為に対して（②）で対抗することを認めるのは困難である。さらに，緊急避難を基本的には（④）と解しつつ，保全法益と被侵害法益がいずれも生命である場合には，（①）であると解する見解もある。この見解は，自己又は第三者の生命に対する危難を避けるために無関係の第三者の生命を犠牲にする行為を（⑥）と評価するのは不当であるという考え方に基づくものである。【語句群】
        answer:
          a: ア．違法性阻却事由
          i: イ．責任阻却事由
          u: ウ．個人的法益
          e: エ．社会的法益
          o: オ．他人の法益カ．自己の法益キ．増加ク．減少ケ．正当行為コ．正当防衛サ．緊急避難シ．違法ス．違法でない
        additional_answer:
          1: 1．①ア③ウ⑤ク
          2: 2．①イ③エ⑤キ
          3: 3．②ケ④ア⑥ス
          4: 4．②コ⑤ク⑥ス
          5: 5．③オ④ア⑥シ
          6:
          7:
          8:
      18:
        questions: 詐欺罪に関する次の【見解】についての後記アからオまでの各【記述】を検討し，正しい場合には1を，誤っている場合には2を選びなさい。【見解】規約上，会員である名義人のみがクレジットカードを利用できるものとされ，その利用者が会員本人であることの確認義務が加盟店に課されている場合，名義人に成り済まし，クレジットカードを利用して商品を購入する行為は，その利用が名義人から許されており，かつ，利用代金が規約に従い名義人において決済されることが見込まれるときであっても，詐欺罪が成立する。【記述】
        answer:
          a: ア．この【見解】に対しては，名義人に依頼されてクレジットカードを利用して商品を購入した場合，詐欺罪の実質的違法性がなく，財産犯として処罰するのは行き過ぎであるとの批判が可能である。［No.30］
          i: イ．この【見解】は，クレジットカード利用者と名義人の同一性が加盟店にとって商品交付の判断の基礎となる重要な事項に当たると理解している。［No.31］
          u: ウ．この【見解】によれば，名義人に成り済ましてクレジットカードを利用して商品を購入する行為について，行為者が，当該名義人において現実に決済されるものと誤信していた場合でも，詐欺罪が成立し得ることとなる。［No.32］
          e: エ．この【見解】は，名義人の個別的な信用を基礎としてクレジットカードシステムが構築されていることを前提に，個々の事案における詐欺罪の成否の判断において，加盟店の経済的損失の有無を重視するものである。［No.33］
          o: オ．この【見解】に対しては，加盟店が名義人以外の利用であることを知りながら，クレジットカードの利用を認めた場合でも詐欺罪の既遂が成立することになり，妥当ではないとの批判が可能である。［No.34］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      19:
        questions: 故意に関する次の各【見解】についての後記1から5までの各【記述】のうち，誤っているものはどれか。（解答欄は，[No.35]）【見解】A．故意の有無については，構成要件を基準にして判断すべきであるところ，殺人罪においては，行為者の認識した事実と発生した事実とが，「およそ人を殺す」という点で一致していれば故意が認められる。また，行為者の認識した客体に対しても，結果が発生した客体に対しても故意犯が成立する。B．故意の有無については，構成要件を基準にして判断すべきであるところ，殺人罪においては，行為者の認識した事実と発生した事実とが，「その人を殺す」という点で一致していなければ故意は認められない。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲が，Xを焼死させようと思い，Xの全身に灯油をかけて火をつけたところ，Xが熱さに耐えかね，火を消そうとして近くの湖に飛び込んで溺死したという事例においては，A，Bいずれの見解でも，甲に殺人既遂罪が成立する。
          2: 2．Aの見解に対しては，甲が殺意をもってXを狙い拳銃を発射したところ，弾丸がXの腕を貫通した上，予想外にYの胸部にも当たり，Xを負傷させるとともにYを死亡させたという事例において，行為者に過剰な故意責任を課すことになり，責任主義に反するとの批判がある。
          3: 3．Bの見解によれば，【記述】2の事例で，甲にYに対する殺人既遂罪が成立する。
          4: 4．Bの見解に対しては，客体の錯誤と方法の錯誤のいずれに当たるのかが必ずしも明らかではない場合において，故意の有無につき，どのように判断するのか明確ではないとの批判がある。
          5: 5．Bの見解によれば，甲がXを殺害しようと考え，Xと似た者を見付けて，Xと思い，その者をナイフで刺し殺したが，実際には，その者はYであったという事例において，甲にYに対する殺人既遂罪が成立する。
          6:
          7:
          8:
      20:
        questions: 次の【事例】に関する後記アからエまでの各【記述】を判例の立場に従って検討した場合，正しいものの個数を後記1から5までの中から選びなさい。（解答欄は，［No.）6］【事例】甲は，某所公園内において，ベンチ上に置いてあるバッグ1個（以下「本件バッグ」という。）を発見し，誰かが置き忘れたものと考え，警察に届け出るため，これを手に取り，同公園から路上に出た。一方，本件バッグをベンチに置き忘れたことに気付いたVは，同公園に戻ろうとして同路上に至ったところ，甲を発見した。Vは，甲が本件バッグを盗んだと疑い，「バッグを返せ」と言いながら，甲の腹部を2回足で蹴り，甲から本件バッグを奪い，さらに，甲を蹴り上げるような仕草を続けた。甲は，Vの暴行を避けようとして，その胸付近を1回平手で突いたところ，その勢いでVが後方に転倒し，後頭部を路面に打ち付け，失神した。甲は，その頃には，Vが本件バッグの所有者であると分かっていたが，Vの態度に怒りを覚えたことなどから，本件バッグを自己のものにしようと考え，失神しているVからこれを取り上げて自宅に持ち帰った。その後，甲が本件バッグ内を確認したところ，V名義の預金口座のキャッシュカード等在中の財布，V所有の携帯電話機等の物品が入っていた。甲は，これらを見て，Vの氏名，勤務先のほか，携帯電話機にわいせつな盗撮画像が保存されていることを知り，これを奇貨とし，Vから上記キャッシュカードの暗証番号を聞き出して上記口座から預金を引き出そうと思い，勤務先にいたVに電話をかけ，「あんた盗撮してるな。警察に携帯を持って行かれたくないなら，あんたのキャッシュカードの暗証番号を教えろ。」と要求するなどした。Vは，この要求を断れば，盗撮の事実が警察に露見すると思い，やむを得ず甲に同暗証番号を教えた。その後，甲は，上記キャッシュカードを用いて現金自動預払機から現金50万円を引き出した。【記述】
        answer:
          a: ア．甲が本件バッグを警察に届け出るために某所公園内から持ち出した行為は，Vによる占有の回復を困難にする行為であるため，窃盗罪又は占有離脱物横領罪が成立する。
          i: イ．Vは本件バッグを甲から取り返す目的で暴行を加えており，この暴行は正当行為に該当するため，甲がVの胸付近を1回平手で突いた行為の違法性が阻却される余地はなく，甲には，暴行罪又は傷害罪が成立する。
          u: ウ．甲が本件バッグをVから取り上げた行為は，甲の暴行に起因するVの失神状態に乗じて本件バッグの占有を取得したといえるため，強盗罪が成立する。
          e: エ．甲が現金自動預払機から現金50万円を引き出した行為は，甲が，これに先行してVから暗証番号を聞き出した時点で，Vの預金の払戻しを受け得る地位を得たことにより，その預金の占有を取得したといえるため，窃盗罪は成立しない。
          o:
        additional_answer:
          1: 1．0個
          2: 2．1個
          3: 3．2個
          4: 4．3個
          5: 5．4個
          6:
          7:
          8:
