---
ja:
  keiho:
    2021:
      1:
        questions: 過失犯に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．共同正犯に関する刑法第60条は，意思の連絡を要件としているので，過失犯には適用されない。
          2: 2．重過失とは，重大な結果を惹起する危険のある不注意な行為をすることをいう。
          3: 3．過失犯の成立に必要となる結果発生の予見可能性は，内容の特定しない一般的・抽象的な危惧感ないし不安感を抱く程度の予見の可能性で足りる。
          4: 4．行為者が法令に違反する行動をした事案においても信頼の原則が適用される場合がある。
          5: 5．ホテルの火災により死傷者が出た場合，火災発生時に現場にいなかったホテル経営者には業務上過失致死傷罪が成立することはない。
          6:
          7:
          8:
      2:
        questions: 住居侵入等の罪に関する次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．甲は，警察署の敷地内に駐車中の捜査用車両のナンバーを把握しようと考え，外部から同敷地内への交通を制限するために設置され，内部をのぞき見ることができない構造になっている高さ
          i: イ．甲は，窃盗の目的で，乙が所有し，その扉や窓に施錠して管理していた空き家に立ち入った。この場合，甲には，邸宅侵入罪が成立する。［No.3］
          u: ウ．甲は，強盗の目的で，面識のない乙方に行き，その意図を隠しながら，玄関前で，「こんばんは。」と挨拶したところ，これを知人による来訪と勘違いした乙が，「どうぞ入ってください。」と答えたので，乙方内に立ち入った。この場合，甲には，住居侵入罪は成立しない。［No.4］
          e: エ．甲は，乙会社が所有するビルに窃盗に入る目的で，同ビルに接しており，同社が設置した門扉及び金網フェンスによって，同ビルの利用のために供されるものであることが明示され，部外者の出入りが制限されている敷地部分に立ち入ったが，同ビルに立ち入る前に警備員に取り押さえられた。この場合，甲には，建造物侵入未遂罪が成立するにとどまる。［No.5］
          o: オ．甲は，住居権者乙の意思に反し，乙方家屋に立ち入ったが，その後，乙から退去を求められたにもかかわらず数時間にわたって同家屋に居座った。この場合，甲には，住居侵入罪だけでなく，不退去罪も成立し，両罪は併合罪となる。［No.6］
        additional_answer:
          1:
          2: 2．5メートル，幅0．2メートルの同警察署の塀をよじ登り，その上に立った。この場合，甲には，建造物侵入未遂罪が成立するにとどまる。［No.2］
          3:
          4:
          5:
          6:
          7:
          8:
      3:
        questions: 次の【事例】及び【判旨】に関する後記1から5までの各【記述】のうち，正しいものを2個選びなさい。（解答欄は，［No.7］，［No.8］順不同）【事例】Xは，Aに電話を掛け，本来支払う必要のない違約金をAが支払わなければならない旨うそを告げた。Aはうそを見破ったが，警察官から，「だまされたふり作戦」（引き続き犯人側の要求どおりに行動しているふりをして犯人を現行犯逮捕しようとする捜査手法をいう。）に協力することを依頼された。Aはこれに応じ，現金を某所に送付するようにというXの指示に従ったふりをして，現金の代わりに模擬紙幣が入った荷物を同所に向けて発送した。その後，被告人は，Xから，報酬を支払う約束の下に荷物の受領を依頼され，詐欺の被害金を受け取る役割である可能性を認識しつつ，これを引き受け，「だまされたふり作戦」が開始されたことを認識せずに，上記場所で同荷物を受領し，警察官に現行犯逮捕された。【判旨】被告人は，本件につき，Xによる欺罔行為がされた後，「だまされたふり作戦」が開始されたことを認識せずに，Xと共謀の上，本件を完遂する上で欺罔行為と一体のものとして予定されていた受領行為に関与している。そうすると，「だまされたふり作戦」の開始の有無にかかわらず，被告人は，その加功前の欺罔行為を含めた本件につき，詐欺未遂罪の共同正犯としての責任を負うと解するのが相当である。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．【判旨】は，被告人に詐欺未遂罪の共同正犯が成立するには，前記荷物の受領行為自体に未遂犯として処罰すべき法益侵害の危険性が必要であり，その危険性の有無は，一般人が認識可能であった事情及び被告人が特に認識した事情に基づいて判断すべきという立場に立った上で，一般人は，Aが「だまされたふり作戦」に協力している事実を認識することが可能であったとの評価を前提としている。
          2: 2．【判旨】に対しては，Aがうそを見破っている以上，被告人が関与した時点では，詐欺罪が既遂に至る可能性がなく，被告人が法益侵害の危険性を惹起したとはいえないとの批判が考えられる。
          3: 3．【判旨】を前提とした場合，強盗罪における財物奪取行為のみに関与した者には，同罪の共同正犯の成立を認めることはできない。
          4: 4．【判旨】は，欺罔行為と財物受領行為の一体性を根拠として，財物受領行為のみに関与した者について，詐欺罪の承継的共同正犯を認めるとの立場と矛盾するものではない。
          5: 5．【判旨】によれば，被告人がXのAに対する欺罔行為の内容を認識していても，同欺罔行為を自己の犯罪の手段として積極的に利用する意思がない場合には，詐欺未遂罪の共同正犯の成立が否定される。
          6:
          7:
          8:
      4:
        questions: 汚職の罪に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。が成立する。
        answer:
          a:
          i:
          u: ウ．公務員が，その職務に関し，賄賂を収受したとき，当該職務が適切なものであっても単純収賄罪（刑法第197条第1項前段）が成立する。
          e: エ．公務員であった者が，その在職中に請託を受けて職務上不正な行為をしたことに関し，退職後に賄賂を収受した場合，事後収賄罪（刑法第197条の3第3項）は成立しない。
          o: オ．犯人が収受した賄賂は，任意的没収の対象となる。
        additional_answer:
          1: 1．アウ
          2: 2．アオ
          3: 3．イウ
          4: 4．イエ
          5: 5．エオ
          6:
          7:
          8:
      5:
        questions: 次の【事例】及び各【見解】に関する後記1から5までの各【記述】を検討した場合，誤っているものはどれか。なお，共同正犯に関する刑法第60条は，結果的加重犯にも適用されることを前提とする。【事例】甲乙両名は，2人でVに向けて石を投げることにし，それぞれVに石を投げた。その際，甲には，傷害の故意しかなかったのに対し，乙には，未必的な殺意があった。両名が投げた石のうち，甲の投げた石がVの頭部に当たり，Vが死亡するに至った。【見解】A説：共同正犯とは，数人が共同して特定の犯罪を行うことであり，構成要件の間に重なり合いがあれば，そのうちのより重い犯罪について共同正犯の成立を認め，軽い犯罪の故意しか有しない者には，軽い犯罪の刑を科す。B説：共同正犯とは，数人が共同して特定の犯罪を行うことであり，構成要件の重なり合う限度で軽い犯罪の共同正犯の成立を認め，重い犯罪の故意を有する者には，共同正犯とは別に，その故意に応じた単独犯の成立を認める。C説：共同正犯とは，数人が犯罪に至る行為過程を含めた行為を共同することであり，特定の犯罪を共同して実現する場合はもちろん，単なる行為を共同して各自の意図する犯罪を実現する場合も，それぞれの行為について共同正犯の成立を認める。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．A説からは，甲と乙に殺人罪の共同正犯が成立するとの結論が導かれる。
          2: 2．A説に対しては，罪名と科刑が分離し，妥当でないとの批判がある。
          3: 3．B説に対しては，重い犯罪の故意を有する乙について，重い犯罪の単独犯として構成した場合には，自らの行為と死亡結果の因果性を欠くことから，殺人既遂罪の成立を認めることが困難となるとの指摘がある。
          4: 4．B説とC説とで，甲に成立する罪名は異ならない。
          5: 5．C説からは，甲と乙に傷害致死罪の共同正犯が成立するにとどまるとの結論が導かれる。
          6:
          7:
          8:
      6:
        questions: 文書偽造の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，［No.11］，［No.12］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．偽造公文書行使罪の客体は，行使の目的で作成されたものでなければならない。
          2: 2．公務員である医師が，自己の勤務する市立病院の患者が裁判所に提出するための診断書に虚偽の病名を記載した場合，虚偽公文書作成罪が成立する。
          3: 3．行使の目的で，公務員の名義を冒用して公文書を作成したが，実際には当該公務員に当該文書の作成権限がなかった場合，当該文書が当該公務員の職務権限内で作成されたものと一般人が信じるに足る形式・外観を備えていれば，公文書偽造罪が成立する。
          4: 4．警察官から提示を求められたときに備え，偽造された自動車運転免許証を携帯して自動車を運転した場合，偽造公文書行使罪が成立する。
          5: 5．上司である公文書の作成権限のある公務員を補佐して公文書の起案を担当する公務員が，その地位を利用し，行使の目的で，その職務上起案を担当する公文書に内容虚偽の記載をした上，情を知らない上司に，当該文書の内容が真実であると誤信させ，これに署名押印させた場合，虚偽公文書作成罪は成立しない。
          6:
          7:
          8:
      7:
        questions: 次のアからオまでの各記述を判例の立場に従って検討した場合，誤っているものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．甲は，情を知らない法務局の担当登記官Aに対し，虚偽の申立てをして登記簿の磁気ディスクに不実の記録をさせた後，当該記録の内容を閲覧可能な状態にした。この場合，甲には，電磁的公正証書原本不実記録罪及び同供用罪が成立し，これらは牽連犯となる。
          i: イ．甲は，乙がA及びBをバットで順次殴打して両名を負傷させた際，これに先立ち，乙の意図を知りながら，乙にバットを手渡してそれらの犯行を幇助した。この場合，甲には，A及びBに対する2個の傷害罪の幇助犯が成立し，これらは観念的競合となる。
          u: ウ．甲は，A名義の預金口座から現金を引き出す目的で，AからA名義のキャッシュカードをだまし取るとともに，暗証番号を聞き出し，銀行の現金自動預払機で同キャッシュカードを使用して現金を引き出した。この場合，甲には，詐欺罪及び窃盗罪が成立し，これらは牽連犯となる。
          e: エ．甲は，強制性交の目的でA宅に侵入したが，Aが不在であったため目的を遂げられなかった。その後，甲は，居間に置かれていたA所有の腕時計を発見し，窃取しようと考えてこれを持ち去った。この場合，甲には，住居侵入罪及び窃盗罪が成立するが，これらは併合罪となる。
          o: オ．甲は，身の代金を得る目的でAを拐取した後，甲の自宅に監禁し，その間にAの実父Bに対し，電話で身の代金を要求した。この場合，甲には，身の代金目的拐取罪，監禁罪及び拐取者身の代金要求罪が成立し，身の代金目的拐取罪と拐取者身の代金要求罪が牽連犯となり，これらの各罪と監禁罪は併合罪となる。
        additional_answer:
          1: 1．アイ
          2: 2．アオ
          3: 3．イエ
          4: 4．ウエ
          5: 5．ウオ
          6:
          7:
          8:
      8:
        questions: 学生A，B及びCは，次の【会話】のとおり議論している。【会話】中の①から⑥までの（）内に後記【語句群】から適切な語句を入れた場合，正しいものの組合せは，後記1から5までのうちどれか。なお，①から⑥までの（）内にはそれぞれ異なる語句が入る。【会話】学生A．私は，公務も公務員としての個人の社会的活動であり，その性質に関わりなく業務妨害罪によって保護されるべきなので，（①）と考えます。学生B．私は，国家的法益と個人的法益では罪質が違うので，（②）と考えます。学生C．B君の見解では，（③）ような威力による非権力的公務に対する妨害のときに業務妨害罪が成立せず，非権力的公務の保護が不十分との批判がありますね。このような批判を踏まえて，私は，（④）と考えます。学生A．C君の見解によると，（⑤）ような暴行による非権力的公務に対する妨害については，いかなる犯罪が成立するのでしょうか。学生C．その場合には，業務妨害罪と公務執行妨害罪が成立すると考えます。学生B．C君の見解に対しては，（⑥）との批判がありますね。【語句群】a．全ての公務が業務妨害罪の対象となるb．強制力を行使する権力的公務以外の公務に限って業務妨害罪の対象となるc．公務は一切業務妨害罪の対象とならないd．威力による非権力的公務に対する妨害のときに処罰の間隙が生じてしまうe．逮捕行為や強制執行のように，自力で抵抗を排除し得る機能を付与されている場合まで威力に対する保護を認めることになるf．公務は公共の福祉を目的とするので，民間の業務より厚く保護されるべきであるg．公務に限って二重に保護する必要はないh．市役所の窓口業務を大声を上げて妨害したi．警察官による適法な捜索差押えの際，多数名で怒号しながら入口を塞いで警察官が捜索場所に立ち入るのを妨害したj．公立学校の入学試験監督員である教員を拳で殴って試験会場に入るのを阻止した
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②c③j
          2: 2．①a④b⑥e
          3: 3．②c③h④a
          4: 4．③h⑤i⑥g
          5: 5．④b⑤j⑥g
          6:
          7:
          8:
      9:
        questions: 次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．甲は，勤務先の事務室で1人で残業をしていたところ，使用中の電気ストーブから周囲の可燃物に誤って引火させた。甲は，その時点での消火作業は容易であったにもかかわらず，同室を含む勤務先建物が焼損することを認容して，消火作業をすることなく，同室から立ち去り，その結果，同建物が全焼した。その行為当時，同建物の他の部屋では甲の同僚が仮眠中であり，甲もそのことを認識していた。この場合，甲に既発の火力を利用する意思がなければ，現住建造物等放火罪は成立しない。［No.15］
          i: イ．甲は，Vと2人きりのホテル客室で，その同意の下，Vに対し，覚醒剤を注射したところ，Vが体調の異変を訴え，錯乱状態に陥ったため，救急医療を要請する必要があることを認識し，その要請をしていれば，Vの救命は確実であったにもかかわらず，その要請をすることなく，Vを放置したまま同室から立ち去り，その結果，Vが死亡したが，甲に殺意はなかった。この場合，甲がVを放置した行為とVの死亡との間の因果関係に欠けることはなく，甲には，保護責任者遺棄等致死罪が成立する。［No.16］
          u: ウ．甲は，深夜，自動車を運転中，路上で過失により通行人Vに同車を衝突させて，歩行不能の重傷を負わせた上，一旦Vを同車に乗せて，降雪中の周囲にひとけのない路上に移動し，Vに対し，医師を呼んでくるとうそを言って，Vを同車から降ろし，同車で同路上から立ち去ったが，甲に殺意はなかった。この場合，甲には，Vを保護する責任があり，保護責任者遺棄等罪が成立する。［No.17］
          e: エ．甲は，自己の口座に振込先を誤った振込入金があったことを知ったが，銀行窓口において，窓口係員に対し，その受取人として上記の誤った振込入金があった旨を告知せずに，その払戻しを請求し，事情を知らない同係員をして，払戻しに応じさせた。この場合，甲には，上記の誤った振込入金があったことを告知する義務はなく，詐欺罪は成立しない。［No.18］
          o: オ．甲は，面識のない他人のVと口論に及び，その首を絞めて窒息死させ，Vの死体をその場に放置して逃走した。この場合，甲には葬祭義務はなく，死体遺棄罪は成立しない。［No.19］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      10:
        questions: "）窃盗罪における不法領得の意思についての次の各【見解】に従って後記の各【事例】における甲の罪責を検討した場合，後記1から5までの各【記述】のうち，正しいものはどれか。なお，後記の各【事例】における甲の行為は，いずれも窃盗罪の客観的要件を全て満たすものとする。【見解】A．不法領得の意思として，権利者を排除して所有者として振る舞う意思及び何らかの用途に従って利用・処分する意思が必要である。B．不法領得の意思として，権利者を排除して所有者として振る舞う意思は必要であるが，何らかの用途に従って利用・処分する意思は不要である。C．不法領得の意思として，何らかの用途に従って利用・処分する意思は必要であるが，権利者を排除して所有者として振る舞う意思は不要である。D．不法領得の意思は不要である。【事例】Ⅰ．甲は，勤務先の会社の上司乙を困らせる目的で，乙が机の引き出し内に保管していた同社の銀行届出印をひそかに持ち出し，自宅の天井裏に隠匿した。Ⅱ．甲は，乙が不在であることを知り，一時的に借用して直ちに戻す意思で，乙方の玄関先に無施錠で駐輪されていた乙の自転車を無断で乗り出し，100メートル先の店まで移動して用事を済ませ，その乗り出しから5分後，同自転車を同玄関先に戻した。Ⅲ．甲は，X市議会議員選挙に際し，候補者乙の得票数を水増しする目的で，同市選挙管理委員会が保管していた投票用紙50枚を投票所から持ち出し，乙の支持者らに交付して乙に対する投票を依頼した。【記述】"
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．A及びBいずれの見解によっても，事例Ⅰでは窃盗罪が成立する。
          2: 2．A及びDいずれの見解によっても，事例Ⅱでは窃盗罪が成立する。
          3: 3．B及びCいずれの見解によっても，事例Ⅱでは窃盗罪が成立する。
          4: 4．B及びDいずれの見解によっても，事例Ⅲでは窃盗罪が成立する。
          5: 5．C及びDいずれの見解によっても，事例Ⅰでは窃盗罪が成立する。
          6:
          7:
          8:
      11:
        questions: "）刑法上の没収及び追徴に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。"
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．犯罪行為の用に供した物（刑法第19条第1項第2号）の没収は，物の危険性に着目した処分であるため，行為者が責任無能力を理由に無罪の言渡しをされたときであっても科すことができる。
          2: 2．犯罪行為の報酬として得た貴金属を売却して得た現金は，追徴ではなく，没収の対象となる。
          3: 3．強制性交の犯人が，被害者に犯行の様子を撮影録画したことを知らせて捜査機関に対し処罰を求めることを断念させる目的で，ひそかに撮影録画したデジタルビデオカセットは，犯罪行為の用に供した物ではないため，没収の対象とならない。
          4: 4．犯罪行為によって得た物(刑法第19条第1項第3号)は，犯罪により不当に得た利益を犯人から剥奪する必要があるため，任意的没収ではなく，必要的没収の対象となる。
          5: 5．没収の対象は，刑罰の一身専属性の見地から，犯人の所有物に限られる。
          6:
          7:
          8:
      12:
        questions: "）名誉毀損罪及び侮辱罪に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。"
        answer:
          a: ア．事実を摘示せずに公然と人を侮辱することを教唆した者に，侮辱教唆罪が成立することはない。
          i: イ．弁護人が被告人の利益を擁護するためにした弁護活動であれば，それが名誉毀損罪の構成要件に該当する行為であっても，違法性が阻却されるため，名誉毀損罪が成立することはない。
          u: ウ．人の社会的評価を害するに足りる事実を公然と摘示したとしても，その人の社会的評価が現実に害されていない場合，刑法第230条第1項にいう「人の名誉を毀損した」とはいえないため，名誉毀損罪は成立しない。
          e: エ．私人の私生活の行状であっても，その携わる社会的活動の性質及びこれを通じて社会に及ぼす影響力の程度等によっては，刑法第230条の2第1項にいう「公共の利害に関する事実」に当たる場合がある。
          o: オ．インターネットを利用して公然と虚偽の事実を摘示し，人の名誉を毀損した場合，他の表現手段を利用する場合と異なり，インターネットの個人利用者に要求される水準を満たす調査によって摘示した事実が真実か否かを確かめることなく発信したときに限り名誉毀損罪が成立する。
        additional_answer:
          1: 1．アエ
          2: 2．アオ
          3: 3．イウ
          4: 4．イオ
          5: 5．ウエ
          6:
          7:
          8:
      13:
        questions: "）次の【事例】に関する後記アからオまでの各【記述】のうち，甲に殺人未遂罪の成立を認めるための論拠として適切なものの組合せは，後記1から5までのうちどれか。【事例】甲は，知人の乙に，毒物を混入したワイン（以下「本件ワイン」という。）を送り付ければ，乙がそれを自ら飲んで死亡すると考えた。甲は，某日，本件ワインを宅配業者の事務所に持ち込み，3日後の配達指定をして，乙宅への配達を申し込んだ。しかし，本件ワインは，申込み当日，同事務所での保管中に瓶が破損して廃棄処分となったため，乙宅に配達されることはなかった。【記述】"
        answer:
          a: ア．間接正犯の実行の着手については，被利用者の行為を基準として実行の着手を判断すべきところ，本件では，それと同様の考え方が妥当する。
          i: イ．結果発生の一定の蓋然性が生じれば，未遂犯の成立を認めることができるところ，我が国の一般的な宅配業務の実情を前提とした場合，本件ワインの配達を申し込んだ時点で乙宅に到着することはほぼ確実といえる。
          u: ウ．実行の着手は，行為者が，その犯行計画上，構成要件実現のためになすべきことを行った時点で認めることができる。
          e: エ．甲が，宅配業者に依頼せず，自ら乙宅に本件ワインを届けようとした場合には，乙宅に本件ワインを届けるまでは殺人未遂罪が成立しないこととの均衡を考慮する必要がある。
          o: オ．既遂結果発生の時間的に切迫した危険を内容とする未遂結果は，刑法第43条の書かれざる構成要件要素である。
        additional_answer:
          1: 1．アエ
          2: 2．アオ
          3: 3．イウ
          4: 4．イエ
          5: 5．ウオ
          6:
          7:
          8:
      14:
        questions: "）証拠隠滅等罪（刑法第104条）に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの個数を後記1から5までの中から選びなさい。"
        answer:
          a: ア．自己の犯罪行為に関する証拠の隠滅を他人に教唆し実行させた場合，証拠隠滅罪の教唆犯は成立しない。
          i: イ．自己の配偶者の犯罪行為に関する証拠を隠滅した場合，証拠隠滅罪が成立する。
          u: ウ．貸金返還請求訴訟における被告が，同訴訟の証拠である消費貸借契約書の原本を焼却した場合，証拠隠滅罪は成立しない。
          e: エ．被告人の友人が，被告人の犯罪行為に関する偽証を証人に教唆し実行させた場合，証拠偽造罪の教唆犯は成立しない。
          o: オ．いまだ捜査が開始されていない段階で，他人の犯罪行為に関する証拠を隠滅した場合，証拠隠滅罪が成立する。
        additional_answer:
          1: 1．1個
          2: 2．2個
          3: 3．3個
          4: 4．4個
          5: 5．5個
          6:
          7:
          8:
      15:
        questions: "）刑法第65条について，学生A，B及びCが次の【会話】のとおり議論している。【会話】中の①から⑪までの（）内に後記【語句群】から適切な語句を入れた場合，正しいものの組合せは，後記1から5までのうちどれか。なお，①から⑪までの（）内にはそれぞれ異なる語句が入る。【会話】学生A．私は，「違法の連帯性，責任の個別性」の原則を強調する立場から，（①）と考えます。学生B．A君の見解には，（②）との批判がありますね。私は，刑法第65条第1項が「共犯とする」，同条第2項が「通常の刑を科する」とそれぞれ規定していることに着目し，（③）と考えます。学生C．ただ，B君の見解には，（④）との批判がありますね。刑法第65条第1項が身分によって構成すべき犯罪を問題とし，同条第2項が身分によって刑の軽重がある犯罪を問題としていることに着目し，（⑤）と考えるべきではないかな。学生B．でも，C君の見解にも，（⑥）との批判がありますね。ところで，C君の見解だと，甲が知人の乙を唆して乙の嬰児の生存に必要な食事をさせなかった事例では，甲の罪責はどうなりますか。学生C．私は，刑法第217条（遺棄）と同法第218条（保護責任者遺棄等）の「遺棄」とは，行為者と要扶助者との間の場所的離隔を生じさせることをいい，同法第217条では作為による遺棄のみが処罰されていると考え，また，同法第218条の「必要な保護をしなかった」とは，場所的離隔を生じさせることなく要扶助者を不保護状態に置くことをいうと考えます。そうすると，同条の罪のうち，作為による保護責任者遺棄罪は（⑦）犯，保護責任者不保護罪は（⑧）犯になるため，乙とその嬰児との間に場所的離隔が生じていない本件では，甲には（⑨）と考えます。学生A．しかし，C君の見解では，甲が乙を唆して乙の嬰児を山に捨てさせた事例では，甲に（⑩）ため，不均衡な結論になるのではないかな。私は，保護責任者という身分は，必要な保護をしなかったことの違法性を基礎付け，遺棄の違法性を加重するため，（⑪）と考えます。したがって，私の見解からは，いずれの事例でも，甲には（⑨）と考えます。【語句群】a．刑法第65条第1項は真正身分犯の成立及び科刑についての規定であり，同条第2項は不真正身分犯の成立及び科刑についての規定であるb．刑法第65条第1項は身分が違法性に関係する場合についての規定であり，同条第2項は身分が責任に関係する場合についての規定であるc．刑法第65条第1項は真正身分犯・不真正身分犯を通じて共犯の成立についての規定であり，同条第2項は不真正身分犯の科刑についての規定であるd．犯罪の成立と科刑が分離されることになるe．真正身分犯が身分を連帯的に作用させ，不真正身分犯が身分を個別的に作用させることの実質的根拠が明らかでないf．身分が違法性に関係する場合と責任に関係する場合を区別することは困難g．責任身分h．違法身分i．真正身分j．不真正身分k．刑法第218条の罪の教唆犯が成立するl．刑法第217条の罪の教唆犯が成立する"
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①b⑤a⑨k
          2: 2．②d⑥e⑪h
          3: 3．②f⑦i⑧j
          4: 4．③c④d⑪g
          5: 5．③c⑥f⑩l
          6:
          7:
          8:
      16:
        questions: "）放火の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，［No.26］，［No.27］順不同）"
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，Aが所有する自動二輪車に放火するため，これに使用するガソリンとライターを所持して同自動二輪車に近づいたが，甲に不審を抱いた警察官から職務質問を受け，放火するに至らなかった。この場合，甲には，放火予備罪は成立しない。
          2: 2．甲は，自己が所有する無人の木造倉庫に放火してこれを焼損し，よって公共の危険を生じさせ，その結果，Aが居住する木造家屋に延焼させたが，その延焼についての認識はなかった。この場合，甲には，延焼罪は成立しない。
          3: 3．甲は，自己が所有する自動二輪車に放火してこれを焼損し，よって公共の危険を生じさせたが，その公共の危険が生じることについての認識はなかった。この場合，甲には，建造物等以外放火罪は成立しない。
          4: 4．甲は，隣人Aが居住する木造家屋を焼損しようと考え，同家屋から1メートル離れた位置にある自己が所有する無人の木造倉庫に放火してこれを焼損したが，同家屋に延焼する危険を生じさせるにとどまった。この場合，甲には，現住建造物等放火未遂罪は成立しない。
          5: 5．甲は，Aが1人で居住しており，他に誰もいなかった木造家屋内でAを殺害し，その直後，同家屋に放火してこれを焼損した。この場合，甲には，現住建造物等放火罪は成立しない。
          6:
          7:
          8:
      17:
        questions: "）正当防衛（刑法第36条第1項）に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，［No.28］，［No.29］順不同）"
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．刑法第36条第1項における「急迫」というには，法益の侵害が現に存在していることを要する。
          2: 2．刑法第36条第1項における「やむを得ずにした行為」というには，反撃行為が権利を防衛する手段として必要最小限度のものであること，すなわち侵害に対する防衛手段として相当性を有するものであることを要する。
          3: 3．急迫不正の侵害がないのにあると誤信して，防衛の意思で反撃行為を行った場合でも，正当防衛が成立し得る。
          4: 4．刑法第36条第1項にいう「権利」は，個人的法益に限られ，国家的・社会的法益は，これに含まれない。
          5: 5．刑法第36条第1項における「不正の侵害」というには，可罰的な行為であることを要しない。
          6:
          7:
          8:
      18:
        questions: "）強盗の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。"
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，銭湯の脱衣場で窃盗をしようと考え，客の財布を手に取って在中する金額を確認中，その様子を目撃した乙から声を掛けられたため，逮捕を免れる目的で，乙に反抗を抑圧するに足りる程度の暴行を加えて加療約1か月間を要する傷害を負わせた。この場合，甲には，事後強盗罪及び強盗致傷罪が成立し，両罪は観念的競合となる。
          2: 2．甲は，電車内で寝ていた乙の財布を盗んで電車を降りたが，乙が目を覚まして追い掛けてきたため，逮捕を免れる目的で，乙に暴行を加えたところ，乙が転倒して重傷を負い，反抗が抑圧された状態に至った。この場合，甲の暴行の程度を問わず，甲には，強盗致傷罪が成立する。
          3: 3．甲は，留守宅に侵入して窃盗をしようと考え，金品を物色中に家人が帰ってきたら同人に反抗を抑圧するに足りる程度の脅迫を加えて逃げる意図でサバイバルナイフを携帯し，住宅街を徘徊して侵入に適した留守宅を探したが，これを発見できず，侵入を断念した。この場合，甲には，強盗予備罪が成立する。
          4: 4．甲は，窃盗の目的で乙宅に侵入し，金品を物色中，乙に発見されたため，この機会に乙に暴行を加えて金品を奪おうと考え，乙に反抗を抑圧するに足りる程度の暴行を加え，金品を奪った。この場合，甲には，事後強盗罪が成立する。
          5: 5．甲は，乙宅に侵入して財布を盗んだ後，誰にも発見されずに1キロメートル離れた公園へ移動して財布内の現金を確認した。しかし，甲は，その金額に満足せず再度乙宅で窃盗をしようと考え，乙宅を出た30分後に乙宅に戻り，その玄関扉を開けようとしたところ，帰宅していた乙に発見されたため，逮捕を免れる目的で，乙に反抗を抑圧するに足りる程度の暴行を加えた。この場合，甲には，事後強盗罪が成立する。
          6:
          7:
          8:
      19:
        questions: "）緊急避難に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。"
        answer:
          a: ア．豪雨により稲苗が水に沈む危険が生じていたことから，排水のため他人の所有する下流の板堰を損壊した場合，「現在の危難」があるとは認められないので，緊急避難は成立しない。
          i: イ．警察官の適法な逮捕行為に対し，逮捕を免れるためには他に方法がなかったので，第三者を突き飛ばして逃走し，よって同人に傷害を負わせた場合，緊急避難が成立し得る。
          u: ウ．頭に拳銃を突き付けられて，覚醒剤の自己使用を強要され，これを拒むことができず，自己に覚醒剤を注射して使用した場合，犯罪行為の強要の手段は「現在の危難」に当たらないので，緊急避難は成立しない。
          e: エ．吊橋が腐朽し，通行の際の揺れにより通行者の生命，身体等に危険が生じていたため，ダイナマイトを使用して同吊橋を爆破したが，通行制限の強化等適当な手段，方法を講ずる余地があった場合，同爆破行為は，「やむを得ずにした行為」とは認められないので，緊急避難は成立しない。
          o: オ．甲が飼い犬A（時価30万円相当）を連れて山道を散歩中，乙が設置していた害獣駆除用の罠（時価3万円相当）にAがかかり，その生命に危険が生じ，Aを保護するためには他に方法がなかったので，その罠を損壊した場合，緊急避難が成立する（甲及び乙いずれにも過失がなかったものとする。）。
        additional_answer:
          1: 1．アイ
          2: 2．アエ
          3: 3．イウ
          4: 4．ウオ
          5: 5．エオ
          6:
          7:
          8:
      20:
        questions: "）次の【事例】に関する後記アからオまでの各【記述】を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。【事例】暴力団A組の組員甲は，クラブで飲酒していた際，たまたま入店してきた旧知の暴力団B組の組員乙に因縁を付けられて口論になり，乙に拳で殴りかかった。乙は，これを避けた上，更に殴りかかろうとしてきた甲の胸部を拳で数回強打した。その数分後，B組の組員丙は，乙と待ち合わせをしていた上記クラブに到着し，その直後に甲の態度に激高し，いきなり甲の胸部を拳で数回強打した。甲は，全治約1か月間を要する肋骨骨折の傷害を負ったが，同傷害が乙と丙のいずれの暴行によって生じたのかは不明であった。甲は，一旦帰宅したものの怒りが収まらず，何か嫌がらせをしてやろうと考え，金属バットを持ち，覆面で顔を隠してB組事務所に行き，その玄関ドアを同バットでたたいて凹損させた。その直後，甲は，A組事務所に行き，A組の組員丁に対し，B組組員から殴られた腹いせにB組事務所の玄関ドアを凹損させたことを話した。丁は，B組との関係悪化を避けるとともに，甲の刑事責任を免れさせるため，甲との間で，犯行時間帯に甲がA組事務所にいたことにする旨の口裏合わせをした。また，丁は，B組組員複数名による襲撃を受ける可能性もあると考え，万が一に備えて，着衣のポケットに護身用として果物ナイフを入れた。他方，乙及び丙は，上記ドアが凹損させられたとの連絡を受け，甲の仕業だろうと考え，A組事務所へ向かった。乙は，応対に出た丁に対し，「甲を出せ。」と言った。丁は，「何の話だ。」と応じたが，乙は，その態度に憤激し，「しらばっくれるな。」と言い，持っていた拳銃を取り出して丁に突き付けた。丁は，自己の身を守るため，上記ナイフで乙の腹部を1回突き刺し，乙に全治約1か月間を要する腹部刺創の傷害を負わせた。丁は，駆けつけた警察官に逮捕され，その後，逃走していた甲も上記ドアを凹損させた事実で逮捕された。丁は，甲の身柄拘束中，甲の犯行に関する参考人として取調べを受けた際，上記口裏合わせに従い，上記ドアが凹損させられた時間帯に甲がA組事務所にいた旨のうその供述をした。【記述】"
        answer:
          a: ア．乙が甲の胸部を拳で強打した行為については，甲からの侵害が，乙が甲に因縁を付けたことにより招かれたものである以上，正当防衛又は過剰防衛が成立することはない。［No.32］
          i: イ．乙は，甲の肋骨骨折について，丙の行為のみにより生じた可能性がある以上，丙との間で共謀が成立していない限り，傷害罪の刑事責任を負わない。［No.33］
          u: ウ．甲がB組事務所の玄関ドアを凹損させた行為については，同ドアが工具を使用すれば容易に取り外せる構造であった場合，建造物損壊罪は成立しない。［No.34］
          e: エ．丁が果物ナイフで乙の腹部を突き刺した行為については，B組組員から襲撃を受けることを予期し，凶器ともいえるナイフを準備している以上，その予期の程度にかかわらず，侵害の急迫性を欠くものといえ，正当防衛又は過剰防衛は成立しない。［No.35］
          o: オ．丁が，甲の犯行に関する参考人として取調べを受けた際，B組事務所の玄関ドアが凹損させられた時間帯に甲がA組事務所にいた旨のうその供述をした行為については，犯人隠避罪が成立する。［No.36］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
