---
ja:
  keiho:
    2017:
      1:
        questions: 次の【見解】に関する後記1から5までの各【記述】のうち，誤っているものはどれか。【見解】間接正犯については，被利用者の行為時に実行の着手を認めるべきである。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．【見解】は，実行行為時と実行の着手時期が一致することを要しないとする考え方と矛盾しない。
          2: 2．【見解】に対しては，利用者にとって偶然の事情で実行の着手時期を決することになり不合理であると批判できる。
          3: 3．【見解】は，離隔犯において到達時に実行の着手を認める考え方と矛盾しない。
          4: 4．【見解】に対しては，責任無能力者を利用する場合には，責任無能力者に規範意識の障害がないというだけで，直ちに結果発生の切迫した危険があるとはいえないと批判できる。
          5: 5．【見解】は，自然的に観察して結果発生に向けた直接の原因となる行為を重視する考え方と矛盾しない。
          6:
          7:
          8:
      2:
        questions: 略取，誘拐及び人身売買の罪に関する次のアからオまでの各記述を判例の立場に従って検討した場合，誤っているものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．営利の目的で未成年者を買い受けた場合，未成年者買受け罪のみが成立する。
          i: イ．身の代金目的誘拐罪は，近親者その他誘拐された者の安否を憂慮する者の憂慮に乗じてその財物を交付させる目的を主観的要素とする目的犯である。
          u: ウ．身の代金目的で成年者を略取し，公訴が提起される前に同成年者を安全な場所に解放すれば，身の代金目的略取罪の刑が必要的に減軽される。
          e: エ．未成年者誘拐罪は親告罪である。
          o: オ．親権者は，未成年者誘拐罪の主体とはならない。
        additional_answer:
          1: 1．アウ
          2: 2．アオ
          3: 3．イウ
          4: 4．イエ
          5: 5．エオ
          6:
          7:
          8:
      3:
        questions: 次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．甲は，乙を殺害する目的で，乙を含む複数の者の飲用に供されているペットボトル内のお茶に致死量の劇薬を投入した。その結果，そのお茶を飲用した複数の者全員が死亡した。この場合，甲には，前記お茶を飲用して死亡した者の数に応じた殺人罪の故意が認められる。
          i: イ．覚せい剤を含有する粉末を所持していた甲は，同粉末が身体に有害で違法な薬物であることは認識していたが，覚せい剤や麻薬ではないと認識していた。この場合，甲には覚せい剤取締法違反（覚せい剤所持）の罪の故意が認められる。
          u: ウ．甲は，客観的にはわいせつな文書を，その意味内容は理解しつつも，刑法上のわいせつな文書に該当しないと考え，多数の者に販売した。この場合，甲にわいせつ物頒布罪の故意は認められない。
          e: エ．甲は，乙宅前路上に置かれていた自転車を，乙の所有物と認識して持ち去ったが，実際には同自転車は無主物だった。この場合，甲には遺失物横領罪が成立する。
          o: オ．甲は，第三者が起こした交通事故により瀕死の重傷を負い路上に倒れていた乙を，既に死亡していると思って山中に遺棄した。この場合，甲に死体遺棄罪は成立しない。
        additional_answer:
          1: 1．アエ
          2: 2．アオ
          3: 3．イウ
          4: 4．イオ
          5: 5．ウエ
          6:
          7:
          8:
      4:
        questions: 各種偽造の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，[№4，[№5］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，他人の自動車運転免許証に甲の写真を貼り付けた偽造自動車運転免許証を入手し，これを携帯して自動車を運転中に検問で停止を求められ，情を知らない警察官に同免許証を真正に成立したものとして提示した。提示した時には同免許証に表示されている有効期間が経過していたとしても，甲には偽造公文書行使罪が成立する。
          2: 2．公務員でない甲は，情を知らない公務員に対し虚偽の申立てをして登記簿に不実の記載をさせ，その登記簿謄本の交付を受けた。甲には虚偽公文書作成罪の間接正犯が成立する。
          3: 3．甲は，情を知らずに釣銭として偽造通貨を受け取ったところ，その後，それが偽造通貨であることに気付いたが，行使の目的でそのまま所持した。甲には偽造通貨収得罪が成立する。
          4: 4．甲は，行使の目的で，他人が振り出した額面10万円の小切手の金額欄に「0」を加え，額面100万円の小切手に改ざんした。甲には有価証券変造罪が成立する。
          5: 5．弁護士資格のない甲は，X弁護士会に実在する自己と同姓同名の弁護士を装い，これを信じた乙から依頼を受けて弁護士としての業務を行った後，乙から報酬を得るために，「X弁護士会所属弁護士甲」名義の弁護士報酬金請求書を作成した。甲には私文書偽造罪が成立しない。
          6:
          7:
          8:
      5:
        questions: 正当防衛及び緊急避難に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，[№6］，[№7］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．正当防衛は，法益の侵害が現に存在している場合のほか，法益の侵害が間近に差し迫っている場合にも成立する余地があるが，緊急避難は，危難が間近に差し迫っている場合に成立する余地はない。
          2: 2．正当防衛が成立するためには，防衛行為が侵害に対する防衛手段として相当性を有するものであることを要するから，防衛行為によって生じた害が避けようとした害の程度を超えた場合に正当防衛が成立する余地はない。
          3: 3．正当防衛が成立する行為を避けるために相手方又は第三者の法益を侵害した場合，緊急避難が成立する余地があるが，正当防衛が成立する余地はない。
          4: 4．過剰避難について，その刑を減軽も免除もしないことはできるが，過剰防衛については，その刑を減軽又は免除しなければならない。
          5: 5．自然現象によって生じた法益侵害を避けるために第三者の法益を侵害した場合，緊急避難が成立する余地があるが，正当防衛が成立する余地はない。
          6:
          7:
          8:
      6:
        questions: わいせつ物頒布等の罪に関する次のアからオまでの各記述を判例の立場に従って検討し，甲に（）内の罪が成立しないものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．インターネットを介した書籍販売業を営む甲は，日本語で書かれたわいせつな文書である小説を，その購入を申し込んできた日本国内在住の多数の外国人に販売したところ，いずれの外国人も日本語の読解能力に乏しく，同小説の内容を理解できなかった。（わいせつ物頒布罪）
          i: イ．甲は，インターネットを介して多数の希望者を募った上，その希望者らに無料で交付する目的で，わいせつな映像を記録したDVDを所持した。（わいせつ物有償頒布目的所持罪）
          u: ウ．甲は，わいせつな映像を記録したDVDの販売業者に対してそのDVDの購入を申し込み，これを購入した。（わいせつ物頒布罪の教唆犯）
          e: エ．DVDのレンタル業を営む甲は，わいせつな映像を記録したDVDを，多数の顧客へ有償で貸し出した。（わいせつ物頒布罪）
          o: オ．甲がインターネットを介したわいせつな映像の販売業を営み始めたところ，その購入を申し込んできた顧客は1名だけであったが，甲は，その者に対して，電子メールに同映像のデータを添付して送信した。（わいせつ物頒布罪）
        additional_answer:
          1: 1．アエ
          2: 2．アオ
          3: 3．イウ
          4: 4．イエ
          5: 5．ウオ
          6:
          7:
          8:
      7:
        questions: 次の【記述】中の①から④までの（）内から適切な語句を選んだ場合，その組合せとして正しいものは，後記1から5までのうちどれか。【記述】被害者の同意が問題となる場合としては，一般に以下のような分類がなされている。第1は，被害者の意思に反することが構成要件要素になっている場合であり，この類型においては，被害者の同意は構成要件該当性を阻却する。窃盗罪は，この類型に①（a．入る・b．入らない）。第2は，被害者の同意の有無が犯罪の成立に影響を及ぼさない場合である。13歳未満の者に対するわいせつ行為は，この類型に②（c．入る・d．入らない）。第3は，被害者の同意がある場合とない場合が分けて規定され，被害者の同意があると軽い方の罪が成立する場合である。業務上堕胎罪は，この類型に③（e．入る・f．入らない）。第4は，被害者の同意が行為の違法性を阻却する場合である。住居侵入罪の「侵入」を住居権者・管理権者の意思に反する立入りと解した場合，同罪は，この類型に④（g．入る・h．入らない）。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②c③e④h
          2: 2．①a②c③f④h
          3: 3．①a②d③f④g
          4: 4．①b②c③e④h
          5: 5．①b②d③f④g
          6:
          7:
          8:
      8:
        questions: 不法領得の意思に関する次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからオの順に[№10］から[№）4］
        answer:
          a: ア．甲は，町議会議員選挙に際し，特定の候補者を当選させるため，後日その候補者の氏名を記載して投票の中に混入することにより同候補者の得票数を増加させる目的で，投票所管理者乙の保管する同選挙の投票用紙を密かに持ち出した。この場合，甲に不法領得の意思は認められず，窃盗罪は成立しない。[№10］
          i: イ．A市建設部長である甲は，不正工事の発覚を恐れ自宅に隠匿する目的で，自己が業務上保管している公文書である市立小学校の設計書を市役所外に持ち出した。この場合，甲に不法領得の意思は認められず，業務上横領罪は成立しない。[№11］
          u: ウ．甲は，自宅で分解して売却できそうな部品を中古部品屋に売却する目的で，知人乙所有の自動車を乙に無断で運転してその場から走り去った。この場合，甲に不法領得の意思は認められず，窃盗罪は成立しない。[№12］
          e: エ．新聞購読料の集金業務に従事する甲は，購読料として集金した現金を遊興のため全額費消して横領した後，その発覚を免れる目的で，新たに購読料として集金した現金を穴埋めに充てた。この場合，穴埋めに充てた現金について，甲に不法領得の意思は認められず，業務上横領罪は成立しない。[№13］
          o: オ．甲は，乙宛てに送達されてきた支払督促状を乙に成り済まして受領して廃棄することにより，送達が適式になされたものとして支払督促の効力を生じさせ，乙所有の財産を不正に差し押さえようと考え，郵便配達員丙を欺いて同督促状の交付を受けて廃棄した。この場合，甲に不法領得の意思は認められず，詐欺罪は成立しない。[№14］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      9:
        questions: 没収と追徴に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。］
        answer:
          a: ア．主物を没収するときは，その従物も没収できる。
          i: イ．判決により没収の言渡しをするためには，対象物が判決時に裁判所により押収されている必要がある。
          u: ウ．被害者宅に侵入して行われた窃盗事犯において，被害者宅への侵入に際して道具として使用された鉄棒は，住居侵入罪について公訴提起されていなければ没収できない。
          e: エ．窃盗によって取得された盗品は，取得物件であるが，没収できない場合がある。
          o: オ．収賄罪において，収受した賄賂が没収不能となった時点で，収受時と比較してその価額が減じていた場合には，没収不能時の価額を追徴することになる。
        additional_answer:
          1: 1．アイ
          2: 2．アエ
          3: 3．イウ
          4: 4．ウオ
          5: 5．エオ
          6:
          7:
          8:
      10:
        questions: 信用及び業務に対する罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．威力業務妨害罪における「威力」は，暴行又は脅迫を用いることを要し，騒音喧騒により人の意思を制圧して業務を妨害した場合，同罪は成立しない。
          2: 2．偽計業務妨害罪における「偽計」は，直接人に向けられていなくてもよい。
          3: 3．信用毀損罪における「信用」は，人の支払能力又は支払意思に対する社会的な信頼に限定されず，経済的側面とは関係のない社会的な信頼を害した場合も，同罪が成立する。
          4: 4．業務妨害罪における「業務」は，社会生活上又は個人生活上の地位に基づき反復継続して従事する事務であるから，学生の学習活動を妨害した場合も，同罪が成立する。
          5: 5．信用毀損罪は危険犯であるが，業務妨害罪は侵害犯である。
          6:
          7:
          8:
      11:
        questions: 次の【事例】に関する後記アからエまでの各【記述】を判例の立場に従って検討し，誤っているものを全て選んだ場合の組合せは，後記1から5までのうちどれか。【事例】土木作業員甲及び乙は，現場監督者丙の監督の下で，X川に架かる鉄橋の橋脚を特殊なA鋼材を用いて補強する工事に従事していたが，作業に手間取り，工期が迫ってきたことから，甲及び乙の2人で相談した上で，より短期間で作業を終えることができる強度の弱いB鋼材を用いた補強工事を共同して行った。その結果，工期内に工事を終えることはできたものの，その後発生した豪雨の際，A鋼材ではなくB鋼材を用いたことによる強度不足のために前記橋脚が崩落し，たまたま前記鉄橋上を走行していたV1運転のトラックがX川に転落し，V1が死亡した。なお，甲及び乙は同等の立場にあり，甲及び乙のいずれについても，B鋼材を工事に用いた場合に強度不足のために前記橋脚が崩落することを予見していなかったものの，その予見可能性があったものとする。【記述】
        answer:
          a: ア．甲及び乙には，強度の弱いB鋼材で補強工事を行うことの意思連絡はあるが，不注意の共同はあり得ないから，甲及び乙に業務上過失致死罪の共同正犯が成立する余地はない。
          i: イ．丙は，甲及び乙が強度の弱いB鋼材で補強工事を行っていることを認識していたが，工期が迫っていたことから，これを黙認したという場合，直接行為者である甲及び乙に過失が認められたとしても，更に丙に過失が認められる余地がある。
          u: ウ．仮に，甲及び乙において，V1が死亡するに至る実際の因果経過を具体的に予見することが不可能であった場合，甲及び乙には業務上過失致死罪は成立しない。
          e: エ．仮に，V1運転のトラックの荷台に，V1に無断でV2が乗り込んでおり，同トラックがX川に転落したことによって，V1及びV2の両名が死亡した場合，甲及び乙にはV2に対する業務上過失致死罪は成立しない。
          o:
        additional_answer:
          1: 1．アイウ
          2: 2．アウエ
          3: 3．アエ
          4: 4．イウ
          5: 5．ウエ
          6:
          7:
          8:
      12:
        questions: 次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。］
        answer:
          a: ア．甲は，自転車Aが，乙が自ら窃取した自転車Bからサドルを取り外し，乙所有の別の自転車本体に容易に着脱可能な状態で取り付けて完成させたものであると知りつつ，乙から自転車Aを購入した。甲には盗品等有償譲受け罪が成立する。[№18］
          i: イ．甲は，盗品であると知りつつ，窃盗犯人乙から依頼を受けて保管していた宝石を乙に返却した後，改めて乙から依頼を受け，預かった同宝石を事情を知らない丙に売却した。甲には盗品等有償処分あっせん罪のみが成立する。[№19］
          u: ウ．甲は，刑法第41条の刑事未成年である乙が窃取した物を，盗品であると知りつつ，乙から無償で譲り受けた。甲には盗品等無償譲受け罪は成立しない。[№20］
          e: エ．甲は，親族関係にない窃盗犯人乙から盗品の保管を依頼された。甲は，同盗品が，甲の実父丙の自宅から窃取された丙所有の物であると知りつつ，乙からの依頼を受け入れて，同盗品を保管した。甲は盗品等保管罪の刑が免除される。[№21］
          o: オ．甲は，妻乙が，親族関係にない窃盗犯人丙から盗品であると知りつつ購入した物を，乙から依頼を受け，盗品であると知りつつ，乙の指定した場所まで運んだ。甲は盗品等運搬罪の刑が免除される。[№22］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      13:
        questions: 責任能力に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，[№2，[№24］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．13歳の少年であっても，事物の理非善悪を弁識する能力及びその弁識に従って行動する能力が備わっていれば，責任能力が認められることがある。
          2: 2．責任能力の有無は法律判断であり，専ら裁判所の評価に委ねられるべきであるため，その前提となる生物学的・心理学的要素についても，最終的には裁判所により判断される。
          3: 3．相手の頭部を殴打する暴行を加えた時点で行為者に責任能力が存在したとしても，その暴行により相手が死亡した時点で行為者に責任能力が存在しなければ，死亡の結果について行為者に刑事責任を問うことはできない。
          4: 4．犯行当時，行為者に重度の精神疾患があれば，そのことだけで直ちに心神喪失の状態にあったと判断されることになる。
          5: 5．飲酒の際，飲酒後に酒酔い運転をする意思が認められる場合には，実際に酒酔い運転をした時に酩酊による心神耗弱の状態にあったとしても，行為者に完全責任能力が認められることがある。
          6:
          7:
          8:
      14:
        questions: 犯人蔵匿及び証拠隠滅の罪に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。］
        answer:
          a: ア．犯人の親族が当該犯人の利益のために犯人蔵匿罪を犯したときは，当該親族に対する刑は減軽しなければならない。
          i: イ．犯人隠避罪の「罰金以上の刑に当たる罪を犯した者」には，犯人として既に逮捕・勾留されている者は含まれない。
          u: ウ．証拠隠滅罪の「他人の刑事事件」は，犯人蔵匿罪と異なり，罰金以上の刑に当たる罪に限られない。
          e: エ．証人等威迫罪の「威迫」は，相手と面会して直接なされる場合に限られ，文書を送付して相手にその内容を了知させる方法によりなされる場合を含まない。
          o: オ．犯人が自己の刑事事件の裁判に必要な知識を有する証人を威迫した場合，証人等威迫罪が成立する。
        additional_answer:
          1: 1．アウ
          2: 2．アエ
          3: 3．イエ
          4: 4．イオ
          5: 5．ウオ
          6:
          7:
          8:
      15:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲が乙に対し，深夜の公園で待ち伏せしてAから金品を喝取するように教唆したところ，乙は，その旨決意し，深夜の公園でAを待ち伏せしたが，偶然通り掛かったBをAと誤認してBから金品を喝取した。乙は，人違いに気付き，引き続きAを待ち伏せして，通り掛かったAから金品を喝取しようとしてAを脅迫したが，Aに逃げられてしまい金品を喝取することができなかった。甲にはAに対する恐喝未遂罪の教唆犯のみが成立する。
          2: 2．甲が乙に対し，Aをナイフで脅してAから金品を強取するように教唆したところ，乙は，その旨決意し，Aをナイフで脅したが，その最中に殺意を抱き，Aの腹部をナイフで刺してAに傷害を負わせ，Aから金品を強取したものの，Aを殺害するには至らなかった。甲には強盗罪の教唆犯が成立するにとどまる。
          3: 3．甲が乙に対し，留守宅であるA方に侵入して金品を窃取するように教唆したところ，乙は，その旨決意したが，B方をA方と誤認してB方に侵入し，その場にいたBから金品を強取した。甲にはB方への住居侵入罪及びBに対する窃盗罪の教唆犯が成立する。
          4: 4．甲が乙に対し，現住建造物であるA家屋に放火するように教唆したところ，乙は，その旨決意し，A家屋に延焼させる目的で，A家屋に隣接した現住建造物であるB家屋に放火したが，B家屋のみを焼損し，A家屋には燃え移らなかった。甲にはA家屋に対する現住建造物等放火未遂罪の教唆犯のみが成立する。
          5: 5．甲は，土建業者AがB市発注予定の土木工事を請け負うためB市役所土木係員乙に現金を供与しようと考えていることを知り，乙に対し，Aに工事予定価格を教える見返りとしてAから現金を受け取り，Aに工事予定価格を教えるように教唆したところ，乙は，その旨決意し，Aとの間で，Aに工事予定価格を教える旨約束して，Aから現金100万円を受け取ったが，その後，工事予定価格を教えなかった。甲には加重収賄罪の教唆犯が成立する。
          6:
          7:
          8:
      16:
        questions: 次の【見解】に関する後記アからオまでの各【記述】のうち，正しいものの組合せは，後記1から5までのうちどれか。【見解】横領罪の目的物は，犯人が占有する他人の物であり，物の給付者において民法上その返還を請求できるものであることを要しないので，不法な目的で金銭を委託した場合，委託者に返還請求権が認められなくても，受託者がこれを領得する行為には，横領罪が成立する。【記述】
        answer:
          a: ア．この【見解】に対しては，民法第708条にいう「給付」に「委託」は含まれないとする立場を前提としなければならず，妥当でないとの批判ができる。
          i: イ．この【見解】は，使途を定めて委託された金銭の所有権は受託者に移転しないとする立場と明らかに矛盾するものである。
          u: ウ．この【見解】に対しては，受託者が民法第708条に基づいて委託者からの返還請求を拒む行為にも横領罪が成立することになりかねず，妥当でないとの批判ができる。
          e: エ．この【見解】は，横領罪の保護法益が所有権であることを重視し，委託信任関係の破壊という点を全く考慮していない。
          o: オ．この【見解】に対しては，不法原因給付の目的物の所有権は，給付者において給付した物の返還を請求できないことの反射的効果として，受給者に帰属するに至ったと解すべきであるとする立場を前提とすると，横領罪にいう「他人の物」を領得したわけではないのに受託者に横領罪の成立を認めることになり，妥当でないとの批判ができる。（参照条文）民法第708条不法な原因のために給付をした者は，その給付したものの返還を請求することができない。ただし，不法な原因が受益者についてのみ存したときは，この限りでない。
        additional_answer:
          1: 1．アエ
          2: 2．アオ
          3: 3．イウ
          4: 4．イエ
          5: 5．ウオ
          6:
          7:
          8:
      17:
        questions: 次のアからオまでの各事例における甲の罪責について，判例の立場に従って検討し，（）内の犯罪が既遂になる場合には1を，未遂にとどまる場合には2を，既遂にも未遂にもならない場合には3を選びなさい。］
        answer:
          a: ア．甲は，会社事務所内において現金を窃取して，戸外に出たところを警備員乙に発見されて取り押さえられそうになったため，逮捕を免れようと考え，乙に対し，刃体の長さ20センチメートルの出刃包丁をその腹部に突き付け，「ぶっ殺すぞ」と怒鳴り付けたが，偶然その場を通り掛かった警察官に取り押さえられ，逮捕を免れることができなかった。（事後強盗罪）[№28］
          i: イ．甲は，行使の目的で，カラープリンターを用いて，複写用紙に真正な千円札の表面及び裏面を複写して千円札を偽造しようとしたが，カラープリンターの操作を誤ったため，完成したものは，一般人がこれを一見した場合に真正な千円札と誤認する程度の外観を備えたものではなかった。（通貨偽造罪）[№29］
          u: ウ．甲は，通行中の乙に因縁を付けて乙から現金を脅し取ろうと考え，乙に対し，「俺をにらんできただろ。金を払えば許してやる。金を出せ。」などと大声で怒鳴り付けて反抗を抑圧するに至らない程度の脅迫を加え，同脅迫により畏怖した乙は，甲に現金を直接手渡さなかったものの，甲が乙のズボンのポケットから乙が所有する現金在中の財布を抜き取って持ち去るのを黙認した。（恐喝罪）[№30］
          e: エ．甲は，知り合いの女性乙を自己が運転する自動車に乗せて同車内において強いて姦淫しようと考え，乙に対し，「自宅まで送ってあげる。」とうそを言ったところ，乙は，これを信じて同車に乗り込んだが，甲の態度を不審に思い即座に同車から降りた。（強姦罪）[№31］
          o: オ．甲は，会社事務所にある現金を窃取する目的で，門塀に囲まれ，警備員が配置されて出入りが制限されている同事務所の敷地内に塀を乗り越えて立ち入ったが，同事務所の建物に立ち入る前に警備員に発見され敷地外に逃走した。（建造物侵入罪）[№32］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      18:
        questions: 名誉毀損罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．摘示される「事実」は，非公知のものでなければならないから，公知の事実を摘示した場合には，名誉毀損罪は成立しない。
          2: 2．事実の摘示が「公然」といえるためには，摘示内容を不特定かつ多数人が認識し得る状態にあったことが必要であるから，不特定ではあるが，少数人しか認識し得ない状態にとどまる場合には，名誉毀損罪は成立しない。
          3: 3．名誉の主体である「人」は，自然人に限られるから，法人の名誉を毀損した場合には，名誉毀損罪は成立しない。
          4: 4．死者の名誉を毀損したとしても，虚偽の事実を摘示した場合でなければ処罰されないから，摘示した事実が真実である場合には，名誉毀損罪として処罰されない。
          5: 5．人の名誉を侵害するに足りる事実を公然と摘示したとしても，現実に人の名誉が侵害されていない場合には，名誉毀損罪は成立しない。
          6:
          7:
          8:
      19:
        questions: 学生A，B及びCは，次の【事例】における甲の罪責について，後記【会話】のとおり検討している。【会話】中の①から⑤までの（）内から適切な語句を選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。【事例】甲は，乙がVに対して暴行を加えていたところに通り掛かり，乙との間で共謀を遂げた上，乙と一緒にVに対して暴行を加えた。Vは，甲の共謀加担前後にわたる一連の暴行を加えられた際に1個の傷害を負ったが，Vの傷害が，甲の共謀加担前の乙の暴行により生じたのか，甲の共謀加担後の甲又は乙の暴行により生じたのかは，証拠上不明であった。【会話】学生A．私は，共犯は自己の行為と因果関係を有する結果についてのみ責任を負うという見解に立ち，後行者は，共謀加担前の先行者の暴行により生じた傷害結果には因果性を及ぼし得ないと考えます。事例の場合，甲には①（a．暴行罪・b．傷害罪）の共同正犯が成立すると考えます。事例とは異なり，Vの傷害が甲の共謀加担後の甲又は乙の暴行により生じたことが証拠上明らかな場合，甲には傷害罪の共同正犯が②（c．成立する・d．成立しない）と考えます。学生B．A君の見解に対しては，甲に対する傷害罪の成立範囲が③（e．狭く・f．広く）なり過ぎるとの批判が可能ですね。学生C．私は，事例の場合には，同時傷害の特例としての刑法第207条が適用され，甲は，Vの傷害結果について責任を負うと考えます。その理由の一つとして，仮に甲が乙と意思の連絡なく，Vに暴行を加えた場合に比べ，事例における甲が④（g．不利・h．有利）に扱われることになるのは不均衡であると考えられることが挙げられます。学生B．乙には，甲の共謀加担前後にわたる一連の暴行の際にVに生じた傷害結果についての傷害罪が成立するのであり，傷害結果について責任を負う者が誰もいなくなるわけではないということは，C君の⑤（i．見解に対する批判・j．見解の根拠）となり得ますね。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②c③e④h⑤i
          2: 2．①b②d③f④g⑤j
          3: 3．①a②c③f④g⑤j
          4: 4．①b②c③e④h⑤i
          5: 5．①a②c③e④g⑤j
          6:
          7:
          8:
      20:
        questions: 次の【事例】に関する後記1から5までの各【記述】を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，[№3，[№36］順不同）【事例】甲は，覚せい剤の密売人である乙から，偽造した1万円札と引換えに覚せい剤をだまし取ろうと考え，1万円札の偽造に使用する目的で，作業部屋を自己名義で賃借した上，印刷機及び印刷用紙を購入して同部屋に運び込み，それらを使用して1万円札100枚を偽造した。（①）その後，甲は，ホテルの部屋で乙と会い，乙に対し，100万円相当の覚せい剤（以下「本件覚せい剤」という。）の代金として，偽造した1万円札100枚を渡した。乙は，甲から渡された1万円札が偽札であることに気付かずに，甲に対し，本件覚せい剤を渡し，甲は，これを持って同部屋を出た。（②）甲は，本件覚せい剤をホテルの駐車場に駐車中の自己の自動車内に置いたところ，甲が乙に渡した1万円札が偽札であることに気付いて追い掛けてきた乙から，本件覚せい剤を返還するように求められた。甲は，本件覚せい剤の返還を免れるため，殺意をもって乙の首を両手で絞めて乙を殺害した。（③）その数日後，甲は，本件覚せい剤を所持しているのを警察官に現認され，覚せい剤取締法違反の現行犯人として逮捕され，A警察署に連行された。警察官丙は，A警察署の取調室において，甲の弁解録取手続を行い，甲の供述内容を弁解録取書に記載した上，同弁解録取書を甲に手渡して内容の確認を求めたところ，甲は，署名押印する前に同弁解録取書を両手で破った。（④）甲は，同取調室から逃げ出し，A警察署の敷地外に出た。（⑤）【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①について，甲が作業部屋を自己名義で賃借した行為は，通貨偽造罪の予備行為に該当することから，その段階で甲には通貨偽造等準備罪が成立する。
          2: 2．②について，甲には詐欺罪が成立し，偽造通貨行使罪は詐欺罪に吸収される。
          3: 3．③について，覚せい剤は，法定の除外事由なく所持することが禁じられた物であるが，甲は，本件覚せい剤の返還を免れるために乙を殺害していることから，甲には強盗殺人罪が成立する。
          4: 4．④について，丙が作成した弁解録取書には，甲の署名押印がないが，甲の供述内容が記載されていることから，甲には公用文書等毀棄罪が成立する。
          5: 5．⑤について，甲は，逮捕中に逃走し，A警察署の敷地外に出ていることから，甲には単純逃走罪が成立する。
          6:
          7:
          8:
