---
ja:
  keiho:
    2018:
      1:
        questions: 刑罰論に関する次の各【見解】についての後記1から5までの各【記述】のうち，誤っているものを2個選びなさい。（解答欄は，［№1，［№2］順不同）【見解】A．刑罰の目的は，行為者が将来再び犯罪を行うのを予防することにある。B．刑罰の目的は，刑罰による威嚇を通して一般人が犯罪を行うのを予防することにある。C．刑罰は，犯罪を行った者が果たさなければならないしょく罪である。D．刑罰の目的は，処罰により行為者の行為が犯罪であると公的に確認され，これを通して一般人が犯罪を行うのを予防することにある。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．Aの見解に対しては，軽微な犯罪を行った者であっても，その更生に必要であれば，長期の拘禁刑を科すことが正当化されるおそれがあるとの批判が可能である。
          2: 2．Bの見解に対しては，刑罰は重ければ重いほどよいという考え方に陥るおそれがあるとの批判が可能である。
          3: 3．Cの見解は，軽微な犯罪を行った者であっても，一般予防の必要性が高いときはその刑を重くしなければならないとの考え方に親和的である。
          4: 4．Cの見解に対しては，犯罪を行った者に対し，その処罰を猶予する余地がなくなるとの批判が可能である。
          5: 5．Dの見解は，自由意思の存在を認めない決定論を前提として初めて成り立つものである。
          6:
          7:
          8:
      2:
        questions: 次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．甲は，同僚Aを会社の備品倉庫内に閉じ込めて困らせようと考え，午後7時頃，Aが一人で作業をしていた同倉庫の全ての出入口扉に外側から鍵を掛けた。Aはそのことに気付かず，もともと同倉庫で深夜遅くまで仕事をするつもりであったので，そのまま作業を続けていたところ，午後10時頃，たまたま同倉庫にやって来た他の従業員が出入口扉の鍵を開けた。この場合，甲には監禁罪は成立し得ない。
          i: イ．甲は，別居中の元妻Aが単独で親権を有する生後数日のBを連れ去ろうと考え，A方を訪問した上，Aがトイレに行っている隙に，ベビーベッドで寝ていたBを連れ去った。この場合，Bには移動の自由が全くないから，甲には未成年者略取罪は成立し得ない。
          u: ウ．甲は，捜査車両をのぞき見て同車両のナンバーを把握するため，警察署の建物及び敷地への外部からの立入りを制限するとともに内部をのぞき見ることができない構造として作用し，建物の利用のために供されている高さ約
          e: エ．甲は，Aに恨みを抱き，「ふざけるな。おまえの妻Bを酷い目に遭わせてやる。」という電子メールをA宛てに送り付けた。BがAの内縁の妻であった場合，甲には脅迫罪は成立し得ない。
          o: オ．甲は，深夜，A方に侵入し，泥酔して熟睡中のAにわいせつ行為をして，Aに全く気付かれないままA方を出た後，A方から約100メートル離れた路上で，警ら中の警察官Bから職務質問を受けたため，逮捕を免れる目的で，Bを拳骨で殴打してBに傷害を負わせた。この場合，甲には準強制わいせつ致傷罪は成立し得ない。
        additional_answer:
          1: 1．アイ
          2: 2．5メートルのコンクリート塀を正当な理由なくよじ登り，その上部に立って同警察署の敷地内の捜査車両を見て立ち去った。この場合，甲には建造物侵入罪は成立し得ない。
          3: 3．イウ
          4: 4．ウエ
          5: 5．エオ
          6:
          7:
          8:
      3:
        questions: 過失犯の本質について，学生A及びBが次の【会話】のとおり議論している。【会話】中の①から④までの（）内に後記アからキまでの【発言】から適切なものを選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。【会話】学生A．私は，過失犯の本質について，精神を緊張させたならば結果発生を予見することが可能であったにもかかわらず，これを予見しなかったことにあると考えています。私が採る見解では，過失犯の体系上，一般的に，（①）の判断において，信頼の原則を考慮することになります。学生B．A君が採る見解に対しては，（②）という批判がありますね。私は，過失犯の本質について，社会生活上必要な注意を尽くさないで，結果回避のための適切な措置を採らなかったことにあると考えています。学生A．B君が採る見解に対しては，「結果回避のための適切な措置」について，（③）という批判があります。また，B君が指摘した批判に対しては，私が採る見解でも，（④）ことにより，対応することができるとの反論ができます。【発言】
        answer:
          a: ア．予見可能性
          i: イ．結果回避義務
          u: ウ．行政取締法規が定める義務に帰着せざるを得ず，刑法上の過失犯が行政取締法規違反の結果的加重犯になってしまう
          e: エ．予見可能性のみで過失を認めると，過失犯の処罰範囲が広くなり過ぎる
          o: オ．重大な結果が予見可能であるにもかかわらず，それを回避する義務がないというのは妥当ではないカ．実行行為の内容として実質的危険性を要求するキ．予見可能性を結果回避義務を導く前提要件として位置付ける
        additional_answer:
          1: 1．①ア②ウ③エ④キ
          2: 2．①ア②エ③ウ④カ
          3: 3．①ア②エ③オ④キ
          4: 4．①イ②ウ③オ④カ
          5: 5．①イ②エ③ウ④キ
          6:
          7:
          8:
      4:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，Aから現金を借り入れるに当たり，借入金をAに自ら返済する意思も能力もないのに，乙に対し，「自分がAに返済するので，保証人として名前を貸してほしい。」とうそを言い，その旨乙を誤信させ，乙に，Aを貸主，甲を借主とする消費貸借契約書の保証人欄に署名押印させた。乙は錯誤に基づいて署名押印しているから，甲には有印私文書偽造罪の間接正犯が成立する。
          2: 2．甲は，取引先乙に見せて自己に信用があることを誇示するだけの目的で，偽造された約束手形を真正なものとして乙に提示した。偽造有価証券行使罪の「行使」といえるためには，偽造有価証券を真正なものとして流通に置く必要があるから，甲には同罪は成立しない。
          3: 3．甲は，偽名を用いて会社に就職しようと考え，同会社に提出する目的で，履歴書用紙に，架空人Aの氏名を記載し，その氏名の横にAと刻した印鑑を押印するとともに，自己の顔写真を貼り付けて履歴書を作成した。同履歴書の作成名義人と作成者との人格の同一性にそごを生じさせるものとは認められないから，甲には有印私文書偽造罪は成立しない。
          4: 4．甲は，信販会社の財産上の事務処理を誤らせる目的で，権限がないのに，同会社の会員名義のクレジットカードの電磁的記録を白地のカード板の磁気部分に印磁して，クレジットカードを構成する電磁的記録を作成したが，その外観は一般人が真正な支払用カードと誤認する程度のものではなかった。支払用カード電磁的記録不正作出罪が成立するためには，一般人が真正な支払用カードと誤認する程度の外観を備える必要はないから，甲には同罪が成立する。
          5: 5．県立高校を中途退学した甲は，父親乙に見せて安心させるだけの目的で，偽造された同高校校長A名義の甲の卒業証書を真正なものとして乙に提示した。甲は，同卒業証書を乙に見せただけであり，公文書に対する公共の信用を害するおそれがないから，甲には偽造有印公文書行使罪は成立しない。
          6:
          7:
          8:
      5:
        questions: 違法性に関する次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．殺人被告事件の弁護人が，同被告事件の真犯人は被告人の兄であると考え，第一審の有罪判決後に行った記者会見で「同被告事件の真犯人は被告人の兄である。」旨発表した場合，弁護活動の一環として行ったものであるから，正当な業務行為として違法性が阻却され，名誉毀損罪は成立し得ない。［№6］
          i: イ．宗教家が，異常な言動を示すようになっていた娘を連れてきた信者の求めに応じ，その娘の不調の原因を取り去る目的で，宗教上の行為として，同人の身体を手で押さえ付け，流れ落ちる滝の水を同人の顔面に打ち当てた結果，同人を窒息死させた場合，宗教活動の一環として行ったものであるから，正当な業務行為として違法性が阻却され，傷害致死罪は成立し得ない。［№7］
          u: ウ．現行犯人を逮捕しようとする私人が，犯人から抵抗を受け，逮捕のために社会通念上必要かつ相当な範囲で実力を行使し同人に傷害を負わせた場合，法令による行為として違法性が阻却され，傷害罪は成立し得ない。［№8］
          e: エ．借地人が，自己の借地内にある自己所有の店舗を増築する必要に迫られ，その借地内に突き出ている隣の家屋の屋根をその所有者の承諾なく切除した場合，自救行為として違法性が阻却され，建造物損壊罪は成立し得ない。［№9］
          o: オ．新聞記者が，取材の目的で国家公務員に秘密漏示を唆した場合，取材の自由は憲法上保障される表現の自由に由来し，十分尊重されるべきであるから，正当な業務行為として違法性が阻却され，国家公務員法違反の罪（秘密漏示教唆罪）は成立し得ない。［№10］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      6:
        questions: 賄賂罪（あっせん収賄罪を除く。）に関する次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．賄賂罪の「賄賂」は，公務員の職務に関する不正な利益であれば足り，個別の職務行為との間に具体的な対価関係があることを要しない。
          i: イ．賄賂罪は，賄賂を収受し，又はその要求若しくは約束をした時点でそれらの行為をした者が公務員でなければ，いかなる場合でも成立しない。
          u: ウ．賄賂罪の「職務」とは，公務員がその地位に伴い公務として取り扱うべき執務をいうが，独立の決裁権限がなく，単に上司の補助をする立場の公務員が取り扱う事務はこれに該当しない。
          e: エ．賄賂罪の「職務」は，公務員の一般的職務権限に属するものであれば足り，公務員が現に具体的に担当している事務であることを要しない。
          o: オ．賄賂罪の「職務」は，賄賂を収受し，又はその要求若しくは約束をした時点で公務員の一般的職務権限に属している必要があり，公務員が一般的職務権限を異にする他の職務に転じた後に前の職務に関して賄賂を収受した場合には，賄賂罪は成立しない。
        additional_answer:
          1: 1．アウ
          2: 2．アエ
          3: 3．イエ
          4: 4．イオ
          5: 5．ウオ
          6:
          7:
          8:
      7:
        questions: 学生A，B及びCは，次の【事例】における甲の罪責について，後記【会話】のとおり議論している。【会話】中の①から④までの（）内から適切なものを選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。【事例】甲は，過失による自動車追突事故を偽装して保険会社から保険金を詐取することを計画し，乙に同計画を打ち明け，乙の真意に基づく同意を得た上で，自己の運転する自動車を乙が運転する自動車に追突させた。その結果，乙は軽微な傷害を負った。【会話】学生A．被害者が自己の身体に対する傷害を同意した場合に傷害罪が成立するか否かにつき，私は，判例と①（a．同様の・b．異なる）立場に立っており，単に同意が存在するという事実だけではなく，その同意を得た動機，目的，身体傷害の手段，方法，損傷の部位，程度など諸般の事情を照らし合わせて，傷害罪の成否を決すべきであると考えます。乙の同意は，保険金詐取という違法な目的に利用するために得られた違法なものであり，これにより，乙に対する傷害行為の違法性が阻却されることはないので，甲には傷害罪が成立すると考えます。学生B．A君の見解に対しては，②（c．個人の自己決定権を重視し過ぎている・d．不可罰である詐欺の予備行為を傷害罪で処罰することになる）という批判があります。学生C．私は，乙の有効な同意がある限り，刑法によって保護すべき法益の侵害がないので，乙に対する傷害行為については，傷害罪の構成要件該当性を欠き，甲には傷害罪が成立しないと考えます。学生A．C君の見解に対しては，③（e．傷害罪の処罰根拠と合理的な関連性のない事情を考慮し過ぎている・f．死亡の結果が発生した場合に傷害致死罪が不成立となるのは不当である）と批判することが可能です。学生C．同意殺人罪に対応する同意傷害罪の規定がない以上，私の見解のように，同意傷害は不可罰であると解すべきです。学生B．しかし，④（g．同意殺人罪の法定刑に比して傷害罪の法定刑は重い・h．同意殺人罪は，殺人罪の法定刑の下限の重さが考慮されて，その減軽類型として特に設けられたものである）ので，同意傷害罪の規定がないことは理由にならないと思います。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②c③e④h
          2: 2．①a②d③f④g
          3: 3．①a②d③f④h
          4: 4．①b②c③e④g
          5: 5．①b②d③f④g
          6:
          7:
          8:
      8:
        questions: 次のアからオまでの各記述における甲の罪責について判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．甲が，自然湖の一部に設けられた乙のいけすから逃げ出した乙所有の錦鯉30匹を，同湖内の同いけすから離れた場所で発見し，乙が所有する錦鯉であると認識しながら，これらを自己のものにしようと考えて捕獲した場合，窃盗罪が成立する。
          i: イ．甲は，パチスロ機に針金を差し込んで誤作動させてメダルを窃取することを乙と共謀し，乙による窃盗の犯行を周囲から見えにくくするため，乙の隣のパチスロ機で通常の遊戯を行い，それによりメダルを取得した。この場合，甲自身が遊戯したパチスロ機で取得したメダルについても窃盗罪が成立する。
          u: ウ．甲が，乙から封かんされた現金20万円入りの封筒を渡されてそれを丙に届けるように依頼されたが，丙方に向かう途中で封筒内の現金が欲しくなり，封を開いて封筒に入っていた現金のうち5万円を取り出してこれを自己のものとし，残りの現金が入った封筒を丙に交付した場合，取り出した5万円について窃盗罪が成立する。
          e: エ．甲は，乙から，乙が海中に落とした腕時計の引き揚げを依頼され，その腕時計が落ちた場所の大体の位置を指示された。甲が，乙から指示された海中付近を探索した結果，同腕時計を発見したが，それを乙に知らせることなく，同腕時計を引き揚げて自己のものとした場合，窃盗罪が成立する。
          o: オ．甲が，満員電車に乗っていた際，隣の席に座っていた見ず知らずの乙が財布を座席に置き忘れたままX駅で下車したのを目撃し，乙の財布とその中身を自己のものにしようと考え，次のY駅に到着した時点で乙の財布を取得した上，同駅で下車し自宅に持ち帰った場合，窃盗罪が成立する。
        additional_answer:
          1: 1．アイ
          2: 2．アオ
          3: 3．イエ
          4: 4．ウエ
          5: 5．ウオ
          6:
          7:
          8:
      9:
        questions: 次の1から5までの各記述のうち，誤っているものを2個選びなさい。（解答欄は，［№14［№15］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．刑の全部の執行猶予の言渡しを受けた者が，猶予の期間内に更に罪を犯しても，罰金に処せられたときには，刑の全部の執行猶予の言渡しを取り消さなくてもよい。
          2: 2．懲役に処せられた者がその執行を終わった日から5年以内に更に罪を犯し，その者を有期懲役に処するとき，その刑は，その罪について定めた懲役の長期の2倍以下とするが，その場合でも懲役20年までしか上げることができない。
          3: 3．懲役又は禁錮に処せられた者に改悛の状があるときは，無期刑については10年を経過した後，行政官庁の処分によって仮に釈放することができる。
          4: 4．1個の行為が2個以上の罪名に触れる場合，それらの罪についていずれも有期懲役に処するとき，その刑は，その最も重い罪について定めた刑の長期にその2分の1を加えたものを長期とする。
          5: 5．親告罪に当たる罪を犯した者が，捜査機関及び告訴権者に発覚する前に，告訴権者に対して自己の犯罪事実を自発的に告げ，告訴するかどうかについて告訴権者の措置に委ねた場合，その刑を減軽することができる。
          6:
          7:
          8:
      10:
        questions: 強盗致傷罪に関する次の各【見解】AないしDに従って後記各【事例】ⅠないしⅢにおける甲の罪責を検討し，後記1から5までの各【記述】のうち，正しいものを2個選びなさい。（解答欄は，［№16［№17］順不同）【見解】A．致傷結果は，強盗の機会に行われた行為から発生すれば足りる。B．致傷結果は，強盗の手段である暴行から発生する必要がある。C．致傷結果は，強盗の手段である暴行のほか，強盗の機会に行われた行為のうち，強盗行為とその性質上密接な関連性を有する行為から発生する必要がある。D．致傷結果は，強盗の手段である暴行のほか，強盗の機会に刑法第238条所定の目的で行う暴行から発生する必要がある。【事例】Ⅰ．甲は，自らの強盗の犯行を乙に目撃されたところ，犯行の翌日，犯行現場から約10キロメートル離れた路上において，たまたま乙に発見され，乙に捕まらないようにするため，乙の顔面を拳骨で多数回殴打し，乙に傷害を負わせた。Ⅱ．甲は，乙から金品を強取することを丙と計画し，丙と共に乙方に侵入して乙から金品を強取したが，その直後，乙方において，丙に対する日頃の不満を解消するためだけに，丙の顔面を拳骨で多数回殴打し，丙に傷害を負わせた。Ⅲ．甲は，乙から金品を強取することを計画し，乙方に侵入して乙に包丁を突き付けて金品を要求したが，これに乙が応じなかったため，金品強取を諦めて逃走しようとしたところ，乙から金品を強取できなかった腹いせに，乙とは別の部屋で寝ていた1歳の丙の腹部を多数回蹴り付け，丙に傷害を負わせた。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．Aの見解によれば，事例ⅠからⅢのいずれでも強盗致傷罪が成立する。
          2: 2．Bの見解によれば，事例ⅠからⅢのいずれでも強盗致傷罪が成立しない。
          3: 3．Cの見解によれば，事例Ⅱでは強盗致傷罪が成立しない。
          4: 4．Dの見解によれば，事例Ⅰでは強盗致傷罪が成立する。
          5: 5．Dの見解によれば，事例Ⅲでは強盗致傷罪が成立する。
          6:
          7:
          8:
      11:
        questions: 責任能力に関する次の1から5までの各記述のうち，判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．裁判所は，責任能力の有無・程度について，専門家たる精神医学者の意見を十分に尊重して判定すべきであるから，精神鑑定の意見の一部だけを採用することは許されない。
          2: 2．行為者が犯行時に心神耗弱状態にあった場合でも，その刑を減軽しないことができる。
          3: 3．犯行時に事物の是非善悪を弁識する能力が著しく減退していても，行動を制御する能力が十分に保たれていれば，完全責任能力が認められることがある。
          4: 4．精神の障害がなければ，心神喪失又は心神耗弱と認められる余地はない。
          5: 5．14歳の者は，事物の是非善悪を弁識し，その弁識に従って行動する能力が十分に認められる場合であっても，処罰されない。
          6:
          7:
          8:
      12:
        questions: 詐欺罪に関する次の1から5までの各記述のうち，判例の立場に従って検討した場合，誤っているものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．航空会社の空港係員に対し，内心では，外国への不法入国を企てている知人を搭乗させるつもりであるのに，自らが搭乗するとうそを言って，あらかじめ航空券を購入していた航空便について搭乗券の交付を求め，同係員から搭乗券の交付を受けた場合，当該搭乗券についての詐欺罪が成立する。
          2: 2．自動車販売会社の販売員に対し，その代金を支払う意思も能力もないのに，これらがあるように装って自動車の購入を申し込み，分割払いの約定で同販売員から自動車の引渡しを受けた場合，代金完済まで同自動車の所有権が同会社に留保されていても，詐欺罪が成立する。
          3: 3．他人名義の国民健康保険被保険者証を利用して消費者金融から借入れをしようと考え，その他人に成り済まして，市役所職員を欺いて国民健康保険被保険者証の交付を受けた場合，詐欺罪が成立する。
          4: 4．自己名義の銀行預金口座に多額の誤った振込みがなされていることを知った上で，同銀行の窓口係員に対し，誤った振込みがあった旨を告知することなく同口座の残金全額の払戻しを請求し，同係員から即時にその払戻しを受けた場合，詐欺罪が成立する。
          5: 5．他人所有の土地を当該他人から買い受けた事実がないのに，当該他人から盗んだ印鑑を押して登記申請に必要な書類を偽造した上，これを登記官に提出し，当該他人に無断で，自己への所有権移転登記を完了させた場合，当該土地についての詐欺罪が成立する。
          6:
          7:
          8:
      13:
        questions: 共犯の従属性に関する次の【見解】に従って後記1から5までの各【記述】を検討した場合，正しいものを2個選びなさい。（解答欄は，［№20［№21］順不同）【見解】共犯が成立するためには，正犯の行為が構成要件に該当し，違法性を具備することを要する。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲が強盗犯人Aの妻乙を唆してAを蔵匿させた場合，甲には犯人蔵匿罪の教唆犯は成立し得ない。
          2: 2．甲が刑法第41条の刑事未成年者に当たる乙を唆して窃盗を行わせた場合，甲には窃盗罪の教唆犯は成立し得ない。
          3: 3．甲が乙にAが一人で居住する家屋に侵入するよう唆したところ，乙がAの承諾を得て平穏にその家屋に立ち入った場合，甲には住居侵入罪の教唆犯は成立し得ない。
          4: 4．甲が乙を唆して私文書を偽造させたが，乙に行使の目的がなかった場合，甲には私文書偽造罪の教唆犯は成立し得ない。
          5: 5．甲が乙に偽証するよう唆したところ，乙が証人として法律により宣誓した上，虚偽の陳述をしたが，証人尋問手続が終了した後，判決言渡し前に自白した場合，甲には偽証罪の教唆犯は成立し得ない。
          6:
          7:
          8:
      14:
        questions: 逃走の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．拘置所に未決勾留中の甲は，逃走しようと考え，房内の換気孔周辺の壁を削って損壊したものの，脱出可能な穴を開けられなかった。甲に加重逃走罪の未遂罪が成立する余地はない。
          2: 2．確定判決によってA刑務所に収容されていた甲は，B刑務所への護送中，刑務官の隙を見て護送車から脱出し，刑務官の追跡を完全に振り切って民家の庭に隠れたが，しばらくして，付近の捜索を継続していた刑務官に発見されて護送車に連れ戻された。甲に逃走罪の既遂罪が成立する余地はない。
          3: 3．刑務官である甲は，勤務先の拘置所に未決勾留中で，自らが看守していた被告人乙を逃走させようと考え，乙の房の扉を解錠し，乙を同拘置所から逃走させた。甲に看守者逃走援助罪が成立する余地はない。
          4: 4．確定判決によって刑務所に収容されていた甲は，その看守に当たっていた刑務官に対する単なる反抗として同刑務官を押し倒したところ，同刑務官が気絶したため，その隙に逃走しようと思い立ち，同刑務所から逃走した。甲に加重逃走罪が成立する余地はない。
          5: 5．甲は，逮捕状により警察官に逮捕された乙の身柄を奪い返そうと考え，路上において，乙を連行中の同警察官に対し，体当たりをする暴行を加え，同警察官がひるんだ隙に，同所から乙を連れ去った。甲に被拘禁者奪取罪が成立する余地はない。
          6:
          7:
          8:
      15:
        questions: 学生A，B及びCは，身分犯の共犯に関して，次の【会話】のとおり検討している。【会話】中の①から③までの（）内から適切なものを選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。］【会話】学生A．私は，刑法第65条第1項は構成的身分の連帯作用を，同条第2項は加減的身分の個別作用を定めたものであると考えます。そして，財物を占有していない甲が，その財物を業務上占有する乙を教唆して，その財物を横領させた事案では，甲には，業務上横領罪の教唆犯が成立すると考えます。学生B．A君は，業務上横領罪における「業務」や「占有」という点について，①（a．「業務上占有」していることが，非占有者との関係で構成的身分・b．「占有」は構成的身分であり，「業務」は加減的身分）と考えているのですね。私は，刑法第65条第1項は「共犯とする」と規定し，身分犯における共犯の成立について定めたもの，同条第2項は「通常の刑を科する」と規定し，非身分者について刑の個別作用を定めたものであると考えています。同じ事案につき，私の立場からすると，甲には，②（c．単純横領罪の教唆犯が成立し，同罪の刑が科せられる・d．業務上横領罪の教唆犯が成立し，同罪の刑が科せられる・e．業務上横領罪の教唆犯が成立し，単純横領罪の刑が科せられる）ことになります。学生C．B君は，遺失物等横領罪の刑は「通常の刑」ではないと考えているのですね。私は，刑法第65条第1項は行為の違法性に関係する身分，すなわち違法身分の連帯作用を，同条第2項は行為者の責任に関係する身分，すなわち責任身分の個別作用を規定したものであると考えます。私の見解に立ち，占有者という身分を違法身分，業務者という身分を責任身分と考えた場合，甲には，③（f．単純横領罪の教唆犯が成立する・g．業務上横領罪の教唆犯が成立する・h．業務上横領罪の教唆犯が成立し，単純横領罪の刑が科せられる）ことになります。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②d③h
          2: 2．①a②e③f
          3: 3．①a②e③h
          4: 4．①b②c③f
          5: 5．①b②e③g
          6:
          7:
          8:
      16:
        questions: 放火の罪に関する次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．甲は，自己が所有する家屋に一人で居住していたが，同家屋に掛けられた火災保険の保険金を詐取しようと考え，同家屋に放火して全焼させ，公共の危険を生じさせた。甲には自己所有非現住建造物等放火罪（刑法第109条第2項）が成立する。［№24］
          i: イ．甲は，競売手続を妨害する目的で，人が住んでいるように見せ掛けるため，空き屋であった家屋に家財道具を持ち込むなどして住居として使用可能な状態にした上，自己が経営する会社の従業員5名を約1か月半前から10数回にわたり交替で泊まり込ませていたところ，同従業員らが不在にしている隙に，同家屋に放火して全焼させた。甲には現住建造物等放火罪（刑法第108条）が成立する。［№25］
          u: ウ．甲は，乙が住居に使用する家屋及びこれに隣接する丙が住居に使用する家屋を燃やそうと考え，乙の家屋に放火してその火を丙の家屋に燃え移らせ，乙及び丙の各家屋を共に全焼させた。甲には1個の現住建造物等放火罪（刑法第108条）が成立する。［№26］
          e: エ．甲は，住宅街の中にある駐車場内に駐車されていた乙所有の自動車にガソリンをまいて放火したところ，同自動車が勢いよく炎上し，その付近に駐車されていた所有者の異なる自動車3台に火が燃え移りかねない状態になったが，付近の建造物に燃え移る危険は生じなかった。甲には他人所有建造物等以外放火罪（刑法第110条第1項）は成立しない。［№27］
          o: オ．甲は，乙が住居に使用する家屋を燃やそうと考え，同家屋の6畳和室に敷かれた布団に灯油をまいて放火し，火は布団からその下に敷かれた畳に燃え移って炎上したが，他に燃え移る前に乙によって消し止められた。甲には現住建造物等放火罪（刑法第108条）の既遂罪が成立する。［№28］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      17:
        questions: 次の【事例】における甲の罪責について，判例の立場に従って検討した場合，正しいものは，後記1から5までのうちどれか。【事例】甲は，バーの経営者Aから現金を強取しようと考え，12歳の長男乙に，「Aのバーに行ってお金をとってきて。覆面を付けて，『金だ』とか言ってモデルガンを見せなさい。」と言い聞かせた。乙は，当初警察に捕まることを恐れて嫌がっていたが，結局小遣い欲しさから承諾し，甲から覆面とモデルガンを受け取った。乙は，Aのバーまで行き，甲から指示された方法に従って，覆面を付けモデルガンを拳銃のように見せ掛け，Aを脅迫してその反抗を抑圧した。さらに，乙は，自己の判断により，外から人が来ないようにするためバーの出入口ドアの鍵を掛け，Aを店内のトイレに閉じ込めた。その後，乙は，レジ内の現金を強取し，外に出ようとしたところ，トイレから脱出して乙に向かってきたAから腕をつかまれたため，これを激しく振り払った。その結果，Aは転倒して負傷した。乙は，逃走して自宅に戻り，強取した現金を全て甲に渡した。甲はその現金の中から乙に小遣いを与え，その余を生活費等に費消した。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．強盗致傷罪の教唆犯が成立する。
          2: 2．強盗罪の間接正犯が成立する。
          3: 3．強盗致傷罪の間接正犯が成立する。
          4: 4．強盗罪の共同正犯が成立する。
          5: 5．強盗致傷罪の共同正犯が成立する。
          6:
          7:
          8:
      18:
        questions: 信用及び業務に対する罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．信用毀損罪における「流布」とは，虚偽の風説を不特定又は多数の人が認識可能な状態に置くことをいい，行為者自らが直接に不特定又は多数の人に告知する場合のみならず，特定かつ少数の者を通じて順次不特定又は多数の人に伝播させる場合も含まれる。
          2: 2．電子計算機損壊等業務妨害罪は，電子計算機に向けられた加害行為を手段とする業務妨害行為を処罰対象とするものであるところ，同罪の加害行為は，「人の業務に使用する電子計算機若しくはその用に供する電磁的記録を損壊」することと「人の業務に使用する電子計算機に虚偽の情報若しくは不正な指令を与え」ることに限られる。
          3: 3．威力業務妨害罪における「威力を用いて」とは，人の意思を制圧するような勢力を行使することをいい，このような勢力が業務に従事している人に対して直接行使されることを要する。
          4: 4．信用毀損罪は，公訴が提起されることにより公判において事件の内容が明らかになり，かえって被害者の信用が損なわれる事態を招くおそれがあるため，被害者による告訴がなければ公訴を提起することができない。
          5: 5．強制力を行使しない公務は，業務妨害罪における「業務」には該当するが，公務執行妨害罪における「職務」には該当しない。
          6:
          7:
          8:
      19:
        questions: 次の【見解】に従って後記の【事例】及び各【記述】を検討した場合，【事例】よりも逮捕監禁行為と死亡との間の因果関係を肯定する判断に結び付きやすいものは，後記1から5までの各【記述】のうちどれか。］【見解】因果関係の存否は，行為の危険性が結果に現実化したものと評価できるかどうかで判断すべきであり，その評価に当たっては，介在事情の異常性と結果への寄与度を考慮すべきである。【事例】Aは，普通乗用自動車（以下「A車」という。）後部のトランク内にVを押し込み，トランクカバーを閉めて脱出不能にしA車を発進走行させた後，市街地の路上で停車させた。A車の停車場所は，片側1車線のほぼ直線の道路上であった。A車が停車して数分後，後方からXが運転する普通乗用自動車（以下「X車」という。）が走行してきたが，Xは前方不注視（脇見運転）のため，A車の後部に真後ろからX車を追突させた。これによって同トランク内に閉じ込められていたVは傷害を負い，救助が得られないまま同傷害により死亡した。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．上記【事例】において，仮に，A車の停車場所が片側3車線道路の道路端に設けられた路上駐車場であった場合
          2: 2．上記【事例】において，仮に，Aが，A車後部のトランク内にVを押し込み，トランクカバーを閉める際に同カバーをVに強く打ち付ける暴行を加えてVに重度の傷害を負わせ，その結果，X車の追突時にはVが既に瀕死状態に陥っており，X車の追突により同傷害が悪化してVの死期が幾分早まった場合
          3: 3．上記【事例】において，仮に，Vが，X車の追突直後，通行人の通報により臨場した救急車で病院へ搬送されたが，同病院の医師の重大な医療過誤により死亡した場合
          4: 4．上記【事例】において，仮に，Xが，A車後部のトランク内にVが閉じ込められていることを知っており，Vを殺害する目的で，あえてX車をA車に追突させた場合
          5: 5．上記【事例】において，仮に，駐車中のA車にX車が追突せず，飛行中のヘリコプターが墜落してA車に衝突し，これによってVが傷害を負って死亡した場合
          6:
          7:
          8:
      20:
        questions: 次の【事例】に関する後記アからオまでの各【記述】を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからオの順に[№32]から[№36]）【事例】甲は，別居している実弟Aとの間で，自己が所有するX市内の土地（以下「本件土地」という。）を代金3000万円で売却する売買契約を締結し，Aから代金全額の支払を受けたものの，本件土地の所有権移転登記は未了のままであった。そこで，甲は，自己が経営する会社の資金繰りのため，自らが保管していた本件土地の登記済証を利用し，事情を知らないBに対して，本件土地に抵当権を設定するので，それを担保に1000万円を融資してほしい旨申し入れたところ，Bは，これを了承した。数日後，甲は，Bから1000万円の融資を受けた上，Aに無断で本件土地の抵当権設定登記を完了した。X市の土木部長である乙は，本件土地を乙個人として購入したいと考え，甲に対して，その旨を申し入れた。甲は，乙に対して，本件土地は既にAに売却済みであるが，登記名義は自分に残っているので，代金2000万円で売却してもよい旨を伝えたところ，乙は，これを了承した。そして，乙は，Y市内に時価700万円の農地（以下「本件農地」という。）を所有していたことから，本件土地の購入資金を調達するため，それまでにX市発注の公共工事の受注に際して，土木部長として便宜を図ってきた建築業を営むCに対して，本件農地を時価で買い取ってほしい旨を依頼した。Cは，本件農地にはそれまで買手が全く見付からず，乙が苦労していることを知りながら，かねてX市発注の公共工事の受注に際して乙が有利な取り計らいをしてくれたことに対する謝礼の趣旨に加え，時価であれば損をすることもないと考えて，乙の依頼を了承した。そして，Cは，乙と本件農地の売買契約を締結した上で，乙に現金700万円を手渡した。その後，甲は，Aに無断で乙と本件土地の売買契約を締結し，乙から代金全額の支払を受けた上，本件土地の所有権が売買により乙に移転した旨の登記を完了した。【記述】
        answer:
          a: ア．甲がAに無断で本件土地に抵当権を設定し，その旨の登記を完了したことについては，甲に横領罪が成立するが，Aは甲の実弟であるので，告訴がなければ公訴を提起することができない。［№32］
          i: イ．甲が本件土地をAに無断で乙に売却し，所有権移転登記を完了したことについては，それ以前に甲がAに無断で本件土地に抵当権を設定し，その旨の登記を完了したことによって，犯罪の成立は妨げられないので，甲に横領罪が成立する。［№33］
          u: ウ．乙は，本件農地を時価でCに売却したのであるから，乙がCから交付を受けた現金700万円は通常の経済取引に基づく不動産の購入代金であり，不正な利益としての賄賂には当たらないので，乙に収賄罪（収受）は成立しない。［№34］
          e: エ．仮に，乙が，Cに対して，時価を超える1000万円で本件農地を購入するよう依頼したが，Cはこの依頼を拒否した場合，収賄罪と贈賄罪は対向犯として必要的共犯の関係にあるので，乙に収賄罪（要求）は成立しない。［№35］
          o: オ．乙は，甲から本件土地が既にAに売却済みであることを知らされながら，Aに無断で本件土地を購入し，所有権移転登記を完了したのであるから，乙に横領罪の共同正犯が成立する。［№36］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
