---
ja:
  keiho:
    2019:
      1:
        questions: 不作為犯に関する次のアからオまでの各記述を判例の立場に従って検討した場合，誤っているものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．不作為犯は，結果発生を防止しなければならない義務が法律上の規定に基づくものでない場合であっても，成立する余地がある。
          i: イ．不作為犯は，死体遺棄罪についても成立する余地がある。
          u: ウ．不真正不作為犯の故意は，結果の発生を意欲していなくても，認められる余地がある。
          e: エ．不作為犯は，作為可能性がない場合であっても，成立する余地がある。
          o: オ．不作為犯の因果関係は，期待された作為に出ていれば結果が発生しなかったことが，合理的な疑いを超える程度に確実であったといえない場合であっても，その可能性さえあれば，認められる余地がある。
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．イエ
          4: 4．ウオ
          5: 5．エオ
          6:
          7:
          8:
      2:
        questions: 次の【事例】に関する後記アからエまでの各【記述】を判例の立場に従って検討した場合，正しいものの個数を後記1から5までの中から選びなさい。【事例】甲及び乙は，宝石商の丙から宝石を奪うことを計画した。その計画は，甲が，宝石取引のあっせんにかこつけてホテルの一室に丙を呼び出し，別室の顧客に見せる必要があるとうそを言って丙から宝石を受領し，甲の退室後に，乙が同室に入って丙を殺害するという内容であった。甲は，計画に従って，ホテルの一室で丙から宝石を受領して退室し，それと入れ替わりに同室に立ち入った乙が丙の腹部を包丁で刺し，丙に重傷を負わせたが，殺害には至らなかった。【記述】
        answer:
          a: ア．甲が丙から宝石を受領した行為について詐欺罪が成立すると考えた場合，甲及び乙に，事後強盗による強盗殺人未遂罪が成立することはない。
          i: イ．甲が丙から宝石を受領した行為について詐欺罪が成立すると考えた場合，同一の被害を二重に評価することはできないため，甲及び乙が，丙から宝石の代金相当額の支払を免れる意図を持っていたとしても，甲及び乙に，殺人未遂罪が成立するにとどまり，いわゆる二項強盗による強盗殺人未遂罪が成立することはない。
          u: ウ．甲及び乙が，丙から宝石の代金相当額の支払を免れる意図を持っていたとしても，丙がこれを免除又は猶予する旨の財産的処分行為をしていないため，甲及び乙に，いわゆる二項強盗による強盗殺人未遂罪が成立することはない。
          e: エ．乙が丙の腹部を包丁で刺した行為が，丙から宝石の占有を奪取する手段とならないと考えた場合，甲及び乙に，いわゆる一項強盗による強盗殺人未遂罪が成立することはない。
          o:
        additional_answer:
          1: 1．0個
          2: 2．1個
          3: 3．2個
          4: 4．3個
          5: 5．4個
          6:
          7:
          8:
      3:
        questions: 承継的共犯に関する次の各【見解】についての後記アからオまでの各【記述】を検討し，正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからオの順に[№3]から[№7]）【見解】A．共犯は，一個の犯罪を共同して行うものであり，後から犯罪に加担した者も，情を知って一罪の一部に加担した以上，犯罪全体について責任を負う。B．共犯は，自己の行為と因果性がある範囲においてのみ責任を負うべきであって，自らが生じさせていない過去の事実について責任を負うべきではない。C．先行者が生じさせた結果は承継しないが，先行者が生じさせた犯行を容易にする状態が存在する場合に，後行者がその状態を利用して犯罪を実現したときには，後行者も犯罪全体について責任を負う。【記述】
        answer:
          a: ア．Aの見解に対しては，何を一罪として扱うかは，立法政策によって決まるため，一罪性に決定的な意味を認めるのは適切ではないとの批判が可能である。[№3]
          i: イ．Aの見解は，共犯の処罰根拠に関する因果的共犯論に基づいて主張されるものである。[№4]
          u: ウ．Bの見解に対しては，複数の行為からなる犯罪で後行行為だけでは処罰されない場合に，処罰の間隙が生じるとの批判が可能である。[№5]
          e: エ．Cの見解に対しては，単なる憂さ晴らしにより他人に暴行を加えて抗拒不能状態にした後，財物奪取の意思が生じ，その状態を利用して同人から財物を奪取した場合，一般に強盗罪が成立しないとされていることとの比較から問題があるとの批判が可能である。[№6]
          o: オ．甲がVに暴行を加えた後，なお強く抵抗するVに乙が甲と共謀の上で暴行を加え，Vが負傷したが，その傷害結果が共謀成立の前後いずれの暴行によって生じたかを特定できない場合，Cの見解からは，乙には傷害罪の承継的共犯は成立しないことになるのが自然であるが，この帰結は刑法第207条との関係で不均衡であるとの批判が可能である。[№7]
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      4:
        questions: 傷害の罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．傷害罪は，他人の身体の生理的機能を毀損する犯罪であるから，精神疾患の一種である心的外傷後ストレス障害（いわゆるPTSD）を負わせるなど精神的機能の障害を惹起した場合，傷害罪が成立することはない。
          2: 2．傷害罪は，暴行罪の結果的加重犯であるから，被害者に暴行を加えずに身体の生理的機能を毀損した場合，傷害罪が成立することはない。
          3: 3．被害者に睡眠薬を摂取させたことによって一定時間にわたり筋弛緩作用等を伴う急性薬物中毒の症状を生じさせた場合，傷害罪が成立することはない。
          4: 4．傷害の実行行為者をその現場において精神的に鼓舞する行為が傷害罪の幇助に当たる場合，現場助勢罪が成立することはない。
          5: 5．同時傷害の特例は，刑法の基本原理に対する重大な例外規定であり，厳格に適用されなければならないため，その要件を満たす傷害から被害者に死亡結果が生じた場合，同特例の適用により傷害致死罪が成立することはない。
          6:
          7:
          8:
      5:
        questions: 次の各【見解】と後記の各【事例】を前提として，後記アからエまでの各【記述】を検討し，正しい場合には1を，誤っている場合には2を選びなさい。【見解】A．行為当時，客観的に存在した全ての事情及び行為後に生じた事情のうち一般人が予見できた事情を判断の基礎とし，その行為から結果が発生することが相当であると認められる場合に因果関係を肯定する。B．一般人が認識・予見できたであろう事情及び行為者が認識・予見していた事情を判断の基礎とし，その行為から結果が発生することが相当であると認められる場合に因果関係を肯定する。C．行為の危険性が結果へと現実化したといえる場合に因果関係を肯定する。行為の危険性は行為時に存在した全ての事情を基礎として判断する。【事例】Ⅰ．甲は，乙の顔面を手拳で1回殴打した。その殴打は，それだけで一般に人を死亡させるほどの強さではなかったが，乙はもともと特殊な病気により脳組織が脆弱となっており，その1回の殴打で脳組織が崩壊し，その結果，乙が死亡した。Ⅱ．甲は，乙の首をナイフで突き刺し，直ちに治療しなければ数時間のうちに死亡するほどの出血を来す傷害を負わせた。乙は，直ちに病院で適切な医療処置を受け，一旦容体が安定したが，その後，医師の指示に従わず安静に努めなかったため，治療の効果が減殺され，前記傷害に基づき死亡した。Ⅲ．甲は，路上で乙の頭部を激しく殴打し，直ちに治療しなければ1日後には死亡するほどの脳出血を伴う傷害を負わせ，倒れたまま動けない乙を残して立ち去った。そこへたまたま通り掛かった無関係の通行人が，乙の腹部を多数回蹴って，内臓を破裂させ，数時間後に乙は内臓破裂により死亡した。【記述】甲の行為と乙の死亡との間の因果関係については，
        answer:
          a: ア．Ⅰの事例で，行為当時，乙は特殊な病気により脳組織が脆弱となっていることを一般人は認識できず，甲も認識していなかった場合，A及びCの見解からは肯定され，Bの見解からは否定される。［№9］
          i: イ．Ⅰの事例で，行為当時，乙は特殊な病気により脳組織が脆弱となっていることを一般人は認識できず，甲も認識していなかったが，甲はこれを認識できた場合，AからCまでのいずれの見解からも肯定される。［№10］
          u: ウ．Ⅱの事例で，行為当時，乙が治療を受けた後，医師の指示に従わず安静に努めなくなることを一般人は予見できなかったが，甲は予見していた場合，Bの見解からは肯定され，A及びCの見解からは否定される。［№11］
          e: エ．Ⅲの事例で，行為当時，乙が通行人に蹴られることを一般人は予見できず，甲も予見していなかった場合，AからCまでのいずれの見解からも否定される。［№12］
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      6:
        questions: 学生A，B及びCは，監禁罪の客体に関して，次の各【見解】のうち，いずれか異なる見解を採り，後記【事例】について【会話】のとおり検討している。学生A，B及びCの採る見解として正しいものの組合せは，後記1から5までのうちどれか。（解答欄は，[№13]）【見解】
        answer:
          a: ア．監禁されている時点で移動する一般的な能力がある者は，その時点で移動できなくても，監禁罪の客体となる。
          i: イ．監禁されている時点で移動する一般的な能力があり，その時点で現実に移動できる者は，監禁罪の客体となる。
          u: ウ．監禁されている時点で移動する一般的な能力があり，その時点で現実に移動でき，かつ，移動する意思がある者は，監禁罪の客体となる。【事例】乙が窓のない部屋の中に一人でいたところ，甲は，午後1時から午後3時までの間，その部屋の唯一の出入口であるドアに外から施錠し，その間，乙がその部屋の外に出られないようにした。【会話】学生A．乙が甲による施錠に気付かなかった場合，B君が採る見解によれば，監禁罪は成立しますか。学生B．成立します。学生C．私が採る見解でも成立します。では，乙が午後0時30分頃に眠ってしまい，その後，午後2時頃に目覚めて，甲による施錠に気付かないまま午後4時まで室内で過ごした場合，A君が採る見解によれば，監禁罪は成立しますか。学生A．成立しません。学生B．私が採る見解では，結論はA君と異なります。では，今のC君の事例を少し修正し，乙が午後3時過ぎに目覚め，甲による施錠に気付かなかったという場合，C君が採る見解によれば，監禁罪は成立しますか。学生C．成立しません。
          e:
          o:
        additional_answer:
          1: 1．A－アB－ウC－イ
          2: 2．A－イB－アC－ウ
          3: 3．A－イB－ウC－ア
          4: 4．A－ウB－アC－イ
          5: 5．A－ウB－イC－ア
          6:
          7:
          8:
      7:
        questions: 罪数に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は［№14，［№15］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，乙を恐喝して乙から財物の交付を受けるとともに財産上の利益を得た。甲には，包括して1個の恐喝罪が成立する。
          2: 2．甲は，乙ら3名をその面前で同時に恐喝して3名全員からそれぞれ財物を出させ，その3名分の財物の交付を乙から一括して受けた。甲には，3個の恐喝罪が成立し，これらは併合罪となる。
          3: 3．甲は，乙を恐喝して乙から財物の交付を受け，その恐喝の手段として用いられた暴行により乙に傷害を負わせた。甲には，恐喝罪と傷害罪が成立し，これらは併合罪となる。
          4: 4．甲は，恐喝の手段として乙を監禁し，その間に乙を脅迫して乙から財物の交付を受けた。甲には，監禁罪と恐喝罪が成立し，これらは併合罪となる。
          5: 5．甲は，乙が窃取した財物と知りながら，乙を恐喝してその財物の交付を受けた。甲には，盗品等無償譲受け罪と恐喝罪が成立し，これらは併合罪となる。
          6:
          7:
          8:
      8:
        questions: 放火罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものを2個選びなさい。（解答欄は，［№1，［№17］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．「建造物」とは，家屋その他これに類する工作物であって，土地に定着し，人の起居出入りに適する構造を有するものをいい，毀損しなければ家屋から取り外すことができない状態にある雨戸は，「建造物」の一部に当たる。
          2: 2．「放火」とは，目的物の焼損を惹起させる行為をいい，目的物への直接的な点火行為に限られず，媒介物への点火行為であっても，その燃焼作用が継続して目的物に延焼し得るものである場合，「放火」に当たる。
          3: 3．「焼損」とは，火力により目的物の重要部分が焼失し，その本来の効用が失われた状態をいい，不燃性の建造物のコンクリート壁が媒介物の火力によって崩落した場合，「焼損」に当たる。
          4: 4．建造物等以外放火罪にいう「公共の危険」は，現住建造物等放火罪や他人所有非現住建造物等放火罪の客体である建造物等に対する延焼の危険に限られず，不特定又は多数の人の生命，身体又は前記建造物等以外の財産に対する危険も含まれる。
          5: 5．現住建造物等放火罪にいう「現に人が住居に使用し」の「人」には犯人が含まれるが，「現に人がいる」の「人」には犯人が含まれない。
          6:
          7:
          8:
      9:
        questions: 被害者の承諾に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，乙の承諾を得て，乙から借り受けた乙所有の重機を丙に転貸していたが，同重機の修理のため一時これを丙から預かった際，乙の承諾を得て，丙に無断で，自己の借金の返済として同重機を自己の債権者に譲渡した。この場合，甲には，横領罪が成立する。
          2: 2．甲は，自らが組長を務める暴力団の組員乙から，「暴力団を脱退したい。」との申出を受けたので，「落とし前として，指を詰めろ。」と言い，乙の承諾を得て，乙の右手小指の根元を出刃包丁で切断した。この場合，甲には，傷害罪は成立しない。
          3: 3．甲は，乙との不倫関係を清算しようと考え，真実は，乙と心中するつもりはないにもかかわらず，乙に対し，「あの世で一緒になろう。私も君の後を追って死ぬから。」と言って心中を持ちかけ，その旨誤信してこれを承諾した乙に毒薬を手渡したところ，乙がそれを飲んで死亡した。この場合，甲には，自殺関与罪が成立する。
          4: 4．甲は，知人乙から，「生活が苦しく刑務所に入りたいので，私から脅されたという事実をでっち上げて，私を告訴してほしい。」と依頼され，乙の承諾を得て，乙を脅迫罪で告訴した。この場合，甲には，虚偽告訴罪は成立しない。
          5: 5．甲は，自らが刑務官を務める刑務所で受刑中の成人女性乙と恋愛関係になり，乙の承諾を得て，勤務中，同刑務所内において，乙と性交した。この場合，甲には，特別公務員暴行陵虐罪が成立する。
          6:
          7:
          8:
      10:
        questions: 公務員職権濫用罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．公務員職権濫用罪の成立には，必ずしも職権行使の相手方の意思に直接働きかけ，それを制圧することまで要しない。
          2: 2．公務員職権濫用罪の成立には，必ずしも公務員の不法な行為が職務としてなされることまで要しない。
          3: 3．公務員職権濫用罪にいう「職権」は，必ずしも法律上の強制力を伴うことまで要しない。
          4: 4．公務員職権濫用罪にいう「職権」は，職権行使の相手方に対し，必ずしも法律上又は事実上の負担や不利益を生ぜしめるに足りる特別の職務権限であることまで要しない。
          5: 5．公務員職権濫用罪にいう「権利の行使を妨害した」の「権利」は，必ずしも法律に明記されたものであることを要しない。
          6:
          7:
          8:
      11:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものを2個選びなさい。（解答欄は［№20，［№21］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，乙から，甲宛てに荷物を発送したので受け取ってほしいと依頼され，もしかしたら同荷物には覚せい剤を含む身体に有害で違法な薬物が入っているかもしれないと思いながら，乙が覚せい剤を忍び込ませた荷物を受け取って所持していた。この場合，甲には，覚せい剤取締法違反（覚せい剤所持）の罪が成立する。
          2: 2．甲と乙は，丙に暴行を加えて傷害を負わせることを共謀したところ，乙において，丙に暴行を加えている最中に興奮して殺意を生じ，丙を殺害した。この場合，甲には，傷害罪の共同正犯が成立する。
          3: 3．甲は，乙が第三者から窃取した指輪を，もしかしたら盗品かもしれないと思いながら，あえて有償で乙から譲り受けた後，同指輪に乙と同じイニシャルが刻み込まれていることに気付き，盗品ではないと確信するに至った。この場合，甲には，盗品等有償譲受け罪が成立する。
          4: 4．甲は，わいせつな映像を録画したDVDを，あらかじめその内容を再生して確認し，この程度ではわいせつ物には当たらないと考えて，多数の者に販売した。この場合，甲には，わいせつ物頒布罪が成立する。
          5: 5．甲は，乙を殺害しようと考え，乙の背部を狙って拳銃の弾丸を発射したところ，同弾丸が乙ではなく，乙の隣にいた丙の腹部に当たり，丙を死亡させた。この場合，甲には，乙に対する殺人未遂罪と丙に対する重過失致死罪が成立する。
          6:
          7:
          8:
      12:
        questions: 業務妨害罪に関する次の【見解】についての後記1から5までの各【記述】のうち，誤っているものはどれか。］【見解】業務妨害罪は人の社会的活動の自由を保護法益とするものであるが，公務も人の社会的活動にほかならないから，公務の性質いかんにかかわらず，同罪によって保護されると解するのが妥当である。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．この【見解】に対しては，公務執行妨害罪という国家的法益に対する罪と業務妨害罪のような個人的法益に対する罪とを安易に混同するものであるとの批判が可能である。
          2: 2．この【見解】に基づけば，公務員と共に公務に従事する非公務員に暴行を加えてその公務を妨害した場合，威力業務妨害罪が成立すると考えることが可能である。
          3: 3．この【見解】に対しては，逮捕行為のような強制力を行使する権力的公務は，暴行にも脅迫にも至らない手段による妨害を受けた時にそれを自力で排除し得るから，そのような公務まで業務として保護する必要はないとの批判が可能である。
          4: 4．この【見解】に基づけば，公務が暴行又は脅迫によって妨害された場合，公務執行妨害罪は業務妨害罪の特別法という関係にあるから前者のみが成立すると考えることが可能である。
          5: 5．この【見解】に対しては，威力や偽計による公務の妨害は公務執行妨害罪にも業務妨害罪にも当たらないこととなり，公務が業務に比して刑法上軽い保護しか受けられないという不都合があるとの批判が可能である。
          6:
          7:
          8:
      13:
        questions: 学生A，B及びCは，次の【事例】における窃盗罪の実行の着手時期について，後記【会話】のとおり議論している。【会話】中の①から⑥までの（）内から適切なものを選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。（解答欄は，[№23]）【事例】甲は，X宅のタンスに宝石が保管されていることを知ったため，その宝石を窃取する目的で，X宅に玄関から侵入し，宝石が保管されているタンスの在りかを探し始めて，それが置かれていた居間に立ち入ろうとしたところ，居間から出てきたXと鉢合わせとなり，取り押さえられた。【会話】学生A．私は，甲がX宅に侵入した時点で窃盗罪の実行の着手を認めてよいと思います。この時点で，①（a．犯意の飛躍的表動があった・b．法益侵害の危険が飛躍的に高まった）といえるからです。学生B．A君は，犯罪を行為者の危険な性格の発現であると考えているのですね。私は，実行の着手の「実行」とは構成要件該当行為のことで，「着手」とはそれを開始することだと解するので，【事例】では，窃盗罪の実行の着手は，②（c．認められない・d．居間に立ち入ろうとした時点で認められる）と考えます。学生A．B君の見解に対しては，実行の着手時期が③（e．不明確になる・f．遅くなり過ぎる）との批判がありますね。学生C．私は，実行の着手時期とは，未遂犯の成立時期のことであるので，未遂犯の処罰根拠に遡り，実質的に考えることが必要だと思います。そのため，窃盗罪の実行の着手時期は，④（g．占有侵害の現実的危険性が発生した・h．窃取行為と密接に関連する行為を開始した）時点だと解するので，【事例】では，窃盗罪の実行の着手は，⑤（i．認められない・j．X宅内でタンスの在りかを探し始めた時点で認められる）と考えます。この点，B君の見解を修正し，実行の着手時期を⑥（k．占有侵害の現実的危険性が発生した・l．窃取行為と密接に関連する行為を開始した）時点とする見解もありますが，この見解に対しては，形式面を重視すると言いながら，結局，実質的な観点を取り入れているとの批判があります。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a⑥k
          2: 2．②c④h
          3: 3．②d⑤i
          4: 4．③f⑥l
          5: 5．④g⑤j
          6:
          7:
          8:
      14:
        questions: 学生A，B及びCは，次の各【事例】を題材にして，後記【会話】のとおり議論している。【会話】中の①から⑧までの（）内から適切な語句を選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。【事例】Ⅰ．店員甲は，自己の担当する売場の商品を勤務時間中にこっそり持ち出して，後日転売した。Ⅱ．店員甲は，店長乙に言われて，店の売掛金を集金したが，これを持ち逃げした。Ⅲ．甲は，パーティーで使うために友人乙から借りたネックレスを，無断で質入れした。Ⅳ．甲は，登記名義を有する所有者乙から自己使用を条件に借りた土地を，しばらく自己使用した後，無断で丙に賃貸して利益を得た。【会話】学生A．事例Ⅰにおいて，甲にはどのような財産犯が成立するだろうか。学生B．店の商品であれば，①（a．店長・b．店員）が占有しているといえるから，②（a．横領罪・b．窃盗罪）が成立すると思う。学生C．反対だ。占有は，③（a．店長・b．店員）にあると認めるべきだから，④（a．横領罪・b．窃盗罪）が成立すると考える。学生B．事例Ⅱにおいて，Cさんの見解によれば，甲に（④）は成立するのか。学生C．成立すると考える。学生A．その結論は，事例Ⅱにおける判例の立場と一致しない。では，Cさんは，事例Ⅲにおいても，甲に（④）が成立すると考えるのか。学生C．いや，成立しないと考える。物を人から借りている場合は別だ。学生B．そうだとすると，Cさんは，事例Ⅳにおいて，甲には，どのような財産犯が成立すると考えるのか。学生C．土地のような不動産の場合，動産とは異なり，その占有は，⑤（a．登記名義を有する者・b．現実に不動産を占有・使用する者）にあると認めるべきだと思うから，土地に対する占有の程度・態様が著しく変更された場合，甲には⑥（a．横領罪・b．不動産侵奪罪）が成立する可能性があると考える。学生A．そうだろうか。⑦（a．横領罪にいう「横領」・b．不動産侵奪罪にいう「侵奪」）があったとはいえないのではないか。むしろ，Cさんの見解によれば，⑧（a．背任罪・b．横領罪）の成否を検討すべきだと思う。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②b③b④a⑤a⑥b⑦b⑧a
          2: 2．①a②b③b④a⑤b⑥a⑦a⑧b
          3: 3．①b②a③a④b⑤a⑥b⑦b⑧a
          4: 4．①b②a③a④b⑤a⑥b⑦b⑧b
          5: 5．①b②a③a④b⑤b⑥a⑦a⑧b
          6:
          7:
          8:
      15:
        questions: 正当防衛に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，［№2，［№26］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．当然又はほとんど確実に侵害が予期された場合において，単に予期された侵害を避けなかったにとどまらず，その機会を利用して積極的に相手方に対し加害行為をする意思で暴行に及んだときは，その暴行行為については，正当防衛が成立する余地はない。
          2: 2．いわゆるけんか闘争において相手方に対してした暴行行為については，正当防衛が成立する余地はない。
          3: 3．手拳で殴る素振りをしながら「お前殴られたいのか。」と言って近付いてきた相手方を，殺傷能力のある刃物を構えて脅した場合，その脅迫行為については，正当防衛が成立する余地はない。
          4: 4．自己に対しナイフを示して脅している相手方に対し専ら攻撃の意思で暴行に及んだ場合，その暴行行為については，正当防衛が成立する余地はない。
          5: 5．財産的権利を防衛するために相手方の身体に暴行を加えて傷害を負わせた場合，その暴行行為については，正当防衛が成立する余地はない。
          6:
          7:
          8:
      16:
        questions: 次のアからオまでの各【記述】を判例の立場に従って検討した場合，後記の各【結論】との組合せとして正しいものは，後記1から5までのうちどれか。なお，【結論】の詐欺罪には詐欺未遂罪も含むものとする。（解答欄は，[№27]）【記述】
        answer:
          a: ア．他人のためにその事務を処理する者が，任務に背いて，その他人を欺く行為をし，同人を錯誤に陥らせて財物を交付させた。
          i: イ．他人を恐喝するに際して，脅迫文言の中に虚偽の部分があり，それも同人に畏怖の念を生じさせる一材料となって，その畏怖の結果として，同人に財物を交付させた。
          u: ウ．新聞販売店から集金業務を委託されている集金員が，集金した購読料を同店に持ち帰らずに自己の用途に費消するつもりであるのに，これを秘して，正規の手続や方式に従って購読者から購読料を集金し，自己の遊興費に費消した。
          e: エ．保険金を詐取する目的で，火災保険の付された自己所有の家屋に放火した。
          o: オ．他人に売買代金として偽造通貨を行使し，同人を錯誤に陥らせて財物を交付させた。【結論】Ⅰ．詐欺罪のみが成立し得る。Ⅱ．詐欺罪と他の罪の双方が成立し得る。Ⅲ．詐欺罪は成立しない。
        additional_answer:
          1: 1．アⅠ－イⅡ
          2: 2．アⅡ－ウⅢ
          3: 3．イⅢ－エⅢ
          4: 4．ウⅡ－オⅡ
          5: 5．エⅡ－オⅢ
          6:
          7:
          8:
      17:
        questions: 過失犯に関する次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．刑法第38条第1項ただし書の「法律に特別の規定がある場合」とは，過失犯を処罰する旨の明文の規定がある場合に限られない。［№28］
          i: イ．公務員が法令により付与された権限を行使するか否かについて，当該公務員に裁量が認められている場合，その権限の不行使を注意義務違反とする過失犯が成立することはない。［№29］
          u: ウ．行政取締法規の義務は，過失犯の注意義務にもなるため，行政取締法規の義務を遵守する限り，他に慣習等から導かれる義務を遵守せずとも，過失犯が成立することはない。［№30］
          e: エ．過失犯が成立するには，因果経過の予見可能性を要するため，現実の結果発生に至る経過を逐一具体的に予見できなければ，過失犯が成立することはない。［№31］
          o: オ．業務上過失致死傷罪の「業務」とは，人が社会生活上の地位に基づき反復継続して行う行為であって，かつ，その行為が他人の生命身体等に危害を加えるおそれのあるものをいうため，他人の生命身体の危険を防止することを義務内容とする業務は，これに含まれない。［№32］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      18:
        questions: 司法作用に対する罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．証人等威迫罪は，判決確定前であれば，その事件で証人として証言を終えた者を威迫した場合でも，成立する。
          2: 2．証人等威迫罪は，公判の結果に何らかの影響を及ぼそうとする意図がなければ，成立しない。
          3: 3．偽証罪は，証人がした虚偽の陳述が裁判の結果に影響しないのであれば，成立しない。
          4: 4．偽証罪は，証人が殊更記憶に反する陳述をした場合でも，陳述内容が真実であれば，成立しない。
          5: 5．虚偽告訴罪は，告訴の内容が客観的真実に合致していた場合でも，申告者が虚偽であると認識していれば，成立する。
          6:
          7:
          8:
      19:
        questions: 身分犯の共犯に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものを2個選びなさい。（解答欄は，［№3，［№35］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．刑法第65条の身分には一時的な心理状態は含まれないので，目的犯に当たる犯罪行為を，当該目的を有する者と有しない者が共同して行った場合，同条の適用の余地はない。
          2: 2．刑法第65条第2項は加減的身分のない者が当該身分のある者に加功した場合について規定するものであるので，賭博の常習性を有する者が有しない者に賭博を教唆した場合，同項の適用の余地はない。
          3: 3．非占有者が業務上の占有者による横領行為に加功した場合，当該非占有者には，刑法第65条第1項の適用により業務上横領罪の共犯が成立し，同条第2項の適用により単純横領罪の刑が科される。
          4: 4．刑法第65条の身分は，一定の犯罪行為に関する犯人の人的関係である特殊の地位又は状態の全てを指称するものであるので，責任能力のある者が刑事未成年者を教唆して犯罪を行わせた場合，同条が適用される。
          5: 5．自首による刑の減免は一身的な事由であるので，共犯者のうち一人に自首が成立する場合，刑法第65条第1項の適用はなく，その減免の効果は自首した者以外には及ばない。
          6:
          7:
          8:
      20:
        questions: 次の【事例】に関する後記アからオまでの各【記述】を判例の立場に従って検討した場合，誤っているものの個数を後記1から5までの中から選びなさい。（解答欄は，[№36]）【事例】甲は，友人乙から，借金の返済に窮している旨の相談をされ，乙に対し，「実家に親父の高級腕時計がある。それを盗んで売りさばけば金になる。」と提案し，甲と別居する甲の実父V方からV所有の腕時計を盗むことを唆した。乙は，甲の提案を受け，V方に窃盗に入ることとしたが，仮に，窃盗を行う際にVらに見付かって逮捕されそうになった場合には，Vらをナイフで脅してこれを抑圧し，逃走しようと考えた。乙は，某日午後0時頃，前記の意図でナイフを購入し，それを携帯してV方に向かい，同日午後1時頃，腕時計を盗む目的で，V方に窓から侵入した上，寝室でV所有の腕時計（時価100万円相当）を窃取した。乙は，その後間もなく，V方玄関ドアの施錠を外して戸外に出て，誰からも発見，追跡されることなく，V方から約1キロメートル離れた公園まで逃げた。乙は，同所において，やはり現金も欲しいと考え，再度V方に窃盗に入ることを決意し，V方に戻り，同日午後1時30分頃，V方玄関内に入ったところ，その直後に帰宅してきたVと鉢合わせとなったことから，逮捕を免れるため，前記ナイフをVの面前に示し，Vが恐怖の余り身動きできないうちに逃走した。乙は，翌日，甲に前記腕時計の売却を依頼した。甲は，同腕時計の売却先を探し，知人丙に対し，その買取りを申し向けたところ，丙が80万円で購入する旨答えたことから，同腕時計を丙に売却した。甲は，丙から同腕時計の売却代金として80万円を受け取ったが，その後，これを自己のものにしようと考え，乙に無断で，その全額を遊興費として費消した。【記述】
        answer:
          a: ア．乙が某日午後0時頃に購入したナイフを携帯してV方に向かったことについては，「強盗の罪を犯す目的」が認められないので，乙に強盗予備罪は成立しない。
          i: イ．乙がVをナイフで脅迫したことについては，腕時計の窃取行為との時間的・場所的な近接性に照らせば，窃盗の機会の継続中に行われたものといえるため，乙に事後強盗罪が成立する。
          u: ウ．甲が乙に腕時計の窃盗を唆したことと，その売却をあっせんしたことは，原因と結果の関係に立つので，窃盗教唆罪と盗品等有償処分あっせん罪は牽連犯となる。
          e: エ．Vの直系血族である甲には盗品等に関する罪について親族等の間の犯罪に関する特例が適用されるため，盗品等有償処分あっせん罪について，甲はその刑を免除される。
          o: オ．甲が腕時計の売却代金を費消したことについては，同腕時計の窃盗犯人である乙は甲に対してその代金の引渡しを請求する権利がないので，甲に委託物横領罪は成立しない。
        additional_answer:
          1: 1．1個
          2: 2．2個
          3: 3．3個
          4: 4．4個
          5: 5．5個
          6:
          7:
          8:
