---
ja:
  keiho:
    2016:
      1:
        questions: ''
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②b③a④a⑤b
          2: 2．①a②a③b④a⑤b
          3: 3．①b②a③a④b⑤b
          4: 4．①b②b③a④b⑤a
          5: 5．①b②b③b④a⑤a
          6:
          7:
          8:
      2:
        questions: 次のアからオまでの各記述を判例の立場に従って検討し，甲に横領罪が成立する場合には1を，成立しない場合には2を選びなさい。
        answer:
          a: ア．甲は，自己が所有する不動産を乙に売却したが，乙への所有権移転登記が完了する前に，同不動産を丙に売却し，丙への所有権移転登記を完了した。[№2]
          i: イ．甲は，所有権留保の約定付き割賦売買契約に基づき24回の月賦払いで，自動車販売会社から自動車を購入し，同自動車の引渡しを受けたが，3回分を支払った時点で，自己の借金の担保として，同自動車を金融業者に提供した。[№3]
          u: ウ．甲は，乙から盗品を売却するよう依頼され，同盗品を丙に売却したが，その売却代金を着服した。[№4]
          e: エ．甲は，自己が所有する不動産を乙に売却したが，乙への所有権移転登記が完了する前に，丙との間で金銭消費貸借契約を締結した事実及びその担保として同不動産に係る抵当権設定契約を締結した事実がないにもかかわらず，同不動産について，丙を権利者とする不実の抵当権設定仮登記を完了した。[№5]
          o: オ．甲は，自己が所有する不動産について，乙を権利者とする抵当権を設定したが，その抵当権設定登記が完了する前に，同不動産について，丙を権利者とする抵当権を設定し，その抵当権設定登記を完了した。[№6]
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      3:
        questions: 次の【事例】に関する後記1から5までの各記述のうち，甲に窃盗罪の従犯の成立を肯定する論拠となり得ないものはどれか。【事例】甲は，乙又は乙の友人が窃盗罪を犯そうとしていることを知り，その手助けのため，乙に対し，同罪の遂行に必要な道具を貸したところ，さらに，乙はその道具を友人丙に貸し，丙がこれを用いて同罪を犯した。なお，丙には同罪の正犯が成立し，乙にはその従犯が成立するものとする。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．従犯には独立した犯罪性が認められる。
          2: 2．従犯の幇助には，教唆者を教唆した者については正犯の刑を科すとする刑法第61条第2項のような規定がない。
          3: 3．共犯は修正された構成要件に該当する行為であるところ，従犯もその構成要件においては「正犯」となる。
          4: 4．幇助は正犯を容易にすることであるという定義からすると，幇助行為が直接的になされたか，間接的になされたかは必ずしも問われない。
          5: 5．教唆犯に対する幇助行為は従犯として処罰される。
          6:
          7:
          8:
      4:
        questions: 文書偽造の罪に関する次のアからオまでの各記述を判例の立場に従って検討した場合，Xに（）内の罪が成立しないものの組合せとして正しいものは，後記1から5までのうちどれか。
        answer:
          a: ア．医師Xは，Yに依頼され，Yが保険会社に提出するために虚偽の病名を記載した診断書を作成した。（虚偽診断書作成罪）
          i: イ．Xは，自動車運転免許の効力停止中に自動車を運転し，速度違反の取締りを受けた際，警察官に対し，あらかじめYから名義使用の承諾を受けていたことから，Yの氏名を名乗り，交通事件原票の供述者欄にY名義で署名押印した。（有印私文書偽造罪）
          u: ウ．Yの代理人でないXは，Yに無断で，行使の目的をもって，金銭消費貸借契約書用紙に「Y代理人X」と記載し，その横に「X」と刻した印鑑を押すなどして，Yを債務者とする金銭消費貸借契約書を作成した。（有印私文書偽造罪）
          e: エ．Xは，身分証明書として使おうと考え，A県公安委員会が発行したYの自動車運転免許証の写真をXの写真に貼り替えた。（有印公文書偽造罪）
          o: オ．Xは，Yの所有する不動産を勝手に売却しようと考え，Yに無断で，行使の目的をもって，不動産の売買契約書用紙に売主として「Y」と記載するなどして，同不動産の売買契約書を作成したが，「Y」と刻した印鑑は押さなかった。（無印私文書偽造罪）
        additional_answer:
          1: 1．アウ
          2: 2．アオ
          3: 3．イウ
          4: 4．イエ
          5: 5．エオ
          6:
          7:
          8:
      5:
        questions: 因果関係に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，［№9，［№10］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲が，殺害目的でVの首を両手で絞め，失神してぐったりとしたVを死んだものと誤解し，死体を隠すつもりでVを雪山に運んで放置したところ，Vは意識を回復しないまま凍死した。甲がVの首を両手で絞めた行為とVの死亡との間には，因果関係がない。
          2: 2．甲が，心臓発作を起こしやすい持病を持ったVを突き飛ばして尻餅をつくように路上に転倒させたところ，Vはその転倒のショックで心臓発作を起こして死亡した。Vにその持病があることを甲が知り得なかった場合でも，甲がVを突き飛ばして路上に転倒させた行為とVの死亡との間には，因果関係がある。
          3: 3．甲は，Vの頸部を包丁で刺し，Vは，同刺創に基づく血液循環障害による脳機能障害により死亡した。その死亡するまでの経過は，Vは，受傷後，病院で緊急手術を受けて一命をとりとめ，引き続き安静な状態で治療を継続すれば数週間で退院することが可能であったものの，安静にすることなく病室内を歩き回ったため治療の効果が上がらず，同脳機能障害により死亡したというものであった。この場合でも，甲がVの頸部を包丁で刺した行為とVの死亡との間には，因果関係がある。
          4: 4．甲は，深夜，市街地にある道幅の狭い車道上に無灯火のまま駐車していた普通乗用自動車の後部トランクにVを閉じ込めて監禁したが，数分後，たまたま普通乗用自動車で通り掛かった乙が居眠り運転をして同車を甲の普通乗用自動車の後部トランクに衝突させ，Vは全身打撲の傷害を負い死亡した。甲がVをトランクに監禁した行為とVの死亡との間には，因果関係がない。
          5: 5．甲は，ホテルの一室で未成年者Vに求められてその腕に覚せい剤を注射したところ，その場でVが錯乱状態に陥った。甲は，覚せい剤を注射した事実の発覚を恐れ，そのままVを放置して逃走し，Vは覚せい剤中毒により死亡した。Vが錯乱状態に陥った時点で甲がVに適切な治療を受けさせることによりVを救命できた可能性が僅かでもあれば，甲がVを放置した行為とVの死亡との間には，因果関係がある。
          6:
          7:
          8:
      6:
        questions: 住居を侵す罪に関する次のアからオまでの各記述を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからオの順に[№11]から[№15]）
        answer:
          a: ア．強盗の意図を隠してA方の玄関前で「こんばんは。」と言ったところ，来客と勘違いしたAから「どうぞお入りください。」と言われてA方住居に立ち入った場合，住居侵入罪が成立する。[№11]
          i: イ．建造物への立入りが平穏な態様で行われた場合には，管理権者があらかじめ立入り拒否の意思を積極的に明示していない限り，建造物侵入罪が成立することはない。[№12]
          u: ウ．平穏を害する態様での住居への立入りであっても，住居権者の同意に基づくものである場合には，住居侵入罪の構成要件には該当するが，違法性が阻却される。[№13]
          e: エ．現金自動預払機が設置されている銀行支店出張所は，一般の利用客の立入りが許容されている場所であるので，同機を利用する客のキャッシュカードの暗証番号等を盗撮する目的で立ち入っても，平穏な態様での立入りであれば，建造物侵入罪が成立することはない。[№14]
          o: オ．住居権者の意思に反して住居に立ち入った上，その後，退去を求められたにもかかわらず数日間にわたってその住居に滞留した場合には，住居侵入罪だけでなく，不退去罪も成立する。[№15]
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      7:
        questions: 罪数に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，偽造された1万円札を使って価格1万円の商品をだまし取ろうと考え，事情を知らない商店の店員Aに対し，同商品の購入を申し込み，代金として同1万円札を渡して，Aから同商品の交付を受けた。甲には，詐欺罪と偽造通貨行使罪が成立し，これらは観念的競合となる。
          2: 2．甲は，Aを監禁するために逮捕し，それに引き続きAを監禁した。甲には，逮捕罪と監禁罪が成立し，これらは牽連犯となる。
          3: 3．甲及び乙は，共同でAの身体に危害を加える目的で，凶器として用いる鉄パイプをそれぞれ準備して集合し，その後，その目的を遂げるため，鉄パイプで代わる代わるAの身体を殴打して傷害を負わせた。甲には，凶器準備集合罪と傷害罪が成立し，これらは牽連犯となる。
          4: 4．甲は，Aを監禁してAから金品を喝取しようと考え，Aをビルの一室に閉じ込めて監禁し，その上で，同室内において，監禁により畏怖していたAに対し，金品の交付を要求しながら脅迫して畏怖させ，Aから金品を脅し取った。甲には，監禁罪と恐喝罪が成立し，これらは牽連犯となる。
          5: 5．甲は，AがB銀行に預け入れていた預金を不正に払い戻して金銭を得る目的で，Aから，B銀行が発行したA名義の預金通帳を窃取した上，B銀行の窓口において，行員に対し，Aに成り済まして，同預金通帳を使って預金を不正に払い戻して金銭を得た。甲には，窃盗罪と詐欺罪が成立し，これらは併合罪となる。
          6:
          7:
          8:
      8:
        questions: わいせつの罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，人通りの多い駅構内において，自己の性器を露出させたが，実際には，それに気付いた人はいなかった。この場合，甲には公然わいせつ罪は成立しない。
          2: 2．甲は，日本国外で販売する目的で，日本国内において，わいせつな映像が録画されたDVDを所持した。この場合，甲にはわいせつ物有償頒布目的所持罪は成立しない。
          3: 3．甲は，友人乙からの土産に対するお礼として，わいせつな映像が録画されたDVD1枚を乙にプレゼントした。この場合，甲にはわいせつ物頒布罪は成立しない。
          4: 4．甲は，不特定多数の通行人を勧誘して5名の客を集めた上，自宅であるマンションの一室において，外部との出入りを完全に遮断した状態で，わいせつな映像が録画されたDVDを再生し，その5名の客に有料で見せた。この場合，甲にはわいせつ物公然陳列罪が成立する。
          5: 5．甲は，海水浴場において，不特定多数の者の面前で，乙女の衣服を全てはぎ取るなどして強いてわいせつな行為をした。この場合，甲には，強制わいせつ罪が成立するのみならず，公然わいせつ罪も成立する。
          6:
          7:
          8:
      9:
        questions: 正当防衛及び緊急避難に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．国家的法益を防衛するための正当防衛が成立する余地はない。
          2: 2．相手方から急迫不正の侵害を受け，第三者の所有物を用いて相手方に反撃し，同所有物を損壊した場合において，その行為が器物損壊罪の構成要件に該当するとき，その行為につき緊急避難が成立する余地はない。
          3: 3．相手方から急迫不正の侵害を受け，これに逆上して相手方に反撃を加えた場合，正当防衛が成立する余地はない。
          4: 4．相手方から急迫不正の侵害を受け，相手方に反撃を加えた場合，その侵害が相手方の過失に基づくものであれば，正当防衛が成立する余地はない。
          5: 5．正当防衛が成立する行為に対しては，正当防衛が成立する余地はない。
          6:
          7:
          8:
      10:
        questions: 公務執行妨害罪に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．窃盗犯人甲は，その窃盗行為を目撃した警ら中の制服警察官乙からその窃盗の機会に現行犯逮捕されそうになり，逮捕を免れるため，乙に対して，その反抗を抑圧するに足りる程度の暴行を加えて抵抗し，そのまま逃走した。甲には事後強盗罪が成立し，これに公務執行妨害罪は吸収されるから，同罪は成立しない。
          2: 2．甲は，税務署の職員乙が甲宅において税務調査をしていたところ，乙の近くでその調査を補助していた民間人である丙に対し，「殺すぞ。」などと危害を加える旨申し向け，これにより乙の職務の執行を一時中断させた。甲は乙を直接脅迫したものではないから，甲には公務執行妨害罪は成立しない。
          3: 3．甲は，制服警察官乙から職務質問を受けている丙の右手をつかんで引っ張り，その場から一緒に走って逃走したところ，これを追い掛けた乙が，走りながら，丙の肩をつかもうとして手を伸ばしたが，その肩をつかめずにバランスを崩して路上に転倒した。甲の丙に対する行為は乙に対する暴行とはいえないから，甲には公務執行妨害罪は成立しない。
          4: 4．甲は，警ら中の制服警察官乙が職務質問をしようとしてきたことから，これを免れるため，乙の職務質問開始前に乙に暴行を加え，乙がひるんだ隙に逃走した。乙が職務質問を開始する前に暴行を加えたにすぎないから，甲には公務執行妨害罪は成立しない。
          5: 5．甲は，制服警察官乙から丙が職務質問を受けているのを見て，これをやめさせようと拳大の石塊を乙に向けて投げ，その臀部に命中させたが，乙が職務質問を中断することはなかった。現実に乙の職務の執行を妨害するに至っていないから，甲には公務執行妨害罪は成立しない。
          6:
          7:
          8:
      11:
        questions: 過失犯に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．監督過失とは,直接行為者が過失を犯さないように監督する注意義務に違反する過失をいう｡監督過失を認めるには，直接行為者に構成要件的結果が発生することの予見可能性があれば足り，直接行為者を監督すべき立場にある監督者には，構成要件的結果が発生することの予見可能性までは必要とされない。
          2: 2．重過失とは，注意義務違反の程度が著しく，それによって発生した構成要件的結果が重大なものをいう。
          3: 3．信頼の原則は，交通事故の過失犯だけに適用されるものであり，それ以外の過失犯に適用される余地はない。
          4: 4．注意義務に違反して人を負傷させた場合であっても，相手方に重大な過失があったときには,過失相殺が適用されるので，過失の責任を免れることができる。
          5: 5．過失犯の成立に必要な注意義務は，必ずしも法令上の根拠があることを要しない。
          6:
          7:
          8:
      12:
        questions: 次のアからエまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。］
        answer:
          a: ア．Aの知人Bは，料理が趣味であり，自宅のパソコンに料理のレシピのデータを保存していた。Aは，Bと口論をした際，Bが大事にしている同データを壊してやろうと思い，同パソコンをたたき壊した。同パソコンを壊したAの行為について，電子計算機損壊等業務妨害罪は成立せず，器物損壊罪が成立する。
          i: イ．Aは，Bに成り済まし，銀行の窓口行員Cに対し，B名義の口座の預金をA名義の口座に振込入金するよう依頼した。Cは，AをBと思い込み，コンピュータの端末を操作して，同銀行が業務用に使用している電子計算機にアクセスし，前記依頼のとおり振込入金の処理をした。Bに成り済まし，Cに振込入金の処理を行わせたAの行為について，電子計算機使用詐欺罪が成立する。
          u: ウ．Aは，盗んだ財布の中に，不正に作られた電磁的記録をその構成部分とするクレジットカードが入っていることに気付き，同カードを使用するつもりはなかったが，機会があれば友人に見せようと考え，同カードを自己の財布に入れて持ち歩いていた。同カードを持っていたAの行為について，不正電磁的記録カード所持罪は成立しない。
          e: エ．Aは，同僚Bのパソコンに，コンピュータウイルスを感染させてBの業務を妨害しようと考え，コンピュータウイルスを作成したが，自宅のパソコンでその効果を試したところ，市販のウイルス対策ソフトで検出されてしまうことが分かったため，同ウイルスを使用することは断念した。同ウイルスを作成して試した一連のAの行為について，電子計算機損壊等業務妨害罪の未遂罪が成立する。
          o:
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．アエ
          4: 4．イエ
          5: 5．ウエ
          6:
          7:
          8:
      13:
        questions: 次のアからオまでの各記述における甲の罪責について，判例の立場に従って検討し，（）内の犯罪が既遂になる場合には1を，未遂にとどまる場合には2を，既遂にも未遂にもならない場合には3を選びなさい。（解答欄は，アからオの順に[№22]から[№）6］
        answer:
          a: ア．甲は，所持金がなかったことから代金を支払わずに食事をしようと考え，飲食店に行って料理を注文し，これを食べた後，代金を請求した店員に対し，財布を忘れたので自宅に取りに帰ると嘘を言ったが，店員にその嘘を見破られた。（詐欺罪）[№22]
          i: イ．甲は，Aを殺害しようと考え，Bから致死性の毒薬であると告げられて小瓶入りの液体を購入し，コーヒーに同液体を入れて，これをAに飲ませたものの，同液体は水であったため，Aは死亡しなかった。（殺人罪）[№23]
          u: ウ．甲は，Aと同居している自宅を燃やそうと考え，自宅の和室に新聞紙が入った段ボール箱を置き，同新聞紙にライターで点火したが，その直後に帰宅したAが燃えている同段ボール箱を発見して消火したため，同段ボール箱の直下の畳だけが焼損した。（現住建造物等放火罪）[№24]
          e: エ．甲は，駅のホームのベンチで寝ているAの隣に座ったところ，Aのズボンのポケットに財布が入っていることに気付き，これを盗もうと考え，手を差し伸べて同ポケットの外側に触れたが，駅員が近付いてきたので，財布に触れることはできなかった。（窃盗罪）[№25]
          o: オ．甲は，交通事故を装って保険会社から保険金をだまし取ろうと考え，Aに依頼して，甲運転の自動車にA運転の自動車を衝突させ，警察官に交通事故を申告したが，Aが警察官から追及されて偽装事故であると認めたため，保険金を請求しなかった。（詐欺罪）[№26]
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      14:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，Aの太ももを蹴って怪我をさせたが，甲には，Aに傷害を負わせるまでの意思はなかった。甲には傷害罪は成立しない。
          2: 2．甲，乙及び丙が，互いに意思の連絡をすることなく，同一の機会にそれぞれAに暴行を加えて怪我をさせたところ，その怪我は，乙又は丙いずれかの暴行によるものであり，甲の暴行によるものではなかった。Aがその怪我により死亡した場合，乙及び丙には傷害致死罪が成立し，甲には傷害罪が成立する。
          3: 3．甲は，四畳半の室内で，Aを脅す目的で，さやから抜いた日本刀をその面前で数回振り回したところ，誤ってその日本刀の刃先がAの腕に当たり，Aに怪我を負わせた。甲には傷害罪は成立しない。
          4: 4．甲は，路上でトラブルとなったAの顔面を1回殴ったところ，Aは，その暴行によりバランスを崩し，足下にあった石につまずいて路上に転倒し，頭部を強く打ち付けて怪我をし，これにより数時間後に死亡した。甲がAの死亡の結果を全く予見していなかった場合でも，甲には傷害致死罪が成立する。
          5: 5．甲は，Aら数名が殴り合いのけんかをしているところにたまたま通り掛かり,｢もっとやれ｡｣と言ってはやし立てた。Aらけんかの当事者が怪我をせず，Aらの暴行が互いの相手に対する暴行罪にとどまる場合でも，甲には現場助勢罪（刑法第206条）が成立する。
          6:
          7:
          8:
      15:
        questions: 学生A，B及びCは，事実の錯誤に関して，次の【会話】のとおり検討している。【会話】中の①から⑪までの（）内から適切な語句を選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。］【会話】学生A．Xが甲を狙って殺人の故意で拳銃を発射し，甲にかすり傷を負わせ，さらに，その弾丸が偶然に乙に命中して乙を死亡させた事例について考えてみよう。私は，同一の構成要件の範囲内であれば，故意を阻却しないと考え，故意の個数については，①（a．故意の個数を問題としない・b．故意の個数を問題とし一個の故意を認める）立場を採ります。ですから，私は，事例の場合，故意犯としては乙に対する殺人既遂罪のみが成立すると考えます。学生B．私は，基本的にはA君と同じ立場ですが，故意の個数について，②（c．故意の個数を問題としない・d．故意の個数を問題とし一個の故意を認める）立場に立ちます。A君の考えだと，③（e．意図した・f．意図しない）複数の客体に既遂の結果が発生した場合，いずれの客体に故意犯を認めるのか不明だからです。学生C．B君の立場は，④（g．罪刑法定主義・h．責任主義）に反することになりませんか。私は，この原則を尊重し，⑤（i．客体の錯誤・j．方法の錯誤）の場合には故意を認めますが，⑥（k．客体の錯誤・l．方法の錯誤）の場合には故意を認めるべきではないと思います。ですから，私は，事例の場合，乙に対する殺人既遂罪は成立しないと考えます。学生A．でも，C君の立場では，方法の錯誤と客体の錯誤との明確な区別が可能であることが前提となりますね。また，未遂犯や過失犯を処罰する規定の有無によっては，処罰の範囲が不当に⑦（m．狭まる・n．広がる）ことになると思います。一方で，B君の立場では，処断刑が不当に重くなりませんか。学生B．私は，甲に対する罪と乙に対する罪の関係を⑧（o．併合罪・p．観念的競合）と考えますので，処断刑はA君の立場による場合と同一となります。学生A．でも，複数の客体に既遂の結果が発生した場合，⑨（q．意図した・r．意図しない）客体についての⑩（s．故意犯・t．過失犯）を，刑を⑪（u．重くする・v．軽くする）方向で量刑上考慮するとなると，やはり問題ではないでしょうか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①b②c③f④g⑤j⑥k⑦m⑧p⑨q⑩s⑪v
          2: 2．①a②d③e④g⑤j⑥k⑦n⑧o⑨r⑩t⑪v
          3: 3．①b②c③f④h⑤i⑥l⑦m⑧p⑨r⑩s⑪u
          4: 4．①a②d③e④h⑤i⑥l⑦n⑧o⑨q⑩s⑪u
          5: 5．①b②c③f④h⑤i⑥l⑦n⑧p⑨r⑩t⑪u
          6:
          7:
          8:
      16:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，警察官から職務質問をされそうになったのでその場から急いで立ち去ろうと考え，たまたま路上に駐車されていた他人所有の自動車に乗り込み，適当な場所で乗り捨てるつもりで，同自動車を運転してその場から走り去った。この場合，甲には，不法領得の意思が認められ，窃盗罪が成立する。
          2: 2．甲は，タクシーの売上金を奪おうと考えて，乗客を装ってタクシーに乗り込み，行き先を指定して人気のない場所に誘導した上，同所で，乗車料金を請求してきた運転手の首元に鋭利なガラス片を突き付けて売上金を渡すよう要求したが，同運転手から抵抗されて売上金を手に入れることができず，そのままその場から立ち去った。この場合，甲には強盗未遂罪のみが成立する。
          3: 3．甲は，視力回復の効果が全くない飲料について，その効果が絶大で入手困難なものと偽って,信じた客にこれを販売し，その代金として現金の交付を受けたが，その販売価格は適正，妥当なものであった。この場合，甲には詐欺罪は成立しない。
          4: 4．甲は，乙がその同居の親族から盗んできたカメラを，盗品であると知りながら乙から購入した。この場合，乙は，窃盗罪についての刑が免除されることから，甲には盗品等有償譲受け罪は成立しない。
          5: 5．甲は，乙所有の土地について，価格が暴落すると偽って，これを信じた乙との間で，時価の半額で同土地を買い受ける旨の売買契約を締結した。この場合，その売買契約が成立したことのみをもって，甲には詐欺既遂罪が成立する。
          6:
          7:
          8:
      17:
        questions: 次の1から5までの各記述を判例の立場に従って検討し，甲に（）内の罪名の間接正犯が成立しないものを2個選びなさい。（解答欄は，[№30，[№31］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，是非弁別能力を有する12歳の長男乙に対し，強盗の犯行方法を教示し，その際に使う凶器を提供して強盗を実行するよう指示したが，その指示は乙の意思を抑圧するものではなく，乙は，自らの意思により強盗の犯行を決意し，甲から提供された凶器を使って，状況によって臨機応変に対処して強盗を実行した。（強盗罪）
          2: 2．医師ではない甲は，妊婦乙からの依頼を受けて乙への堕胎手術を開始したが，その最中に乙の生命が危険な状態に陥ったため，医師丙に依頼し，胎児を乙の母体外に排出させた。（同意堕胎罪）
          3: 3．公務員ではない甲は，公証人乙に対して虚偽の申立てをし，事情を知らない乙をして，公文書である公正証書の原本に虚偽の記載をさせた。（虚偽公文書作成罪）
          4: 4．甲は，事情を知らない新聞社の従業員乙に依頼して，同社の新聞紙上に，丙に無断で丙名義の事実証明に関する広告文を掲載させた。（私文書偽造罪）
          5: 5．甲は，乙所有の建材を自己の所有物であると偽って，事情を知らない丙に売却し，丙をして,乙の建材置場から当該建材を搬出させた。（窃盗罪）
          6:
          7:
          8:
      18:
        questions: 逃走の罪に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，[№3，[№33］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．勾留状によって拘置所に勾留されていた甲は，面会者から密かに差し入れられた合い鍵を用いて房の扉を開け，拘置所から逃走した。甲には加重逃走罪の既遂罪が成立する。
          2: 2．確定判決によって刑務所に収容されていた甲は，同房に服役中の乙と逃走する旨の相談をしていたところ，ある日，房の扉が施錠されていないことに気付き，房から出て刑務所から逃走したが，乙は思いとどまり，房の外に出なかった。甲には加重逃走罪の既遂罪が成立する。
          3: 3．勾留状によって拘置所に勾留されていた甲は，隣の房に勾留されていた乙に依頼して乙の同房者丙を殴ってもらい，拘置所職員が乙の行動を制止している隙に拘置所から逃走した。甲には加重逃走罪の既遂罪が成立する。
          4: 4．確定判決によってA刑務所に収容されていた甲は，B刑務所への護送中，護送車両から逃走した。甲には単純逃走罪の既遂罪が成立する。
          5: 5．甲は，勾留状によって拘置所に勾留されていた乙を逃走させるため，乙の房の合い鍵を乙に差し入れたが，乙は拘置所から逃走しなかった。甲には逃走援助罪の既遂罪が成立する。
          6:
          7:
          8:
      19:
        questions: 共犯に関する次の1から5までの各記述を判例の立場に従って検討し，誤っているものを2個選びなさい。（解答欄は，[№3，[№35］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲がAの殺害を乙に教唆したところ，乙はAの殺害を丙に教唆し，さらに，丙はAの殺害を丁に教唆し，丁がAを殺害した。甲には，殺人罪の教唆犯が成立する。
          2: 2．乙は，路上で，Aの頭部を殴って転倒させ，Aに脳挫傷の傷害を負わせたが，その直後に駆けつけた甲は，Aが乙の暴行によって倒れて苦しんでいることを知り，Aの抵抗が困難になっている状態を利用してAに暴行を加えようと考え，乙と意思を通じ，代わる代わるAの腹部を蹴り，腹部に打撲傷の傷害を負わせた。甲には，脳挫傷の傷害についても乙との傷害罪の共同正犯が成立する。
          3: 3．甲は，乙からAの殺害計画を打ち明けられ毒薬の入手を依頼されたことから，毒薬を購入して乙に渡したが，乙は，毒薬での殺害計画を変更し，Aを包丁で刺して殺害した。甲には，殺人予備罪の共同正犯が成立する。
          4: 4．甲と乙は，A方に強盗に入ることを計画し，それぞれ包丁を持ってA方に侵入し，Aを包丁で脅した上，室内を物色していたところ，家人B，Cに犯行を目撃され，甲はBに捕まったが，乙は逮捕を免れるためCの腕を包丁で切り付けて傷害を負わせた。甲には，住居侵入罪のほか強盗致傷罪の共同正犯が成立する。
          5: 5．暴力団組員乙は，対立する暴力団組長Aを殺害することを決意し，誰にも犯行の決意を打ち明けることなく，小刀を持ってA方に向かったところ，乙の舎弟である甲は，乙の決意を察し，仮に乙がAから反撃されそうになった場合は，自分がAを殺害しようと考え，乙に何も告げることなく，拳銃を持ってA方付近に先回りして隠れていたが，乙は，玄関先に出てきたAを小刀で一突きして殺害した。甲には，乙の殺人罪の従犯が成立する。
          6:
          7:
          8:
      20:
        questions: 次の【事例】に関する後記アからエまでの各【記述】を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。］【事例】甲は，内縁の妻Aと同居していたところ，遊興費に窮し，A所有のドレス20着及び指輪1個と，A管理のA名義のクレジットカード1枚（その規約上，会員である名義人のみが利用でき，他人への譲渡，貸与等が禁じられ，また，加盟店は，利用者が会員本人であることを善良な管理者の注意義務をもって確認することが定められている。）を，Aの部屋から盗み出した。甲は，丙にドレス及び指輪の売却を仲介してもらおうと考え，これらの盗品を丙方に運ぼうとした。しかし，甲は，ドレスの数が多く一人で運ぶのが困難であったため，乙に対し，ドレスと指輪が盗品であることを話した上で，丙宅への運搬を手伝ってほしいと頼んだ。乙がこれを了解したので，甲及び乙は，指輪とドレスのうち10着を甲が，残りのドレス10着を乙が，それぞれ運転する自動車に載せて丙宅へ運ぶこととし，これらの盗品を丙宅へ運んだ。丙は，ドレス及び指輪を，甲がAから盗んできたものであることを承知した上で甲から預かり，甲からの依頼どおりに売却先を探すこととしたが，指輪についてはAが母親の形見として大切にしていたものであることを知っていたことから，高値でAに売り付けようと考え，後日，Aに対し，代金50万円で指輪を売却し，その売却代金を甲に渡した。また，甲は，Aから盗んだクレジットカードを担保として丁から現金30万円を借りたが，その際，丁に対し，「これはA名義のクレジットカードだけど，Aから使用を許されており，お前がこのカードを利用して買物をしても，その利用代金はAにおいて決済される。」と伝えた。その後，甲が丁に対して金を返さなかったことから，丁は，甲の話を信じ，デパートにおいて，Aに成り済まして同カードを用いて腕時計1個を購入した。【記述】
        answer:
          a: ア．甲がAの指輪を盗んだことにつき，甲の行為は窃盗罪に該当するが，Aは甲の内縁の妻であるから，刑法第244条第1項により刑が免除される。
          i: イ．乙が盗品のドレス10着を，窃盗犯人である甲が指輪とドレス10着を，それぞれ丙宅まで運搬したことにつき，乙は甲と共同してこれら盗品を運搬したのであるから，乙にはドレス20着全てと指輪につき盗品等運搬罪が成立する。
          u: ウ．丙がAを相手方として指輪の売却をあっせんしたことにつき，Aは窃盗の被害者であるが，丙には盗品等処分あっせん罪が成立する。
          e: エ．丁がA名義のクレジットカードで腕時計を購入したことにつき，丁は，Aから同カードの使用を許されており，かつ，自らの使用に係る同カードの利用代金がAにおいて決済されるものと信じていたので，丁に詐欺罪は成立しない。
          o:
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．イウ
          4: 4．イエ
          5: 5．ウエ
          6:
          7:
          8:
