---
ja:
  keiho:
    2015:
      1:
        questions: 次のアからオまでの各記述を判例の立場に従って検討した場合，正しいものの組合せは，後記1から5までのうちどれか。
        answer:
          a: ア．不真正不作為犯の作為義務は，法律上の規定に基づかなければならない。
          i: イ．不真正不作為犯が成立するために，作為可能性を必要としない場合もある。
          u: ウ．不真正不作為犯の因果関係が認められるためには，期待された作為をしていれば結果が発生しなかったことが，合理的な疑いを超える程度に確実であったことが必要である。
          e: エ．不真正不作為犯は，殺人罪や放火罪については成立するが，財産犯については成立しない。
          o: オ．不作為による放火罪が成立するためには，既発の火力を利用する意思は必ずしも必要ではない。
        additional_answer:
          1: 1．アウ
          2: 2．アオ
          3: 3．イウ
          4: 4．ウエ
          5: 5．ウオ
          6:
          7:
          8:
      2:
        questions: 業務妨害罪に関する次の1から5までの各記述を判例の立場に従って検討し，誤っているものを2個選びなさい。（解答欄は，[№2，[№3］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．業務妨害罪における「業務」とは，職業その他社会生活上の地位に基づいて継続して行う事務又は事業をいい，営利を目的とするものでなくても「業務」に含まれる。
          2: 2．業務妨害罪における「業務」は，業務自体が適法なものであることを要するから，行政取締法規に違反した営業行為は「業務」には当たらない。
          3: 3．強制力を行使しない非権力的公務は，公務執行妨害罪における「公務」に当たるとともに業務妨害罪における「業務」にも当たる。
          4: 4．威力業務妨害罪における威力を「用いて」といえるためには，威力が直接現に業務に従事している他人に対してなされることを要する。
          5: 5．業務妨害罪における「妨害」とは，現に業務妨害の結果が発生したことを必要とせず，業務を妨害するに足りる行為があることをもって足りる。
          6:
          7:
          8:
      3:
        questions: 次のアからオまでの各事例を判例の立場に従って検討し，（）内の甲の行為とVの死亡との間に因果関係が認められる場合には1を，認められない場合には2を選びなさい。
        answer:
          a: ア．甲は，自宅に遊びに来た友人Vの態度に腹を立て，その頭部を平手で1回殴打したところ，Vが家から出て行ったので，謝りながらVを追い掛けた。Vは，甲が謝りながら追い掛けてきたことに気付いたが，甲と話をしたくなかったので，甲に追い付かれないように，あえて遮断機が下りていた踏切に入ったところ，列車にひかれ，内臓破裂により死亡した。（甲がVの頭部を平手で1回殴打した行為）［№4］
          i: イ．甲は，マンション4階の甲方居間で，Vの頭部や腹部を木刀で多数回殴打した。Vは，このままでは殺されると思い，甲の隙を見て逃走することを決意し，窓からすぐ隣のマンションのベランダに飛び移ろうとしたが，これに失敗して転落し，脳挫滅により死亡した。（甲がVの頭部や腹部を木刀で多数回殴打した行為）［№5］
          u: ウ．甲は，Vに致死量の毒薬を飲ませたが，その毒薬が効く前に，Vは，事情を知らない乙に出刃包丁で腹部を刺されて失血死した。（甲がVに致死量の毒薬を飲ませた行為）［№6］
          e: エ．甲は，路上でVの頭部を木刀で多数回殴打し，これにより直ちに治療しなければ数時間後には死亡するほどの脳出血を伴う傷害をVに負わせ，倒れたまま動けないVを残して立ち去った。そこへ，たまたま通り掛かった事情を知らない乙が，Vの頭部を1回蹴り付け，Vは，当初の脳出血が悪化し，死期が若干早まって死亡した。（甲がVの頭部を木刀で多数回殴打した行為）［№7］
          o: オ．甲は，面識のないVが電車内で酔って絡んできたため，Vの顔面を拳で1回殴打したところ，もともとVは特殊な病気により脳の組織が脆弱となっており，その1回の殴打で脳の組織が崩壊し，その結果Vが死亡した。（甲がVの顔面を拳で1回殴打した行為）［№8］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      4:
        questions: 偽造公文書の行使に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，［№9，［№10］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．行使の目的なしに作成された偽造公文書は，偽造公文書行使罪の客体とならない。
          2: 2．偽造公文書の内容，形式を口頭で他人に告知するだけでは，偽造公文書行使罪は成立しない。
          3: 3．偽造公文書を相手方に示して錯誤に陥れ，相手方から現金の交付を受けた場合，偽造公文書行使罪は詐欺罪に吸収され，詐欺罪のみが成立する。
          4: 4．交際相手と結婚するために自己に生活能力があることを示そうとして，偽造した国家試験合格証書を当該相手に見せた場合，偽造公文書行使罪が成立する。
          5: 5．自動車を運転する際，警察官から運転免許証の提示を求められれば提示するつもりで偽造した運転免許証を携帯した場合，偽造公文書行使罪が成立する。
          6:
          7:
          8:
      5:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，Xを眠らせてXが左腕に着けていた高級腕時計を外して持ち去ろうと考え，Xに多量の睡眠薬を飲ませたが，Xが眠らなかったため，Xの腕時計に触れることすらできなかった。甲には昏酔強盗未遂罪が成立する。
          2: 2．拘置所に勾留中の甲は，逃走しようと考え，収容されていた房の壁を削り取って穴を開けたが，その穴が脱出可能な程度の大きさになる前に発見されたため，逃走行為に及ばなかった。甲には加重逃走未遂罪が成立する。
          3: 3．甲は，Xから現金を脅し取ろうと考え，「殺されたくなければ100万円をよこせ。」などとXを恐喝する内容の手紙をポストに投かんし，その手紙はX方に配達されたが，手紙を見たXの妻は冗談であると思い，その内容をXに伝えなかった。甲には恐喝未遂罪が成立する。
          4: 4．甲は，X方の居間に置かれた金庫に多額の現金が入れてあることを知り，これを盗む目的で，X方の無施錠のドアから玄関に入ったが，Xにその場で発見されたため，逃走した。甲には窃盗未遂罪が成立する。
          5: 5．甲は，Xに対し，Xの孫を装って電話をかけ，「おじいちゃん。金がなくて困っているので，今から言う俺の口座に100万円を送金して。」と言って現金をだまし取ろうとしたが，その声が孫の声と違うことに気付いたXは，甲から指定された口座に送金しなかった。甲には詐欺未遂罪が成立する。
          6:
          7:
          8:
      6:
        questions: 次の1から5までの各事例における甲のVに対する罪責について，判例の立場に従って検討した場合，甲に殺人罪が成立しないものはどれか。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，Vには自殺がどのようなものかを理解する能力がなく，しかもVが甲の命ずることには何でも服従するのを利用してVを死亡させようと考え，Vに対して，首を吊る方法を教えた上，これを実行するよう命じた。Vは，甲から命じられたとおりに，教えられた方法で自ら首を吊って窒息死した。
          2: 2．甲は，真冬の深夜，河川堤防でVに激しい暴行を加えたところ，Vは走って逃げ出した。甲は，逃げるVを堤防際まで追い詰めれば，逃げ場を失ったVが堤防から下の川に飛び込んで溺死するかもしれないがそれでも構わないと考え，Vを堤防際まで追い詰めた。逃げ場を失ったVは，甲からの暴行を免れるため，堤防から約3メートル下の川に飛び込んで溺死した。
          3: 3．甲は，Vから，包丁で腹部を突き刺して殺してほしいと依頼され，これを真意から出た依頼であると信じて包丁でVの腹部を突き刺したが，その依頼はVの冗談であって，Vの真意から出たものではなかった。Vは，甲から腹部を包丁で刺されたことにより失血死した。
          4: 4．甲は，妻と話し合って一家心中することとし，妻と5歳になる息子Vからそれぞれ一家心中することの承諾を得た上，妻とVを殺すため，同人らの腹部を包丁で刺した。妻とVは，甲から腹部を包丁で刺されたことにより失血死した。
          5: 5．甲は，Vから心中を持ち掛けられたことを利用して，Vを死亡させようと考え，自らは死ぬ気がないのに，Vとの心中を了承した。Vは，甲の真意を知っていれば死ぬことはなかったが，甲も一緒に死んでくれるものと誤信したまま，甲の目の前で，甲が用意した致死量の毒を飲んで中毒死した。
          6:
          7:
          8:
      7:
        questions: 学生Aと学生Bは，次の【事例】における甲の罪責について後記【会話】のとおり検討している。【会話】中の①から⑧までの（）内から適切な語句を選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。（解答欄は，[№13]）【事例】甲は，乙に対し，殺意をもって，拳銃の引き金を引いて銃弾1発を発射し，乙の胸部に命中させて乙を殺害した。甲が拳銃で乙に狙いを付ける直前，乙は，甲に対し，殺意をもって，拳銃で狙いを付けて引き金を引こうとしていたものの，甲が発射した銃弾によって死亡したことから，引き金を引くには至らなかった。なお，甲は，乙が拳銃で自己に狙いを付けていることを知らなかった。【会話】学生A．甲の行為は，殺人罪の構成要件に該当する。そして，正当防衛の成立要件として，防衛の意思が必要であると考えると，甲には①（a．殺人既遂罪が成立し・b．正当防衛が認められ），防衛の意思は不要であると考えると，甲には②（c．殺人既遂罪が成立する・d．正当防衛が認められる）ことになる。学生B．最近では，防衛の意思必要説，不要説のいずれからも，甲には殺人未遂罪が成立し得るという見解が有力に主張されている。防衛の意思必要説からの殺人未遂罪説は，違法性は行為無価値と結果無価値の総合から構成されるという違法二元論を根拠とし，③（e．行為無価値の存在と結果無価値の欠如・f．行為無価値の欠如と結果無価値の存在）を理由に，一方，防衛の意思不要説からの殺人未遂罪説は，④（g．適法・h．違法）な結果が発生する具体的危険があることを理由に，それぞれ殺人未遂罪が成立し得ると説明している。学生A．しかし，防衛の意思不要説からの殺人未遂罪説に対しては，⑤（i．「侵害はよいが侵害を試みることは許されない」・j「侵害を試みることはよいが侵害は許されない」）ことになるとの批判がある。学生B．もともと，防衛の意思不要説からの殺人未遂罪説が問題にしている危険は，⑥（k．別のあり得た違法結果・l．当該結果）を発生させる危険ではなく，⑦（m．別のあり得た違法結果・n．当該結果）を発生させる危険と言われている。だから，その批判は当たらない。学生A．いずれにせよ，殺人未遂罪説は，実際に乙が死亡しているのだから，罪刑法定主義上，問題があると思う。学生B．刑法第43条は，「犯罪の実行に着手してこれを遂げなかった」と規定しており，これを，⑧（o．構成要件的結果・p．構成要件に該当する違法な結果）が発生しなかったという意味に理解すれば，文言解釈としての問題はないと思う。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②d③e④h⑤i⑥k⑦n⑧o
          2: 2．①b②c③e④g⑤j⑥k⑦n⑧p
          3: 3．①b②c③f④g⑤j⑥k⑦n⑧o
          4: 4．①a②d③e④h⑤i⑥l⑦m⑧p
          5: 5．①a②d③f④h⑤j⑥l⑦m⑧p
          6:
          7:
          8:
      8:
        questions: 次のアからオまでの各記述を判例の立場に従って検討した場合，誤っているものの組合せは，後記1から5までのうちどれか。が成立する。
        answer:
          a:
          i:
          u:
          e: エ．女子を強姦する目的で暴行を加えたところ，その暴行によって同人が死亡したため，姦淫するに至らなかった場合，強姦致死罪（刑法第181条第2項）が成立する。
          o: オ．女子に対して準強制わいせつ罪に当たる行為をし，同人に騒がれて捕まりそうになり，わいせつな行為を行う意思を喪失してその場から逃走するため同人に暴行を加えて傷害を負わせた場合，強制わいせつ致傷罪（刑法第181条第1項）は成立せず，準強制わいせつ罪と傷害罪が成立する。
        additional_answer:
          1: 1．アウ
          2: 2．アオ
          3: 3．イウ
          4: 4．イエ
          5: 5．エオ
          6:
          7:
          8:
      9:
        questions: 次の【事例】に関する1から5までの各【記述】を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，[№15]，[№16]順不同）【事例】Aは，外国へ旅行に行った際，旅行先で知り合ったBから，荷物を預けるので手荷物として日本まで運んでほしいと依頼され，これを了承し，その荷物を日本に持ち込んだが，荷物の中身は覚せい剤であった。なお，覚せい剤をみだりに日本に持ち込んだ場合には覚せい剤取締法の輸入罪が成立し，麻薬をみだりに日本に持ち込んだ場合には麻薬及び向精神薬取締法の輸入罪が成立するものとする。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．Aは，Bから預かった荷物の中身は「薬物ではない。」と聞かされていたが，「薬物以外の何か違法なものかもしれない。」と思ってこれを日本に持ち込んだ場合，Aには覚せい剤取締法の輸入罪が成立する。
          2: 2．Aは，Bから預かった荷物の中身は「覚せい剤である。」と思ったものの，覚せい剤を日本に持ち込むことは法律上禁止されていないと考えてこれを日本に持ち込んだ場合，Aには覚せい剤取締法の輸入罪が成立する。
          3: 3．Aは，Bから預かった荷物の中身は「覚せい剤である。」と聞かされたものの，覚せい剤が違法な薬物であることを知らず，「覚せい剤とは高価な化粧品のことである。」と認識してこれを日本に持ち込んだ場合でも，「覚せい剤」という認識がある以上，Aには覚せい剤取締法の輸入罪が成立する。
          4: 4．Aは，Bから預かった荷物の中身は「覚せい剤かもしれないし，もしかしたら麻薬かもしれない。」と思ってこれを日本に持ち込んだ場合，Aには客体の認識に錯誤があり，麻薬及び向精神薬取締法の輸入罪の法定刑が覚せい剤取締法の輸入罪の法定刑よりも軽いときには，Aには麻薬及び向精神薬取締法の輸入罪が成立する。
          5: 5．Aは，Bから預かった荷物の中身は「覚せい剤ではないが，麻薬である。」と思ってこれを日本に持ち込んだ場合，覚せい剤取締法の輸入罪の法定刑と麻薬及び向精神薬取締法の輸入罪の法定刑が同じときには，Aには覚せい剤取締法の輸入罪が成立する。
          6:
          7:
          8:
      10:
        questions: 次の【記述】中の①から⑨までの（）内から適切な語句を選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。【記述】強盗罪における強取とは，相手方の反抗を①（a．困難にする・b．抑圧する）に足りる程度の暴行・脅迫を加え，相手方の②（c．意思に反し・d．瑕疵ある意思に基づき），相手方の占有に属する財物を自己又は第三者の占有に移転することをいう。強取と③（e．窃盗罪における窃取・f．恐喝罪における喝取）との区別は，実行行為としての暴行・脅迫の有無であり，強取と④（g．窃盗罪における窃取・h．恐喝罪における喝取）との区別は，相手方の反抗を①（a．困難にする・b．抑圧する）に足りる程度の暴行・脅迫であるか否か，つまり，暴行・脅迫の程度である。それゆえ，恐喝罪は，⑤（i．委託物横領罪・j．詐欺罪）と同様，相手方の⑥（k．意思に反し・l．瑕疵ある意思に基づき），財物を交付させる犯罪である。そして，強盗罪や⑦（m．窃盗罪・n．恐喝罪）のように，相手方の②（c．意思に反し・d．瑕疵ある意思に基づき），相手方の占有に属する財物を自己又は第三者の占有に移転する犯罪を⑧（o．奪取罪・p．交付罪）と呼び，恐喝罪や⑤（i．委託物横領罪・j．詐欺罪）のように，相手方の⑥（k．意思に反し・l．瑕疵ある意思に基づき），相手方の占有に属する財物を自己又は第三者の占有に移転する犯罪を⑨（q．奪取罪・r．交付罪）と呼んで区別することができる。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②c③e④h⑤j⑥k⑦n⑧p⑨q
          2: 2．①b②c③e④h⑤j⑥l⑦m⑧p⑨q
          3: 3．①a②d③f④g⑤i⑥l⑦n⑧p⑨q
          4: 4．①b②d③f④g⑤i⑥k⑦m⑧o⑨r
          5: 5．①b②c③e④h⑤j⑥l⑦m⑧o⑨r
          6:
          7:
          8:
      11:
        questions: 責任能力に関する次の1から5までの各記述を判例の立場に従って検討した場合，正しいものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．ある人が同じ精神の障害の状態にありながら，ある行為については完全な責任能力が認められ，他の行為については完全な責任能力が認められないことがある。
          2: 2．心神喪失とは，精神の障害により事物の理非善悪を弁識する能力及びその弁識に従って行動する能力のいずれもない状態をいう。
          3: 3．心神喪失は，精神の障害がある場合に限られるから，アルコールによって一時的にそのような状態に陥った場合は心神喪失と認めることはできない。
          4: 4．心神耗弱は，責任能力が著しく減退しているにすぎないから，その刑を減軽しないこともできる。
          5: 5．13歳の少年が人を殺害した場合，少年法の規定に基づく手続を経れば，その少年に刑罰を科すことができる。
          6:
          7:
          8:
      12:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．盗品等無償譲受け罪が成立するためには，無償譲受けについて契約を締結しただけでは足りず，盗品等が現実に移転されることが必要であるが，盗品等有償譲受け罪は，有償譲受けについて契約を締結しただけで成立する。
          2: 2．盗品等の売買をあっせんすれば，あっせん自体が無償であっても，盗品等有償処分あっせん罪が成立する。
          3: 3．盗品等有償譲受け罪の客体に対する故意は，財産罪に当たる行為によって領得された物であることの認識があれば足り，いかなる財産罪に当たるかの認識までは不要である。
          4: 4．盗品等の売買をあっせんすれば，盗品等が現実に移転されなくても，盗品等有償処分あっせん罪が成立する。
          5: 5．盗品等有償譲受け罪の犯人が本犯である窃盗犯人の配偶者である場合，当該盗品等有償譲受け罪の犯人について，その刑は免除される。
          6:
          7:
          8:
      13:
        questions: 教授Xと学生Yは，事後強盗罪の共犯に関する事例について後記【会話】のとおり検討している。【会話】中の①から④までの（）内から適切な語句を選んだ場合，正しいものの組合せは，後記1から5までのうちどれか。（解答欄は，[№20]）【会話】教授X．窃盗犯人甲は，自己を逮捕しようと追い掛けてきた被害者Vに対し，逮捕を免れる目的で，Vの反抗を抑圧する程度の暴行を加えました。甲にはどのような犯罪が成立しますか。学生Y．甲には事後強盗罪が成立します。教授X．それでは，甲がVから追い掛けられている時に，甲の知人乙が，偶然通り掛かり，その状況から甲がVの物を盗んだのだと認識し，甲と意思を通じて，甲の逮捕を免れさせる目的で，Vに対し，Vの反抗を抑圧する程度の暴行を加えた場合，乙の共犯としての罪責はどうなりますか。学生Y．事後強盗罪を真正身分犯と考え，刑法第65条についての判例の立場に立てば，乙には①（a．刑法第65条第1項により事後強盗罪・b．刑法第65条第2項により暴行罪）が成立します。教授X．事後強盗罪を不真正身分犯と考える立場では，乙の共犯としての罪責はどうなりますか。学生Y．事後強盗罪を不真正身分犯と考えた上で，刑法第65条第1項は構成的身分及び加減的身分を通じて，身分犯における共犯の成立の規定であり，同条第2項は加減的身分について刑の個別作用を定めたものと解する立場に立てば，乙には②（c．刑法第65条第1項により事後強盗罪が成立するが，同条第2項により暴行罪の刑を科す・d．刑法第65条第1項と同条第2項の双方を適用して，暴行罪が成立する）ことになります。教授X．事後強盗罪を身分犯と考えない立場では，乙の共犯としての罪責はどうなりますか。学生Y．事後強盗罪を窃盗と暴行の結合犯と考える立場もあります。この立場に立ち，乙に事後強盗罪が成立するという考え方は，乙の承継的共同正犯を③（e．肯定・f．否定）しています。教授X．事後強盗罪を結合犯と考える立場に対しては，どのような批判がありますか。学生Y．④（g．窃盗の既遂・未遂によって事後強盗罪の既遂・未遂が決まることを説明できない・h．窃盗に着手しただけで事後強盗罪の未遂を肯定することになってしまうのではないか）という批判があります。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．①a②d③e④g
          2: 2．①b②d③f④h
          3: 3．①a②c③e④h
          4: 4．①b②d③f④g
          5: 5．①a②c③e④g
          6:
          7:
          8:
      14:
        questions: 証拠隠滅等の罪に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，[№21]，[№22]順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，Aが窃盗被告事件で公判請求されたと知り，同事件に関するAに有利な情状証拠を隠匿した。甲には証拠隠滅罪は成立しない。
          2: 2．甲は，親族Aが犯した傷害被疑事件につき，他人を教唆してAの犯行に関わる証拠を隠滅させた。甲には，親族による犯罪に関する特例（刑法第105条）が適用され，証拠隠滅罪の教唆犯は成立しない。
          3: 3．甲は，Aが犯した殺人被疑事件につき，目撃者Bが捜査機関から事情聴取の要請を受けたことを知り，その聴取を妨害するため，Bを甲方に2か月間監禁した。甲には証拠隠滅罪が成立する。
          4: 4．甲は，Aの強盗被告事件に証人として出廷し，法律により宣誓の上，自己の記憶と異なる偽りの事実を証言し，これに基づく証人尋問調書が作成された。甲には証拠偽造罪が成立する。
          5: 5．甲は，自己が犯した強制わいせつ被疑事件に関する証拠の隠滅をAに教唆して実行させた。甲には証拠隠滅罪の教唆犯が成立する。
          6:
          7:
          8:
      15:
        questions: 結果的加重犯の共同正犯の成立が認められることを前提に，次の【事例】及び各【見解】に関する後記1から5までの各【記述】を検討し，誤っているものを2個選びなさい。（解答欄は，［№2，］［№24］順不同）【事例】甲と乙は，丙に対する傷害を共謀し，共同して木刀で丙の手足を殴打していた際，甲は丙に対する殺意を抱き，木刀で丙の頭部を殴打し，丙はその殴打により脳挫傷で死亡した。なお，乙は，甲が殺意を抱いたことを知らなかった。【見解】A説：共同正犯とは，数人が犯罪に至る行為過程を含めた行為を共同することであり，特定の犯罪を共同して実現する場合はもちろんのこと，単なる行為を共同して各自の意図する犯罪を実現する場合も，それぞれの行為について共同正犯の成立を認める。B説：共同正犯とは，数人の者が共同して特定の犯罪を行うことであり，構成要件の間に重なり合いがあれば，そのうちのより重い犯罪について共同正犯の成立を認め，軽い犯罪の故意しかない者には，軽い犯罪の刑を科す。C説：共同正犯とは，数人の者が共同して特定の犯罪を行うことであり，構成要件の重なり合う限度で軽い犯罪の共同正犯の成立を認める。【記述】
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．A説からは，甲と乙に殺人罪の共同正犯が成立するとの結論が導かれる。
          2: 2．B説からは，甲と乙に殺人罪の共同正犯が成立するとの結論が導かれる。
          3: 3．B説に対しては，犯罪の成立と科刑が分離するのは妥当でないと批判できる。
          4: 4．C説からは，甲と乙に傷害致死罪の共同正犯が成立し，甲には殺人罪の単独犯が成立するとの結論が導かれる。
          5: 5．C説に対しては，A説やB説から，共同正犯の成立範囲が広すぎると批判できる。
          6:
          7:
          8:
      16:
        questions: 事後強盗罪に関する次の1から5までの各記述を判例の立場に従って検討し，正しいものを2個選びなさい。（解答欄は，［№2，［№26］順不同）
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．窃盗既遂犯人のみが事後強盗罪の主体となる。
          2: 2．事後強盗罪は，強盗罪と同様，財物と財産上の利益について成立する。
          3: 3．窃盗犯人が窃盗の現場で逮捕を免れるために暴行・脅迫を加えた相手方が，現に当該窃盗犯人を逮捕する意図を有していなくても，事後強盗罪は成立する。
          4: 4．窃盗犯人が窃盗の現場で逮捕を免れるために相手方を殺害した場合，強盗殺人罪は成立しない。
          5: 5．強盗予備罪の「強盗の罪を犯す目的」には，事後強盗を犯す目的も含まれる。
          6:
          7:
          8:
      17:
        questions: 次の1から5までの各記述を判例の立場に従って検討した場合，誤っているものはどれか。］
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．甲は，酒に酔った状態で，自動車を無免許で運転した。甲には酒酔い運転の罪と無免許運転の罪が成立し，これらは観念的競合となる。
          2: 2．甲及び乙は，対立する暴走族の構成員を襲撃することを共謀し，同構成員であるX，Y及びZに対し，殴る蹴るの暴行を加え，それぞれに傷害を負わせた。甲及び乙にはそれぞれ3個の傷害罪が成立し，これらは併合罪となる。
          3: 3．甲は，乙がX及びYを殺害するつもりでいることを知ったことから，凶器としてナイフ1本を乙に手渡したところ，乙は，同ナイフを用いてX及びYを殺害した。甲には2個の殺人幇助の罪が成立し，これらは併合罪となる。
          4: 4．甲は，離婚した元妻Xを殺害する目的で，深夜，Xの母親Y宅に侵入し，その場にいたX，Y及びYの子Zを順次殺害した。甲には1個の住居侵入罪と3個の殺人罪が成立するが，住居侵入罪と各殺人罪は牽連犯となり，全体が科刑上一罪となる。
          5: 5．甲は，身の代金を得る目的でXを拐取し，更にXを監禁し，その間にXの近親者に対して身の代金を要求した。甲には身の代金目的拐取罪，拐取者身の代金要求罪及び監禁罪が成立し，身の代金目的拐取罪と拐取者身の代金要求罪は牽連犯となり，これらの各罪と監禁罪は併合罪となる。
          6:
          7:
          8:
      18:
        questions: 次の【事例】に関する後記1から5までの甲の罪責を判例の立場に従って検討した場合，甲に（）内の犯罪が成立しないものはどれか。【事例】甲は，A方から高価な壺を盗み出した。Aは，これに気付いて甲を追い掛けたが，甲は，逃げ切って帰宅し，盗んだ上記壺を自宅のテーブルに置いていた。警察官は，甲の本件窃盗事件の捜査を開始した。
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1: 1．警察官は，甲を立会人として本件窃盗事件に係る捜索差押許可状に基づき甲方を捜索中，テーブルに上記壺が置かれているのを発見し，これを差し押さえようとして手を伸ばしたところ，甲は，腹立ち紛れにその壺を取り上げ，その場で床にたたき付けて粉々に割った。（公務執行妨害罪）
          2: 2．甲は，自宅において，本件窃盗事件に係る捜索差押許可状に基づく捜索を受けた際，自宅に隠し持っていた覚せい剤が警察官に発見されることを恐れ，これを密かにトイレに流した。（証拠隠滅罪）
          3: 3．甲は，本件窃盗事件で通常逮捕され，警察署において弁解録取の手続を受けた際，警察官が甲の供述を記載した弁解録取書を手に取って破った。（公用文書毀棄罪）
          4: 4．甲は，本件窃盗事件について発付された勾留状の執行により留置施設に留置されていたが，留置担当者の隙を見て同施設から外へ逃走した。(単純逃走罪）
          5: 5．甲は，本件窃盗事件について犯人ではないと否認していたが，公判請求され，公判でAが被害状況を証言したことを逆恨みし，公判係属中，Aに対して「自分が有罪になったら，Aの自宅へ行って直接会ってお礼をさせてもらう。」旨の手紙を送り，Aはこれを読んで不安に思った。（証人威迫罪）
          6:
          7:
          8:
      19:
        questions: 罪刑法定主義に関する次のアからオまでの各記述のうち，正しいものの組合せは，後記1から5までのうちどれか。］
        answer:
          a: ア．犯罪と刑罰は，「法律」によって定められていなければならず，この「法律」には，法律の委任を受けた政令，条例及び慣習法が含まれる。
          i: イ．行為の時に適法であった行為を，その後の法律によって遡って犯罪とすることは，許されない。
          u: ウ．ある刑罰法規につき，条文の文言を，語義の可能な範囲内で通常の意味よりも広げて解釈することは，許されない。
          e: エ．刑の長期と短期を定めて言い渡し，現実の執行期間をその範囲内において執行機関の裁量に委ねることは，許されない。
          o: オ．ある刑罰法規が，犯罪に比べて著しく均衡を失する重い刑罰を規定している場合，当該刑罰法規は違憲である。
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．イオ
          4: 4．ウエ
          5: 5．ウオ
          6:
          7:
          8:
      20:
        questions: 次の【事例】に関する後記アからオまでの各【記述】を判例の立場に従って検討し，正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからオの順に[№30］から[№）4］【事例】借金の返済に苦しんでいた甲とその内縁の妻乙は，A市が発行した乙を被保険者とする国民健康保険被保険者証の氏名を乙から実在しない丙に改変し，丙になりすまして消費者金融会社から借入れをして現金を手に入れることを相談した。甲と相談したとおり，乙は，上記国民健康保険被保険者証の被保険者氏名欄に乙とあるのを丙と書き換えた。そして，乙は，消費者金融会社の無人借入手続コーナーにおいて，借入申込書に丙の氏名を記載し，丙と刻した印鑑を押捺するなどして丙名義の借入申込書1通を完成させた上，同申込書及び氏名を丙に改変した上記国民健康保険被保険者証の内容を，同コーナーに設置された機械を使用し，同機械に接続されている同社本店の端末機に送信し，同社の貸付手続担当者に対し，丙であるかのように装って100万円の借入れを申し込んだ。同担当者は，当該申込みをした者が真実丙であり，かつ，貸付金は約定のとおりに返済されるものと誤信し，同社の貸付システムに従って丙名義の借入カードを上記コーナーに設置された機械から発券した。乙は，その場で同カードを入手し，同カードを現金自動入出機に挿入して同機から現金100万円を引き出した。その後，乙は，上記行為に及んだことを後悔し，自宅で，甲に一緒に自首をしようと持ち掛けた。甲は，これを聞いて激高し，乙を窒息死させようと考え，その首を絞めたところ，乙は首を絞められたことによるショックで心不全になり死亡した。甲は，乙の死亡から約30分後，死亡して横たわっている乙の指に時価20万円相当の乙の指輪がはめてあることに気が付き，同指輪を奪って逃走した。【記述】
        answer:
          a: ア．乙が国民健康保険被保険者証の被保険者氏名欄を丙と書き換えた行為については，単に文書の内容を書き換えたにすぎないから，甲と乙には，公文書偽造罪ではなく，公文書変造罪が成立する。[№30］
          i: イ．乙が丙名義の借入申込書を作成した行為については，丙が実在しなくても，一般人をして真正に作成された文書であると誤信させる危険があるから，甲と乙には有印私文書偽造罪が成立する。[№31］
          u: ウ．甲と乙は，当初から現金100万円を手に入れる目的で丙名義の借入カードを入手し，同カードを利用して現金100万円を引き出したのだから，甲と乙には現金100万円について詐欺罪が成立する。[№32］
          e: エ．甲は，乙を窒息死させようとしていたが，乙はそれとは別の原因で死亡するに至ったのであるから，甲には，乙の首を絞めて死亡させた行為について殺人既遂罪は成立せず，殺人未遂罪と過失致死罪が成立する。[№33］
          o: オ．甲が乙の指輪を奪った行為については，その時点で乙は既に死んでいるから，甲には，窃盗罪ではなく，占有離脱物横領罪が成立する。[№34］
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
