---
ja:
  kenpo:
    2017:
      1:
        questions: 公権力との間で特別な法律関係にある個人に対する人権の制約に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№1]）
        answer:
          a: ア．公務員の労働基本権の制限に関し，全農林警職法事件判決（最高裁判所昭和48年4月25日大法廷判決，刑集27巻4号547頁）以降の最高裁判所の判例は，職務の内容にかかわらず公務員の争議行為を一律に禁止することについて，合憲とする判断を維持している。
          i: イ．公権力が特別権力関係に属する個人に対して包括的な支配権を有し，その個人の人権を法律の根拠なくして制限することができるほか，特別権力関係内部における公権力の行為は司法審査に服さないとする特別権力関係論は，日本国憲法の下では妥当し難い。
          u: ウ．かつて特別権力関係とされた在監関係につき，現在では，刑事収容施設及び被収容者等の処遇に関する法律において刑事施設被収容者の権利義務が明確化され，書籍等の閲覧，外部の者との面会及び信書の発受の各制限についてその要件が法定されたことにより，刑事施設の長らはそれらの制限の可否について裁量を失った。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      2:
        questions: 夫婦が婚姻の際に定めるところに従い夫又は妻の氏を称すると定める民法第750条の規定が，憲法第13条の規定に違反するか否かについて判示した最高裁判所の判決（最高裁判所平成27年12月16日大法廷判決，民集69巻8号2586頁）に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№2]から[№4]）
        answer:
          a: ア．前記判決は，氏名について，その個人からみれば，人が個人として尊重される基礎であり，その個人の人格の象徴であって，人格権の一内容を構成するが，具体的な法制度を離れて，氏が変更されること自体を捉えて直ちに人格権を侵害し，違憲であるか否かを論ずるのは相当ではないとした。[№2]
          i: イ．前記判決は，氏には，名とは切り離された存在として社会の構成要素である家族の呼称としての意義があるとの点を強調して，婚姻を含めた身分関係の変動に伴って自らの意思に関わりなく氏が改められるとしてもやむを得ないという結論を導いている。[№3]
          u: ウ．前記判決は，現行の法制度の下における氏の性質等に鑑み，婚姻の際に「氏の変更を強制されない自由」が憲法上の権利として保障される人格権の一内容であるといえるとしつつも，結論として，民法第750条の規定が憲法第13条に違反するとまではいえないとした。[№4]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      3:
        questions: 日本国民である父親から出生後に認知された子の日本国籍の取得をめぐる国籍法違憲判決（最高裁判所平成20年6月4日大法廷判決，民集62巻6号1367頁）に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№5]から[№7]）
        answer:
          a: ア．前記判決は，日本国民を血統上の親として出生しながら，日本国籍を生来的に取得できなかった子について，日本国籍を生来的に取得した子よりも日本国籍の取得の要件を加重すべきであるとする立法目的には，法律婚を尊重する観点から合理的な根拠があるとした。[№5]
          i: イ．前記判決は，日本国民である父親から出生後に認知された子について，父母の婚姻が日本国籍の取得の要件とされている点をして，立法目的との合理的関連性の認められる範囲を著しく超える手段を採用したものであるとした。[№6]
          u: ウ．前記判決は，婚姻関係にない父母から出生した子について将来にわたって不合理な偏見を生じさせるおそれがあることなどを指摘し，父母の婚姻という事柄をもって日本国籍の取得の要件に区別を生じさせることに合理的な理由があるか否かについては慎重に検討することが必要であるとした。[№7]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      4:
        questions: 思想・良心の自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№8]から[№10]）
        answer:
          a: ア．企業が従業員を採用するに際して，その者の在学中における団体加入や学生運動参加の事実の有無について申告を求めることは，その事実がその者の思想・良心と全く関係ないものではないから，違法である。[№8]
          i: イ．市立小学校の入学式における国歌斉唱の際に「君が代」のピアノ伴奏をする行為は，音楽専科の教諭にとって通常想定され期待されるものであり，当該教諭が特定の思想を有するということを外部に表明する行為であると評価することは困難なものである。[№9]
          u: ウ．公立高等学校の卒業式における国歌斉唱の際に起立斉唱する行為は，学校の儀礼的行事における慣例上の儀礼的な所作としての性質を有するものであり，同校の校長が教諭に当該行為を命じても，当該教諭の思想・良心の自由を何ら制約するものではない。[№10]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      5:
        questions: いわゆる政教分離に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№11]から[№13]）
        answer:
          a: ア．国公有地が特定の宗教的施設の敷地として無償提供された場合に政教分離原則に違反するか否かを判断するに当たり，当該宗教的施設の性格，当該無償提供に至る経緯及びその提供の態様については考慮に入れるべきであるが，これらに対する一般人の評価についてまで考慮に入れることは，多数者による少数者の宗教的抑圧につながるおそれがあるので相当ではない。[№11]
          i: イ．宗教上の祝典，儀式，行事については，その目的が宗教的意義を持ち，その効果が宗教に対する援助，助長，促進又は圧迫，干渉等になるような行為であれば，憲法第20条第3項により禁止される「宗教的活動」に含まれるが，その判断に当たっては，社会通念に従って客観的になされなければならないから，行為者がどのような宗教的意識を有していたかについてまで考慮に入れるべきではない。[№12]
          u: ウ．地方公共団体が町内会に対し特定の宗教的施設の敷地として公有地を無償で利用に供してきたところ，当該行為が政教分離原則に違反するおそれがあるためにこれを是正解消する必要がある一方で，当該宗教的施設を撤去させることを図るとすると，信教の自由に重大な不利益を及ぼしかねないことなどの事情がある場合には，当該町内会に当該公有地を譲与したとしても直ちに政教分離原則に違反するとはいえない。[№13]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      6:
        questions: 公務員宿舎である集合住宅の各室玄関ドアの新聞受けに，政治的意見を記載したビラを投かんする目的で同集合住宅の敷地等に立ち入った事案について判示した最高裁判所の判決（平成20年4月11日第二小法廷判決，刑集62巻5号1217頁）に関する次のアからエまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからエの順に[№14]から[№17]）
        answer:
          a: ア．前記判決は，被告人らによる政治的意見を記載したビラの配布は，表現の自由の行使ということができ，その行為を刑法第130条前段の罪により処罰することは，表現そのものを処罰することの憲法適合性が問題となるとした。[№14]
          i: イ．前記判決は，表現の自由は，送り手の情報が妨げられることなく受け手に受領されることを当然に内包しており，本件で被告人らの行為に刑事罰を科すことは，本件公務員宿舎の居住者が情報に接する機会を奪い，その受領権を侵害することになるとした。[№15]
          u: ウ．前記判決は，本件立入りの場所が自衛隊・防衛庁当局が管理するものであることから，いわゆるパブリック・フォーラムたる性質を持つものであることを前提としつつ，判示したものである。[№16]
          e: エ．前記判決の後の判決（最高裁判所平成21年11月30日第二小法廷判決，刑集63巻9号1765頁）では，政党のビラを配布するために民間の分譲マンションの各住戸の廊下等共用部分に立ち入った行為につき，表現の自由の重要性に鑑み，当該マンションの管理者が商業的な宣伝・広告のビラのみならず政党のビラを配布することまで禁止するのは合理性を欠くとして，かかる行為を刑法第130条の罪に問うことは憲法第21条第1項に反する旨判示された。[№17]
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      7:
        questions: 取材の自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№18]）
        answer:
          a: ア．報道機関の取材結果に対する裁判所による提出命令の可否の判断に当たっては，個別事情を考慮することなく，公正な刑事裁判の一般的価値とこれと対立する取材の自由・報道の自由の一般的価値とを比較衡量して判断するという手法によるのが相当である。
          i: イ．適正迅速な捜査は公正な刑事裁判の不可欠の前提であることから，取材の自由に対する制約の許否に関しては捜査と公判とで本質的な差異はなく，したがって，差押えの主体にかかわらず，報道機関の取材結果に対する差押えの可否を判断する際の基本的な考え方は変わらない。
          u: ウ．民事訴訟における，報道関係者による取材源に係る証言拒絶は，当該報道が公共の利益に関わり，取材方法が適切であり，取材源が秘密の開示を承諾していない場合には，当該民事事件が社会的意義や影響のある重大な民事事件であっても，原則として許容される。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      8:
        questions: 憲法第22条第1項の解釈に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№19]）
        answer:
          a: ア．農業災害補償法が一定の稲作農業者を農業共済組合に当然に加入させる仕組みを採用したことの合憲性は，当該仕組みが国民の主食である米の生産の確保と稲作を行う自作農の経営の保護を目的とすることから，必要最小限度の規制であるか否かによって判断される。
          i: イ．憲法第22条第1項は職業選択の自由を保障しているが，いわゆる営業の自由は，財産権の行使という側面を併せ有することから，同項及び第29条第1項の規定によって根拠付けられる。
          u: ウ．職業の許可制は，狭義の職業の選択の自由そのものに制約を課す強力な制限であるため，社会政策ないしは経済政策上の積極的な目的のための措置であっても，より緩やかな規制によってはその目的を十分に達することができない場合でなければ，合憲性を肯定し得ない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      9:
        questions: 第三者所有物没収事件判決（最高裁判所昭和37年11月28日大法廷判決，刑集16巻11号1593頁）に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№20]）
        answer:
          a: ア．前記判決は，被告人以外の第三者の所有物（以下「第三者所有物」という。）を没収する場合において，当該第三者に対し告知，弁解，防御の機会を与えることなくその所有物を没収することは，適正な法律手続によらないで財産権を侵害する制裁を科するに外ならない旨判示した。
          i: イ．前記判決は，被告人に対する附加刑として科される第三者所有物に対する没収の言渡により，当該第三者の占有権が剥奪されるにとどまり，所有権剥奪の効果は生じないことを，その判断の前提としている。
          u: ウ．前記判決では，第三者所有物について没収の言渡を受けた被告人は，その没収の裁判の違憲を理由として上告することができるとされた。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      10:
        questions: 生存権とこれを具体化した法制度に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№21]）
        answer:
          a: ア．国民年金制度は，憲法第25条の趣旨を実現するために設けられた社会保障上の制度であるから，同条の趣旨にこたえて具体的にどのような立法措置を講ずるかの選択決定は，立法府の広い裁量にゆだねられており，著しく合理性を欠き明らかに裁量の逸脱，濫用とみざるを得ないような場合を除いて，裁判所が審査判断するに適しない事柄であり，何ら合理的理由のない不当な差別的取扱いがあっても，憲法第14条違反の問題は生じ得ない。
          i: イ．憲法第25条にいう「健康で文化的な最低限度の生活」は，きわめて抽象的・相対的な概念であって，その具体的内容は，その時々における文化の発達の程度，経済的・社会的条件，一般的な国民生活の状況等との相関関係において判断決定されるべきものであるから，国の立法として具体化される場合にも，国の財政事情は考慮されるべきではない。
          u: ウ．国は，難民条約の批准及びこれに伴う国会審議等を契機に，外国人に対する生活保護について一定の範囲で国際法及び国内公法上の義務を負うことを認めるに至ったものであり，少なくとも永住外国人にも憲法第25条第1項の保障が及ぶものとなったと解すべきであるから，生活保護法の適用対象となる「国民」には永住外国人も含まれる。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      11:
        questions: 刑事補償請求権に関する次の学生アからエまでの各発言について，正しいものの組合せを，後記1から6までの中から選びなさい。（解答欄は，[№22]）
        answer:
          a: ア．「抑留又は拘禁という人権制限措置を受けたけれども結果として無罪とされた者に，相応の補償をすることによって，公平の要請を満たそうとするのが憲法第40条なんだね。」
          i: イ．「無罪判決を受けた刑事被告人が，抑留又は拘禁されたことを理由に，憲法第17条に定める国家賠償を求め得るケースはあり得ないからね。」
          u: ウ．「憲法第40条は『無罪の裁判を受けたとき』について定めているけど，この文言の意味について，無罪判決が確定したとき又は一旦確定していた有罪判決が再審の結果取り消されて無罪が言い渡されたときを意味すると解する説によれば，同条は免訴や公訴棄却の裁判を受けた場合についても補償することを要請していることになるよ。」
          e: エ．「不起訴となった事実Aに基づく抑留又は拘禁であっても，そのうちに実質上は無罪となった事実Bについての抑留又は拘禁であると認められるものがあるときは，その部分の抑留又は拘禁も憲法第40条の『抑留又は拘禁』に包含されるとした最高裁判所の判例があったな。」
          o:
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．アエ
          4: 4．イウ
          5: 5．イエ
          6: 6．ウエ
          7:
          8:
      12:
        questions: 天皇に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№23]から[№25]）
        answer:
          a: ア．天皇の人権には，天皇の象徴たる地位に基づく制約があり，特定の政党に加入することや国籍を離脱することは認められないが，学問の自由についてはかかる制約を受けることなく一般の国民と同等に保障されている。[№23]
          i: イ．判例は，天皇が日本国の象徴であり日本国民統合の象徴であることに鑑み，天皇には民事裁判権が及ばないとし，摂政についても，天皇の名でその国事に関する行為を行うことから同様であるとしている。[№24]
          u: ウ．憲法第2条は，皇位が世襲のものである旨定めているところ，その具体的な在り方を定める皇室典範において，皇位の継承において皇長子の長子より皇次子を優先させることとしても憲法に反するものではない。[№25]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      13:
        questions: 選挙権及び選挙制度に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№26]から[№28]）
        answer:
          a: ア．憲法は，国民主権の原理に基づき，国民に対して，両議院の議員の選挙において投票をすることによって国の政治に参加することができる権利の保障は認めているが，投票をする機会の平等までは保障していない。[№26]
          i: イ．選挙運動の一つの手段である政見放送において，政見放送の品位を損なう言動を禁止した公職選挙法第150条の2の規定に違反する言動がそのまま放送される利益は，法的に保護された利益とはいえず，したがって，上記言動がそのまま放送されなかったとしても，法的利益の侵害があったとはいえない。[№27]
          u: ウ．憲法は，両議院の議員の選挙において投票をすることを，一定の年齢に達した国民の固有の権利として保障しており，自ら選挙の公正を害する行為をした者等の選挙権について一定の制限をすることは別として，選挙権又はその行使を制限するためには，そのような制限をすることがやむを得ないと認められる事由がなければならない。[№28]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      14:
        questions: 政党に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№29]から[№31]）
        answer:
          a: ア．憲法には政党について直接規定されていないが，政党は，憲法の定める議会制民主主義を支える上で極めて重要な存在であることから，憲法は，政党の存在を当然に予定しているとするのが判例の立場である。[№29]
          i: イ．憲法第51条は，「両議院の議員は，議院で行つた演説，討論又は表決について，院外で責任を問はれない。」と定め，国民の代表たる国会議員の職務執行の自由を保障しているから，議院内での国会議員による発言や表決を理由にその所属政党が除名処分をすることはできない。[№30]
          u: ウ．政党がその所属党員に対してした除名その他の処分の当否について，裁判所は，原則として適正な手続にのっとってされたか否かを審査して判断すべきであり，一般市民としての権利利益を侵害する場合に限り処分内容の当否を審査できるとするのが判例の立場である。[№31]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      15:
        questions: "）国会の立法手続に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№32]）"
        answer:
          a: ア．国会の活動につき，憲法は，常会（第52条），臨時会（第53条），特別会（第54条第1項）というように一定の期間を単位として行う会期制を採用し，国会法は，会期内に議決に至らなかった議案は後会に継続しないという会期不継続の原則を採用している。
          i: イ．国会の議事手続については両議院の自主性を尊重すべきであるから，裁判所としては，法律制定の議事手続に関する事実を審理して当該法律の有効無効を判断すべきではないというのが判例の立場である。
          u: ウ．内閣の法律案提出権が認められるのは，議院内閣制においては国会と内閣との協働が当然に要請されており，憲法第72条の「議案」に法律案も含まれるからであるとの立場に立ったとしても，法律により内閣の法律案提出権を否定することができる。
          e:
          o:
        additional_answer:
          1: 1．ア〇イ〇ウ〇
          2: 2．ア〇イ〇ウ×
          3: 3．ア〇イ×ウ〇
          4: 4．ア〇イ×ウ×
          5: 5．ア×イ〇ウ〇
          6: 6．ア×イ〇ウ×
          7: 7．ア×イ×ウ〇
          8: 8．ア×イ×ウ×
      16:
        questions: 内閣及び内閣総理大臣に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№33]から[№35]）
        answer:
          a: ア．憲法は閣議について規定していないが，内閣が行政権の行使について国会に対し連帯して責任を負うとする憲法第66条第3項の趣旨により，会合しないで文書を各大臣間に持ち回って署名を得る持ち回り閣議は許されないとされている。[№33]
          i: イ．内閣の総辞職について規定している憲法第70条の「内閣総理大臣が欠けたとき」とは，内閣総理大臣が死亡した場合のほか，憲法第58条第2項に基づき内閣総理大臣が除名により国会議員の地位を失った場合に限られる。[№34]
          u: ウ．憲法第73条第6号は，内閣の政令制定権を規定しているところ，法律を執行するための必要な細則を定める執行命令及び法律が政令に委任した事項を定める委任命令は許されるが，既存の法律に代替する内容を定める代行命令は許されない。[№35]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      17:
        questions: 最高裁判所の規則制定権に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№36]）
        answer:
          a: ア．最高裁判所は，裁判所の内部規律に関する事項について規則を定める権限を有するが，憲法第76条第3項は，すべて裁判官は憲法及び法律にのみ拘束されると定めているから，裁判官を対象とする事項を規則で制定することはできない。
          i: イ．最高裁判所の制定する規則は，その対象となる事項が規則を制定した機関の内部事項に限られないという点で，議院規則と異なる性質を有する。
          u: ウ．「この法律に定めるもののほか，非訟事件の手続に関し必要な事項は，最高裁判所規則で定める。」との非訟事件手続法第2条の規定は，憲法第77条第1項において規則の対象とされている「訴訟に関する手続」に非訟事件の手続が含まれないとの立場を前提としている。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      18:
        questions: 裁判所の違憲審査に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№37]）
        answer:
          a: ア．裁判所は，処罰対象となる行為が過度に広汎であることが争われている罰則の合憲性の判断に当たり，その規制目的や当該目的達成の手段としての合理性等を審査する場合がある。
          i: イ．合憲限定解釈は，合憲性が争われている法令について法令違憲との判決を下すことを回避する手段の一つである。
          u: ウ．合憲的な適用であることが明らかである場合には，適用された法令に合憲的に適用できる部分と違憲的に適用される可能性のある部分とが不可分の関係で含まれていたとしても，法令違憲と判断する余地はないことになる。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      19:
        questions: 財政に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。（解答欄は，アからウの順に[№38]から[№40]）
        answer:
          a: ア．「租税を除く外，国が国権に基いて収納する課徴金及び法律上又は事実上国の独占に属する事業における専売価格若しくは事業料金については，すべて法律又は国会の議決に基いて定めなければならない。」と規定する財政法第3条について，その根拠を憲法第83条の財政民主主義に求める見解に対しては，財政法第3条は，具体的な金額又は金額算定基準まで法律によって定めることまで要求していないのであるから，憲法第83条と矛盾することになるとの批判が妥当する。[№38]
          i: イ．最高裁判所の判例によれば，個人への特別の給付に対する反対給付として当該個人に対して課する国民健康保険料のような金銭給付は憲法第84条の「租税」には当たらないと狭く解したとしても，「租税」以外の公課の賦課要件について定めた条例が憲法第84条の趣旨に反することはあり得る。[№39]
          u: ウ．国費を支出するには国会の議決に基づくことを必要とするが，国費の支出に関する国会の議決は使途の確定した支出についてなされるべきものであるから，使途が未確定である予備費を設けることについては国会の議決を要しない。[№40]
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      20:
        questions: 憲法改正に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。（解答欄は，[№41]）
        answer:
          a: ア．憲法改正には，国民投票において「その過半数の賛成」を必要とするとされているが，日本国憲法の改正手続に関する法律によって，「その過半数」とは，有権者総数の過半数を意味するとされている。
          i: イ．憲法第96条第2項は，国民の承認を経た憲法改正について，「直ちにこれを公布する」と定めているが，ここで「直ちに」とされているのは，公布を恣意的に遅らせてはならないことを定めたものである。
          u: ウ．憲法を始源的に創設する「憲法制定権力」と憲法によって与えられた「憲法改正権」とは同質であるとの見解は，憲法改正の限界について理論上限界はないとする立場の根拠となり得る。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
