---
ja:
  kenpo:
    2021:
      1:
        questions: 公務員や未決拘禁者など，公権力との関係で特別な法律関係にある者の権利制約に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．多数の被拘禁者を外部から隔離して収容する施設では，施設内でこれらの者を集団として管理するに当たり，内部の規律及び秩序を維持し，その正常な状態を保持する必要があるから，この目的のため必要がある場合には，未決拘禁者についても，身体の自由やその他の行為の自由に一定の制限が加えられることはやむを得ない。
          i: イ．刑事収容施設内において喫煙を許すことにより，罪証隠滅のおそれがあり，また火災発生により被拘禁者の逃走や人道上の重大事態の発生も予想される一方，たばこは生活必需品とまではいえず嗜好品にすぎないことからすれば，喫煙の自由が憲法の保障する人権に含まれるとしても，制限の必要性の程度と制限される基本的人権の内容，これに加えられる具体的制限の態様とを総合的に考慮すると，施設内における喫煙禁止は必要かつ合理的なものといえる。
          u: ウ．職権行使の独立が保障され，単独で又は合議体の一員として司法権を行使する主体として，国に対する訴訟を含めて中立・公正な立場から裁判を行うことが強く期待される裁判官に対する政治運動禁止の要請は，議会制民主主義の政治過程を経て決定された政策を，政治的偏向を排し組織の一員として忠実に遂行すべき立場にある一般職の国家公務員に対する政治的行為の禁止の要請ほどには強くないというべきである。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      2:
        questions: 憲法の明文で規定されていない権利・自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには〇，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．髪型の自由は，自己決定権として憲法第13条によって保障されるものである。それゆえ，非行を防止する目的で高校生らしい髪型を維持するよう求める校則の定めが，社会通念上不合理なものとはいえないとしても，これに反した生徒を退学させることは許されない。
          i: イ．学籍番号，氏名，住所及び電話番号といった個人情報は，大学が個人識別等を行うための単純な情報である。それゆえ，このような個人情報については，プライバシーに係る情報として法的保護の対象とはならない。
          u: ウ．指紋は，それ自体では個人の私生活や人格，思想，信条，良心等個人の内心に関する情報となるものではないが，何人も個人の私生活上の自由の一つとして，みだりに指紋の押なつを強制されない自由を有する。それゆえ，在留外国人の指紋押なつ制度は，国家機関が正当な理由なく指紋の押なつを強制するものであり，憲法第13条の趣旨に反し，許されない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      3:
        questions: 法の下の平等に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．尊属に対する尊重報恩は社会生活上の基本的道義であるが，このような自然的情愛ないし普遍的倫理の維持は，刑法上の保護に値するものではなく，尊属殺を通常の殺人よりも重く処罰する規定は，合理的な根拠に基づくものといえないから，憲法第14条第1項に違反する。
          i: イ．国籍法の規定が，同じく日本国民である父から認知された子でありながら，父母の婚姻により嫡出子たる身分を取得した者と異なり，父母が法律上の婚姻をしていない非嫡出子は同法所定の他の要件を満たしても日本国籍を取得することができないという区別を生じさせていることは，同規定の立法目的との合理的関連性を欠くものであり，憲法第14条第1項に違反する。
          u: ウ．女性に対し6か月の再婚禁止期間を定める規定の立法目的は，父性の推定の重複を回避し，父子関係をめぐる紛争の発生を未然に防ぐことにあると解され，6か月の再婚禁止期間を設けることはこの立法目的との関連において合理性を有するから，憲法第14条第1項に違反しない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      4:
        questions: 思想・良心の自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．憲法第19条の保障する良心の自由は，単に事物に関する是非弁別の内心的自由のみならず，かかる是非弁別の判断に関する事項を外部的に表現するか否かの自由をも包含するものであるから，謝罪広告の掲載を命ずる判決は，良心の自由への直接的な制約となるが，その内容が名誉回復のために必要な限度にとどまるものであれば，同条に違反しない。［No.4］
          i: イ．公立中学校の校長が，同校の生徒について，大学生の政治集会に参加しているなどと記載した内申書を作成提出することは，同記載が生徒の思想，信条そのものを記載したものでなく，同記載に係る外部的行為によっては生徒の思想，信条を了知し得るものではないし，また，生徒の思想，信条自体を高等学校の入学者選抜の資料に供したものと解することはできないから，憲法第19条に違反しない。［No.5］
          u: ウ．公立小学校の校長が，音楽専科の教諭に対し，入学式における国歌斉唱の際に「君が代」のピアノ伴奏を行うよう命ずることは，個人の歴史観ないし世界観に由来する行動と異なる外部的行為を求めるものとして，思想・良心の自由への間接的な制約となるが，地方公務員としての職務の公共性に加え，ピアノ伴奏が音楽専科の教諭にとって通常想定され期待される行為であることからすれば，許容される制約であり，憲法第19条に違反しない。［No.6］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      5:
        questions: 表現の自由に関する次のアからウまでの各記述について，bの見解がaの見解の批判となっている場合には1を，そうでない場合には2を選びなさい。
        answer:
          a: ア．a．表現の自由に対する規制について，表現の内容に着目した内容規制には，厳格な審査基準が妥当し，表現の時・場所・方法等の規制に関わる内容中立的規制の場合には，より緩やかな審査基準が妥当する。b．審査基準の枠組みの設定の仕方が図式的になり過ぎており，人によって極めて重要な意義を持つはずの表現の時・場所・方法等の規制の危険性・問題性を軽視している。［No.7］
          i: イ．a．商品知識の啓蒙や，意見の伝達等何らかの表現行為に関わる広告は，表現の自由の保障の対象となるが，純然たる営利広告は，経済的自由の保障の対象となる。b．消費者の側から見ると，純然たる営利広告も，一つの重要な生活情報としての意味を持ち得るから，それを表現の自由の保障の対象外としてしまうと，消費者の知る権利を害することになる。［No.8］
          u: ウ．a．表現行為に先立ち行政権がその内容を事前に審査し不適当と認める場合にその表現行為を禁止する検閲は，憲法第21条第2項により絶対的に禁止され，同条第1項から導き出される広義の事前抑制の原則的禁止とは区別される。b．独立性を保障された司法権と行政権との区別は重要であり，また，検閲の禁止に例外を認める解釈は，憲法第21条第2項が，「検閲は，これをしてはならない」と明記していることに反する。［No.9］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      6:
        questions: 集会の自由に関する次のアからウまでの各記述について，bの見解がaの見解の批判となっている場合には1を，そうでない場合には2を選びなさい。
        answer:
          a: ア．a．地方公共団体は，公の施設を利用して特定の集会が開かれることにより，その集会の主催者と敵対するグループ等とが衝突して，人の生命・身体・財産が侵害され，公共の安全が損なわれる危険がある場合には，公の施設の利用を不許可とすることができる。b．主催者が集会を平穏に行おうとしているのに，その集会の目的や主催者の思想，信条に反対する他のグループ等がこれを実力で阻止し，妨害しようとして紛争を起こすおそれがあることを理由に公の施設の利用を拒むことは，憲法第21条の趣旨に反する。［No.10］
          i: イ．a．所有権や管理権に基づく集会の規制が許されるかどうかの判断に当たっては，集会の場所が一般公衆が自由に出入りできるものであるときには，集会の自由の保障に可能な限り配慮する必要がある。b．主張や意見を社会に伝達する自由を保障する場合には，その表現の場を確保することが重要な意味を持ち，特に，表現の自由の行使が行動を伴うときには，表現のための物理的な場所が提供されなければ，意見を受け手に伝えることができない。［No.11］
          u: ウ．a．集会や集団行動については，公共の秩序を維持するため，又は公共の福祉が著しく害されることを防止するために一定の法的規制が必要であるから，集会等の時間，場所，方法を問わず，事前の許可を要すると条例で定めることもやむを得ない。b．集会や集団行動が他人の権利と衝突することがあるとしても，その衝突の程度は集会等の具体的態様によって大きく異なるから，一律に事前の許可にかからしめることは集会の自由に対する過大な制約である。［No.12］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      7:
        questions: 憲法第23条に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．大学の学問の自由と自治は，大学が学術の中心として深く真理を探究し，専門の学芸を教授研究することを本質とすることに基づくから，教授や研究者の研究，その結果の発表，研究結果の教授の自由とこれらを保障するための自治とを意味すると解されており，大学の学生が学問の自由を享有するのは，教授や研究者の有する特別な学問の自由と自治の効果としてである。
          i: イ．子どもの教育は教師と子どもとの間の人格的接触を通じ，その個性に応じて行われなければならないが，全国的に一定の水準の教育を確保する必要があるので，教師に教授の具体的内容及び方法について裁量を認めることはできない。
          u: ウ．大学における学生の集会が大学の学問の自由と自治を享有するか否かは，その集会が真に学問的な研究と発表のためのものか，実社会の政治的社会的活動に当たるかによって判断されるものであり，その集会が公開か否かといった点は考慮されない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      8:
        questions: 財産権の制限と損失補償に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．法律の規定により財産上の権利の行使が制限される場合であっても，災害を未然に防止するという社会生活上のやむを得ない必要からその制限が当然受忍すべきものであるときは，憲法第29条第3項による損失補償を要しない。［No.14］
          i: イ．財産上の権利の行使を制限する法律が補償規定を欠いている場合であっても，相当の資本を投入してきた者が，一般的に当然に受忍すべきものとされる範囲を超えて制限を受けるときは，憲法第29条第3項を根拠として補償請求をする余地がある。［No.15］
          u: ウ．財産上の権利の行使を制限する法律に補償規定が置かれている場合であっても，その法律は，補償の内容が憲法第29条第3項の要求する水準にあるか否かについて，憲法適合性の審査の対象となる。［No.16］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      9:
        questions: 生存権に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．憲法第25条にいう「健康で文化的な最低限度の生活」は，抽象的・相対的な概念であって，その具体的な内容は，その時々における文化の発達の程度，経済的・社会的条件，一般的な国民生活の状況等との相関関係において判断決定されるべきものであるとともに，同規定を現実の立法として具体化するに当たっては，国の財政事情を無視することができず，高度の専門技術的な考察とそれに基づいた政策的判断を必要とする。
          i: イ．憲法第25条の生存権を具体化する趣旨の法律として，生活保護法等の法律が制定された場合，その法律は憲法第25条と一体をなし，かかる法律の定める給付水準を正当な理由なくして引き下げることは憲法上許されない。
          u: ウ．憲法第25条第2項で定める防貧施策については広い立法裁量が認められる一方，同条第1項で定める救貧施策については，国は国民の最低限度の生活を保障する責務を負い，前者よりも厳格な違憲審査基準が用いられる。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      10:
        questions: "）刑事補償請求権に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。"
        answer:
          a: ア．憲法第40条は，抑留又は拘禁された後に刑事事件において無罪の裁判を受けた者について，その手続がたとえ憲法第31条以下の諸権利の保障に反しなかったとしても，多大な犠牲を被っている以上，正義・衡平の観点から金銭による事後的救済を与えようとする趣旨の規定である。［No.18］
          i: イ．判例は，不起訴になった事実に関する抑留又は拘禁であっても，そのうちに実質上は，無罪となった事実についての抑留又は拘禁と認められるものがあるときは，その部分の抑留又は拘禁も，憲法第40条にいう「抑留又は拘禁」に包含されると解している。［No.19］
          u: ウ．判例は，家庭裁判所における少年審判手続において非行事実がないことを理由とする不処分決定について，刑事事件において無罪の裁判を受けたことと実質的に同視できるとして，同決定を受けた者を刑事補償の対象としないことは憲法第40条に違反すると解している。［No.20］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      11:
        questions: "）主権に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。"
        answer:
          a: ア．国民主権の原理に基づき，国及び普通地方公共団体による統治の在り方については日本国の統治者としての国民が最終的な責任を負うべきものであることからすると，外国人が普通地方公共団体の公務員に就任することは，その者が公権力の行使に当たる行為を行うかどうかにかかわらず，本来我が国の法体系の想定するところではない。
          i: イ．裁判員制度は国民主権の理念に沿って司法の国民的基盤の強化を図るものであり，裁判員の職務等が司法権の行使に対する国民の参加という点で参政権と同様の権限を国民に付与するものであることからすると，裁判員の職務等を憲法第18条後段が禁ずる「苦役」に当たるということは，必ずしも適切ではない。
          u: ウ．天皇は日本国の象徴であり日本国民統合の象徴であるが，この地位は主権の存する日本国民の総意に基づくものであるとともに，民事裁判権が国民に由来する司法権の一作用であることからすれば，天皇に裁判所の民事裁判権が及ばないものと解することはできない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      12:
        questions: "）政党に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。"
        answer:
          a: ア．憲法は，政党について規定するところがないが，政党の存在を当然に予定しており，政党は，議会制民主主義を支える不可欠の要素であるから，国会が，参議院議員の選挙制度の仕組みを決めるに当たり，このような政党の国政上の重要な役割を踏まえて，政党を媒体として国民の政治意思を国政に反映させる名簿式比例代表制を採用することは，国会の裁量の範囲内である。［No.22］
          i: イ．政党に対しては，高度の自主性と自律性を与えて自主的に組織運営をなし得る自由を保障しなければならず，また，党員が政党の存立及び組織の秩序維持のために，自己の権利や自由に一定の制約を受けることがあるのも当然であるから，政党が党員に対してした除名処分の当否は，一般市民法秩序と直接の関係を有しない内部的な問題にとどまる限り，裁判所の審判権は及ばない。［No.23］
          u: ウ．衆議院の小選挙区選挙について，候補者届出政党にのみ政見放送を認め，候補者を含むそれ以外の者には政見放送を認めないものとする公職選挙法の規定は，選挙運動をする上で，候補者届出政党に所属する候補者とこれに所属しない候補者との間に単なる程度の違いを超える差異を設ける結果となり，国会に与えられた合理的裁量の限界を超えるものであるから，憲法第14条第1項に違反する。［No.24］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      13:
        questions: "）憲法第9条の解釈に関する次のアからウまでの各記述について，bの見解がaの見解の批判となっている場合には1を，そうでない場合には2を選びなさい。"
        answer:
          a: ア．a．憲法第9条第1項は，侵略戦争を放棄しているが，自衛戦争は放棄しておらず，同条第2項にいう「前項の目的」とは，第1項の「国際紛争を解決する手段として」の戦争の放棄のみを指すから，自衛のための戦力の保持は禁じられていない。b．自衛のための戦力と侵略のための戦力とを区別することは困難であり，戦力の保持を禁じた第2項の規定が無意味なものとなる。［No.25］
          i: イ．a．憲法第9条第1項は，侵略戦争を放棄しているが，自衛戦争は放棄しておらず，同条第2項にいう「前項の目的」とは，第1項全体の精神，すなわち「正義と秩序を基調とする国際平和を誠実に希求し」を指し，第2項によって警察力を上回る実力の保持が禁じられている。b．日本国憲法には，第66条第2項の文民条項を除き，戦争開始の決定手続や軍隊の編制に関する規定が存在しない。［No.26］
          u: ウ．a．憲法第9条は，我が国が主権国として有する固有の自衛権まで否定するものではなく，自衛のために必要な最小限度の実力，すなわち自衛力の保持を禁じていない。b．個人の正当防衛の権利とは異なり，国家が固有の権利として自衛権を有するということはできない。［No.27］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      14:
        questions: "）国会議員の免責特権に関する次のアからウまでの各記述について，最高裁判所の判決（最高裁判所平成9年9月9日第三小法廷判決，民集51巻8号3850頁）の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。"
        answer:
          a: ア．国会議員は，議院で行った演説，討論又は表決に加えて，国会における意見の表明とみられる行為や，職務行為に付随する行為に関しては，国民全体に対する関係で政治的責任を負うにとどまり，個別の国民の権利に対応した関係での法的義務を負うものではないから，国会議員の上記の行為そのものが国家賠償法上の違法の評価を受けることはない。
          i: イ．国会議員が，立法，条約締結の承認，財政の監督等の審議や国政に関する調査の過程で行う質疑等は，多数決原理により国家意思を形成する行為そのものではなく，国家意思の形成に向けられた行為であり，質疑等の内容が個別の国民の権利等に直接関わることも起こり得るので，質疑等において個人の権利を侵害した国会議員は，当該個人に対して損害賠償責任を負う。
          u: ウ．国会議員が，質疑等において，職務と無関係に違法又は不当な目的をもって事実を摘示し，あるいは，あえて虚偽の事実を摘示して，個別の国民の名誉を毀損したと認められる特別の事情がある場合には，国家賠償法第1条第1項に基づいて，国に賠償を求めることができることもある。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      15:
        questions: "）内閣及び内閣総理大臣に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。"
        answer:
          a: ア．内閣の総辞職について定める憲法第70条の「内閣総理大臣が欠けたとき」には内閣総理大臣の辞職の場合を含まないとする見解によっても，その首長たる地位に鑑みれば，内閣総理大臣が辞職したときには，内閣は総辞職しなければならない。
          i: イ．行政権が内閣に属する旨を定める憲法第65条によれば，あらゆる行政を内閣が自ら行う必要まではないとしても，全ての行政について内閣が直接に指揮監督権を持つことが要求される。
          u: ウ．憲法第66条第2項は，内閣総理大臣及び国務大臣が「文民」であることを要求しているが，現職の自衛官は「文民」に該当しないので，内閣総理大臣及び国務大臣に任命することはできない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      16:
        questions: "）裁判の公開に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。"
        answer:
          a: ア．判例によれば，憲法第82条にいう「公開」は，国民一般に裁判の傍聴が許されるということを意味するから，何人も，裁判所に対して裁判を傍聴することを権利として要求することができる。［No.30］
          i: イ．判例によれば，刑事事件の証人尋問の際に，傍聴席と証人との間に衝立を置くなどして傍聴人から証人を見ることができないようにすることは，審理を公開することの意義を没却するものであるから，憲法第82条に違反する。［No.31］
          u: ウ．裁判所が裁判官の全員一致で公の秩序又は善良の風俗を害するおそれがあると決することにより，傍聴人を退廷させて審理をすることができる場合であっても，判決の言渡しは，傍聴人を入廷させてしなければならない。［No.32］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      17:
        questions: "）憲法訴訟に関する次のアからウまでの各記述について，bの見解がaの見解の根拠となっている場合には1を，そうでない場合には2を選びなさい。"
        answer:
          a: ア．a．公職選挙法上の選挙無効訴訟において，選挙人である原告は，同法の規定により一定の者の選挙権が制限されていることに関し，他者の選挙権の制限に係る同規定の違憲を主張して争うことはできない。b．公職選挙法の規定により選挙権の制限を受ける者は，自己の選挙権侵害を理由に救済を求める訴訟において同規定の違憲を主張することができる。［No.33］
          i: イ．a．規制範囲が過度に広範である疑いのある法律の規定であっても，これを合理的に解釈することにより，その規制対象を合憲的に規制し得る行為に限定でき，違憲の疑いを除去することができる場合には，裁判所は，同規定を違憲と判断すべきではない。b．法律の違憲判断を回避することにより立法府への干渉を最小限に抑えるとともに，基本的人権の保障を果たすことができる。［No.34］
          u: ウ．a．最高裁判所が法令を違憲無効とする判決をした場合，その判決の効力が及ぶのは当該事件限りであり，違憲と判断された法律は当該事件の訴訟当事者との関係においてのみその適用を排除される。b．法的安定性を確保するためには，最高裁判所は，自らの法令違憲の判断の効力が及ぶ範囲を制限する旨説示できる。［No.35］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      18:
        questions: "）憲法第89条後段の「公の支配」の意義に関し，「国又は地方公共団体が，法令等により一定の監督をしていることで足りる」とする見解があるが，次のアからウまでの各記述について，かかる見解の根拠となる記述には○を，根拠とはならない記述には×を付した場合の組合せを，後記1から8までの中から選びなさい。"
        answer:
          a: ア．「公の支配」を厳格に捉え過ぎると，公的援助の対象となっている私的な団体等の自主性を過度に損なうことになり，望ましくない。
          i: イ．憲法第89条後段の趣旨は，財政民主主義の見地から，慈善，教育，博愛の事業に対する公金の支出が公の財産の濫費，濫用にならないように，国や地方公共団体が監督することにある。
          u: ウ．憲法第89条後段が，慈善，教育，博愛を特に掲げ，それを同条前段の宗教団体に対する公金支出等の禁止と一体のものとして定めていることを重視すべきである。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      19:
        questions: "）地方自治に関する次のアからウまでの各記述について，正しいものには〇，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。"
        answer:
          a: ア．地方自治の本質について，地方公共団体固有の前国家的な基本権を保障したものではなく，地方自治という歴史的・伝統的な制度を保障したものと解する立場に立つと，憲法第92条に規定された「地方自治の本旨」には特別の法的意味がないこととなる。
          i: イ．憲法は，都道府県と市町村という二層構造の地方公共団体を憲法上保障しておらず，地方公共団体の在り方は立法政策に委ねられるとする立場に立つと，現行の都道府県より更に大きな単位の地方公共団体を設け，三層構造とすることも許容されることとなる。
          u: ウ．憲法第95条は，「一の地方公共団体のみに適用される特別法」について規定するが，「一の地方公共団体」は，「一つの」ではなく，「特定の」地方公共団体を意味するものであるから，複数の地方公共団体に適用される法律についても，同条の規定する住民投票が必要になる場合がある。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      20:
        questions: "）条約に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。"
        answer:
          a: ア．内閣が条約を締結するには国会の承認を経ることが憲法上必要であるとされる趣旨は，国会による政府の統制を確保することにあるから，国家間の合意の締結には，名称・内容のいかんを問わず，国会の承認が必要となる。［No.38］
          i: イ．憲法が条約に優位すると考える見解によっても，国際協調主義や，裁判所による違憲審査について定めた憲法第81条に条約が列挙されていないことなどを理由として，条約が裁判所の違憲審査の対象に含まれないと解することは可能である。［No.39］
          u: ウ．条約が裁判所の違憲審査の対象となると考える見解によれば，条約が裁判所によって違憲と判断された場合，その国内法上の効力は否定されるが，国際法上の効力まで当然に否定されるわけではない。［No.40］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
