---
ja:
  kenpo:
    2022:
      1:
        questions: 憲法が保障する基本的人権の制約理由に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。
        answer:
          a: ア．表現の自由などの精神的自由も、その行使の結果から本人を保護するために法律により制限を加えられることがあるが、こうした制限については、専門技術的な判断が伴うことから立法者に広い裁量が認められるので、目的との関連で著しく不合理であることが明らかである場合に限って、その効力を否定することができる。
          i: イ．職業選択の自由は、社会生活における安全の保障及び秩序の維持等の消極的な目的や、国民経済の円満な発展や社会公共の便宜の促進、経済的弱者の保護等の社会政策及び経済政策上の積極的な目的のほか、租税の適正かつ確実な賦課徴収を図るという国家の財政目的のために制約され得る。
          u: ウ．労働基本権は、勤労者の経済的地位の向上のための手段として認められたものであって、それ自体が目的とされる絶対的なものではないから、憲法第13条のいう公共の福祉のための制約を受けるほか、公務員の争議行為の禁止の場合のように、勤労者を含めた国民全体の共同利益の見地からする制約を受ける。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      2:
        questions: 私人間における人権保障に関する次のアからウまでの各記述について、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。
        answer:
          a: ア．最高裁判所は、株式会社による政党への政治資金の寄附が、国民の選挙権の自由な行使を直接に侵害するものであるとしつつ、会社にも政治活動の自由が保障されるため、当該侵害は社会的許容性の限度を超えるものではないと判断されることから、当該寄附が公序良俗に違反すると解することはできないとした。
          i: イ．最高裁判所は、株式会社の就業規則において女子の定年年齢を男子より低く定める部分が、専ら女子であることのみを理由として差別したことに帰着するものとして、公序良俗に違反し無効であると解するに当たって、個人の尊厳と両性の本質的平等を解釈の基準として定める民法の規定とともに、法の下の平等を定める憲法第14条第1項を参照した。
          u: ウ．最高裁判所は、下級裁判所が、一定の集団に属する者の全体に対して人種差別的な発言をした者に対し、人種差別撤廃条約並びに同条約に照らして解釈される憲法第13条及び第14条第1項は私人相互の関係にも直接適用されるとして、民法第709条の規定により高額の損害賠償を命じた事例において、上告を棄却した。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      3:
        questions: 法の下の平等に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、それぞれ正しい場合には1を、誤っている場合には2を選びなさい。
        answer:
          a: ア．国民への課税要件等を定めるには、極めて専門技術的な判断を要するため、租税法の分野における所得の性質の違い等を理由とする取扱いの区別については、その立法目的が正当なものであり、かつ、当該立法において具体的に採用された区別の態様が目的との関連で著しく不合理であることが明らかでない限り、その合理性は否定できず、憲法第14条に違反しない。［No.3］
          i: イ．生存権は、生存に直結する権利であり精神的自由に準ずる権利である一方、これを具体化するための立法には高度の専門技術的な政策的判断を要するところ、併給調整条項の適用により、障害福祉年金の受給者と非受給者との間で児童扶養手当の受給に関する区別が生じるとしても、立法目的に合理的な根拠があり、かつ、立法目的と当該区別との間に実質的関連性が認められ、合理的理由のない差別とはいえないから、憲法第14条に違反しない。［No.4］
          u: ウ．相続制度をどのように定めるかは、国の伝統、社会事情、国民感情や、その国における婚姻ないし親子関係に対する規律、国民の意識等を総合的に考慮するなど立法府の合理的な裁量判断に委ねられているが、嫡出性の有無による法定相続分の区別は、立法府に与えられた上記のような裁量権を考慮しても、こうした区別をすることについて合理的な根拠が認められないから、合理的理由のない差別として、憲法第14条に違反する。［No.5］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      4:
        questions: 憲法第20条に関する次のアからウまでの各記述について、bの見解がaの見解の批判となっている場合には1を、そうでない場合には2を選びなさい。
        answer:
          a: ア．a．憲法第20条第2項と同条第3項の規定は、その目的、趣旨、対象、範囲を異にしており、同条第2項の「宗教上の行為、祝典、儀式又は行事」は、必ずしも全てが同条第3項の「宗教的活動」に含まれるという関係にはない。b．憲法第20条第3項の「宗教的活動」に含まれない宗教上の祝典、儀式、行事等であっても、国家がこれに参加を強制すれば、同条第2項違反の問題が生じ得る。［No.6］
          i: イ．a．憲法第20条第3項にいう「宗教的活動」とは、国及びその機関の活動の中で宗教と関わりを持つ全ての行為を指すものではなく、その関わりが相当とされる限度を超えるものに限られる。b．国家が社会生活に規制を加え、あるいは教育、福祉、文化等に関する助成、援助等の諸施策を実施するに当たって、宗教と一定の関わりを生ずることは避けられない。［No.7］
          u: ウ．a．憲法第20条第3項の「宗教的活動」とは、目的が宗教的意義を持ち、効果が宗教に対する援助、助長、促進又は圧迫、干渉等になるものをいい、その該当性判断において、一般人の宗教的評価や行為者の意図等の主観、行為が一般人に与える影響等も考慮すべきである。b．「宗教的活動」の該当性判断において一般人の宗教的評価等を考慮することは、多数者による少数者の信仰の抑圧につながる可能性がある。［No.8］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      5:
        questions: 表現の自由に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。
        answer:
          a: ア．ビラの配布のために集合住宅の共用部分及び敷地内に管理権者の承諾なく立ち入って、その管理権やそこで私的生活を営む者の私生活の平穏を侵害したとしても、ビラの内容が政治的意見を記載したものであれば、表現の自由の行使として尊重されるべきであるから、当該立入り行為を刑法第130条前段の罪に問うことは憲法第21条第1項に違反し、許されない。
          i: イ．公立図書館は、住民に対して思想、意見その他の種々の情報を含む図書館資料を提供してその教養を高めること等を目的とする公的な場であり、図書の著作者にとっては、その思想、意見等を公衆に伝達する公的な場でもあるから、図書の著作者は、公立図書館に対して表現の自由に基づいて自らの著作物を購入し、閲覧に供するよう求めることができる。
          u: ウ．報道機関の報道が正しい内容を持つためには、報道のための取材の自由も憲法第21条の精神に照らして十分尊重されなければならず、取材源の秘密は、取材の自由を確保するために必要なものとして重要な社会的価値を有するから、報道機関の記者が民事訴訟で証人として尋問された場合、取材源に関する証言の拒絶は、それによって真実発見及び裁判の公正が犠牲になるとしても、直ちに認められなければならない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      6:
        questions: 新聞の記事に取り上げられた者が、当該記事に取り上げられたという理由のみによって、当該新聞を発行・販売する者に対し、当該記事に関する自己の反論文を無修正、無料で掲載することを求めることができるものとする、いわゆる反論権に関する次のアからウまでの各記述について、最高裁判所の判決（最高裁判所昭和62年4月24日第二小法廷判決、民集41巻3号490頁）の趣旨に照らして、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。
        answer:
          a: ア．反論権の制度が認められると、新聞記事により自己の名誉を傷つけられあるいはそのプライバシーに属する事項等について誤った報道をされたとする者にとっては、機を失せず、同じ新聞紙上に自己の反論文の掲載を受けることができ、これにより当該記事に対する自己の主張を読者に訴える途が開かれることになる。したがって、反論権の制度が名誉あるいはプライバシーの保護に資するものがあることは否定し難い。
          i: イ．反論権の制度は、民主主義社会において極めて重要な意味を持つ新聞等の表現の自由に対し重大な影響を及ぼすものである。したがって、記事を掲載した新聞が日刊全国紙であって、当該新聞による情報の提供が一般国民に対し強い影響力を持ち、当該記事が特定の者の名誉ないしプライバシーに重大な影響を及ぼし得る場合でない限り、具体的な成文法がないのに反論権を認めることはできない。
          u: ウ．放送事業者に対して、一定の場合に、放送により権利の侵害を受けた本人等からの請求に基づく訂正放送を義務付ける放送法の規定や、他人の名誉を毀損した者に対して、裁判所が「名誉を回復するのに適切な処分」を命ずることができるとする民法第723条の規定は、反論権について直接規定したものではない。しかし、それらの規定は、それぞれの趣旨に鑑みれば、裁判において反論権を認める根拠となり得る。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      7:
        questions: 憲法第22条と海外旅行の自由に関する次のアからウまでの各記述について、bの見解がaの見解の批判となっている場合には1を、そうでない場合には2を選びなさい。
        answer:
          a: ア．a．海外旅行の自由は、海外に移住する自由に含まれる。b．憲法第22条第1項は国内の関係、同条第2項は国外の関係を規律すると考えることは形式的に過ぎて適切ではない。［No.11］
          i: イ．a．海外旅行の自由は、移転の自由に含まれる。b．日本国の主権から離脱する自由として海外に移住し国籍を離脱する自由と、日本国の主権の保護を受けながら一時的に日本国外に渡航する自由とは異なる。［No.12］
          u: ウ．a．海外旅行の自由は、憲法第22条ではなく、幸福追求権の一部分として憲法第13条により保障される。b．移転の自由及び海外に移住する自由は、一時的な移動ではなく、生活の本拠を決定することを保障するものである。［No.13］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      8:
        questions: 教育に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。
        answer:
          a: ア．憲法第26条の規定の背後には、子どもは学習権を有するとの観念が存在しており、子どもに対する教育は、専ら子どもの利益のために、教育を与える者の責務として行われるべきものであることからすると、教育の内容及び方法は、基本的に、子どもの教育の実施に当たる教師が決定すべきこととなる。
          i: イ．教育内容に対する国家的介入は抑制的であることが要請され、誤った知識や一方的な観念を子どもに植え付けるような教育を施すことを国が強制することは許されないと解されるが、このことは、教育内容について決定する国の権能を否定する理由とはならない。
          u: ウ．憲法第26条第2項は、子女に教育を受けさせることを国民に義務付け、義務教育は無償とすると定めているのであるから、同項は、義務教育に関する限り、授業料のほか、教科書代金や学用品についても国が負担することを定めたものと解される。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      9:
        questions: 刑事手続上の権利に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、それぞれ正しい場合には1を、誤っている場合には2を選びなさい。
        answer:
          a: ア．憲法第31条の定める法定手続の保障は、直接には刑事手続に関するものであるが、行政手続にも及ぶと解すべき場合があり、その場合には行政処分の相手方に常に事前の告知、弁解、防御の機会を与える必要がある。［No.15］
          i: イ．憲法第35条は、住居、書類及び所持品について、侵入、捜索及び押収を受けることのない権利を規定しているが、この規定の保障対象には、住居、書類及び所持品に準ずる私的領域に侵入されることのない権利が含まれる。［No.16］
          u: ウ．憲法第38条第1項は、自己が刑事上の責任を問われるおそれのある事項について供述を強要されないことを保障するものであり、氏名の供述も、これによって自己が刑事上の責任を問われるおそれがあることから、原則として保障が及ぶ。［No.17］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      10:
        questions: "）国家賠償請求に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、それぞれ正しい場合には1を、誤っている場合には2を選びなさい。"
        answer:
          a: ア．公務員の不法行為について国又は公共団体に対し損害賠償を求める権利について、憲法第17条は、「法律の定めるところ」による旨を規定している。これは、公務員のどのような行為によりいかなる要件で損害賠償責任を負うかを立法府の政策判断に委ねたものであって、立法府に無制限の裁量権を付与しているわけではない。［No.18］
          i: イ．公務員がその職務を行うに当たり、故意又は過失によって違法に他人に損害を加えた場合、国は当該公務員に代位して賠償責任を負う。しかし、国会議員には憲法第51条で発言及び表決に対する免責特権が保障されているから、議員が国会で行った質疑等において個人の名誉を毀損する発言を行っても責任を問われることはないので、国が賠償責任を負うこともない。［No.19］
          u: ウ．国会議員の立法行為の国家賠償法上の違法の問題と立法内容の違憲の問題とは区別されるし、本質的に政治的なものである立法行為の適否を法的に評価するべきではない。したがって、国民に憲法上保障されている権利を違法に侵害することが明白な場合であっても、国会議員の立法行為が国家賠償法上の違法の評価を受けることはない。［No.20］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      11:
        questions: "）日本の憲法史に関する次のアからウまでの各記述について、それぞれ正しい場合には1を、誤っている場合には2を選びなさい。"
        answer:
          a: ア．大日本帝国憲法の下では、天皇が有していた、作戦用兵の目的のために陸海軍を統括する統帥権について、国務大臣の輔弼の対象外とされたため、帝国議会は関与し得なかった。［No.21］
          i: イ．大日本帝国憲法の下では、内閣制度は憲法で規定されていなかった。また、帝国議会の権限が強く保障されていたので、各国務大臣は天皇ではなく帝国議会に対して責任を負うとされていた。［No.22］
          u: ウ．日本国憲法成立の法理に関する八月革命説は、ポツダム宣言の受諾によって天皇から国民に主権者が変更されたという説は現実社会の変化にそぐわない全くの擬制的な説明であると批判して、ポツダム宣言を受諾した1945年8月から革命が漸進的に進行し、占領体制から脱して国家主権を回復したときにその革命が成就し国民は真の主権者となった、とする説である。［No.23］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      12:
        questions: "）天皇に関する次のアからウまでの各記述について、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。"
        answer:
          a: ア．天皇の国事行為には内閣の助言と承認が必要であるが、天皇が自ら発意し、内閣が閣議にかけて承認する場合、内閣は当該国事行為についての責任を負わない。
          i: イ．天皇は、法律の定めるところにより、国事行為を委任することができるが、この委任については、内閣の助言と承認は必要ではない。
          u: ウ．皇室に財産を譲り渡し、又は皇室が、財産を譲り受け、若しくは賜与することは、国会の議決に基づかなければならない、と憲法は定めている。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      13:
        questions: "）選挙権及び被選挙権に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。"
        answer:
          a: ア．憲法第15条第4項は、「すべて選挙における投票の秘密は、これを侵してはならない。」として投票の秘密を明文で保障しているが、選挙の公正が担保されることは、代表民主制の根幹をなすもので極めて重要であるから、選挙権のない者又は代理投票をした者の投票のような無効投票が存在する場合における議員の当選の効力を判断する手続の中で、こうした無効投票の投票先を明らかにするとしても、その限度では投票の秘密を侵害するものではない。
          i: イ．労働組合は、団結権が保障されており、組合の団結を維持するための統制権の行使によって公職選挙における組合員の立候補の自由を制約することができるので、公職選挙において統一候補を擁立した場合、当該候補以外の組合員が立候補をやめなかったことを理由にその組合員を処分することができる。
          u: ウ．組織的選挙運動管理者等が、買収等所定の選挙犯罪を犯して禁錮以上の刑に処せられた場合に、公職の候補者等であった者の当選を無効とし、かつ、これらの者が5年間当該選挙に係る選挙区において行われる当該公職に係る選挙に立候補することを禁止する旨を定めた公職選挙法の規定は、民主主義の根幹をなす公職選挙の公正を保持する極めて重要な法益を実現するための規定であり、立法目的は合理的であるとともに、立法目的を達成する手段として必要かつ合理的なものといえるから、憲法第15条に違反しない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      14:
        questions: "）政党に関する次のアからウまでの各記述について、bの見解がaの見解の根拠となっている場合には1を、そうでない場合には2を選びなさい。"
        answer:
          a: ア．a．政治資金の授受の規正その他の措置を講ずることを定めた政治資金規正法は、会社が政党及び政治資金団体に対して政治活動に関する寄附をすることを、一定の限度で認めている。b．政党は、議会制民主主義を支える不可欠の要素であり、かつ、国民の政治意思を形成する最も有力な媒体であるから、その健全な発展に協力することは、会社にとって当然の行為として期待される。［No.26］
          i: イ．a．国が政党に対し政党交付金による助成を行うことを定めた政党助成法は、政党に対する政党交付金の交付に当たっては、条件を付し、又はその使途について制限してはならないとしている。b．政党が議会制民主主義を支える不可欠の要素であることからすると、その結社としての活動の自由が制約されることはやむを得ない。［No.27］
          u: ウ．a．公職選挙法は、所属議員、直近の選挙における得票又は当該選挙における候補者に照らし一定以上の規模を有する政党のみに、衆議院及び参議院の比例代表選出議員の選挙に参加することを認めている。b．その所属する政党の規模の大小により、選挙への参加機会が均等でないことは、信条又は社会的身分による差別に当たる疑いがある。［No.28］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      15:
        questions: "）内閣及び内閣総理大臣に関する次のアからウまでの各記述について、それぞれ正しい場合には1を、誤っている場合には2を選びなさい。"
        answer:
          a: ア．最高裁判所の判例の趣旨に照らすと、内閣総理大臣は、憲法第72条に規定された行政各部の指揮監督権限を閣議にかけて決定した方針に基づいて行使する必要があり、行政各部に対してその所掌事務について一定の方向で処理するよう指導、助言等の指示を与えたとしても、内閣としての事前の方針決定がなければ、事実上の影響力を行使したものにすぎず、内閣総理大臣の職務権限に属するものではない。［No.29］
          i: イ．内閣は憲法第73条第1号により法律を誠実に執行する義務を負っているが、最高裁判所が違憲と判断した法律については、国会がこれを改廃する前であっても、内閣は、その執行を差し控えることができる。［No.30］
          u: ウ．憲法には内閣に法律案の提出権を認める規定はないものの、憲法では議院内閣制が採用されていることや、内閣に法律案の提出権を認めたからといって当然に国会の議決権が拘束されるわけではないことは、法律で内閣に法律案の提出権を付与することが憲法上禁じられていないと解する根拠となり得る。［No.31］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      16:
        questions: "）裁判官の身分保障に関する次のアからウまでの各記述について、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。"
        answer:
          a: ア．裁判官は、裁判により心身の故障のために職務を執ることができないと決定された場合を除いては、最高裁判所の裁判官については国民審査によることなしには、また、下級裁判所の裁判官については公の弾劾によることなしには、罷免されることはない。
          i: イ．裁判官の罷免事由である「心身の故障」とは、裁判官の職務を遂行することができない程度の精神上の能力の喪失又は身体的故障で、相当長期間にわたって継続することが確実に予想される場合をいうと解されており、一時的な故障は、たとえそれがどのように重大なものであってもこれに当たらない。
          u: ウ．憲法第78条は、裁判官の懲戒処分は行政機関が行うことはできないと規定しているところ、これは、裁判官の懲戒処分は裁判所が行うべきことを定めているものと解されており、その手続については、法律上、裁判により行うことが規定されている。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      17:
        questions: "）司法権の限界に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、それぞれ正しい場合には1を、誤っている場合には2を選びなさい。"
        answer:
          a: ア．地方議会の議員に対する出席停止の懲罰に関し、その懲罰を受けた議員が取消しを求める訴えは、法令の適用によって終局的に解決し得る法律上の争訟に当たるところ、議会により出席停止の懲罰処分を科されると、その議員は、住民の負託を受けた議員としての責務を十分に果たすことができなくなるから、当該処分が議会の自律的な権能に基づいてなされたものとして、議会に一定の裁量が認められるとしても、裁判所は、常にその適否を判断することができ、司法審査の対象となる。［No.33］
          i: イ．政党が組織内の自律的運営として党員に対してした除名処分は、原則として自律的な解決に委ねるのが相当であり、その除名処分が一般市民法秩序と直接の関係のない内部的な問題にとどまる限り、司法審査の対象とはならず、また、一般市民としての権利利益を侵害する場合であっても、その処分の当否は、当該政党の自律的な規範が公序良俗に反するなどの特段の事情のない限りその規範に照らし、規範がない場合は条理に基づき、適正な手続にのっとってされたか否かによって決すべきであり、司法審査もこの点に限られる。［No.34］
          u: ウ．三権分立の制度の下において、司法権の行使について、ある限度の制約は免れず、あらゆる国家行為が無制限に司法審査の対象となるわけではないと解すべきであるところ、衆議院の解散のような直接国家統治の基本に関する高度に政治性のある国家行為は、国会等の政治部門の判断に委ねられ、最終的に国民の政治判断に委ねられているものと解すべきであるから、衆議院の解散が違法であることを前提とする国会議員の歳費の支払を請求する訴えは、法律上の争訟に当たるとはいえない。［No.35］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      18:
        questions: "）財政に関する次のアからウまでの各記述について、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。"
        answer:
          a: ア．予算の裏付けを必要とする法律が成立しているにもかかわらず、その執行に必要となる予算が不存在ないし不成立の場合、法律を誠実に執行すべき内閣としては、補正予算の提出、経費の流用、予備費の支出などにより、対処することが求められる。
          i: イ．予備費は、予見し難い予算の不足に充てるため、国会の議決に基づいて設けられ、内閣の責任で支出されるものである。そのため、内閣は、その支出について、事後に国会の承諾を求める必要はない。
          u: ウ．内閣は、毎年の国の収入支出の決算について、会計検査院の検査を経た上で、翌年度国会に提出しなければならない。提出された決算については、各議院で審議され、それを認めるか否かの審査がなされるが、そこで不承認とされても、決算の効力に影響は生じない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      19:
        questions: "）条例に関する次のアからウまでの各記述について、最高裁判所の判例の趣旨に照らして、正しいものには○、誤っているものには×を付した場合の組合せを、後記1から8までの中から選びなさい。"
        answer:
          a: ア．憲法第94条は、法律の範囲内で条例制定権を認めているが、ある事項について国の法令中にこれを規制する明文の規定がない場合であれば、当該事項について規制を設ける条例の規定は、国の法令に違反しない。
          i: イ．条例は、公選の議員をもって組織する地方公共団体の議会の議決を経て制定される自治立法であって、国民の公選した議員をもって組織する国会の議決を経て制定される法律に類するものであるから、条例によって刑罰を定める場合、法律による条例への委任は、一般的・包括的委任で足りる。
          u: ウ．憲法第94条は、地方公共団体に条例制定権を認めており、ある事項を条例によって規制する結果として、地方公共団体ごとにその取扱いに差異が生じることがあり得るから、ある事項について条例によって刑罰を定める場合、地域によって刑罰の内容に差異が生じることも許容され得る。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      20:
        questions: "）憲法改正に関する次のアからウまでの各記述について、それぞれ正しい場合には1を、誤っている場合には2を選びなさい。"
        answer:
          a: ア．憲法改正の公布は、天皇が内閣の助言と承認のもとで「国民の名で」行うものとされており、「国民の名で」というのは、憲法改正が主権の存する国民の意思によることを明らかにする趣旨である。［No.38］
          i: イ．憲法改正は、国会が発議し、国民の承認を経ることによって成立するもので、国民主権に関わることから、特別の国民投票又は直近の衆議院議員総選挙の際に行われる投票においてその過半数の賛成を必要とする。［No.39］
          u: ウ．憲法を始源的に創設する憲法制定権力と憲法によって与えられた憲法改正権とを区別する考えは、憲法改正には法的な限界があるとする見解の根拠となる。［No.40］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
