---
ja:
  kenpo:
    2018:
      1:
        questions: 次の対話は，公務員の人権に関する教授と学生の対話である。教授の各質問に対する次のアからウまでの学生の各回答について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。教授．公務員の地位のように権利主体と公権力との間に特殊な法律関係がある場合には，憲法の人権保障が原則として及ばないなどとする理論がありますね。このような理論によって公務員の人権に対する制約を正当化した最高裁判所の判決がありますか。
        answer:
          a: ア．はい。猿払事件判決（最高裁判所昭和49年11月6日大法廷判決，刑集28巻9号393頁）が，先生のおっしゃる趣旨の判示をして，公務員の政治的意見表明の自由に対する制約を正当化しています。［№1］教授．あなたの言うその判決は，国家公務員法第102条第1項が一定の行動類型に属する政治的行為を禁止していることに伴い生じ得る意見表明の自由の制約については，どのような判示をしていますか。
          i: イ．公務員の政治的中立性を損なうおそれのある行動類型に属する政治的行為を禁止することに伴い意見表明の自由が制約されることになっても，そのような制約は行動の禁止に伴う限度での間接的・付随的制約にとどまると判示しています。［№2］教授．堀越事件判決（最高裁判所平成24年12月7日第二小法廷判決，刑集66巻12号1337頁）は，公務員のしたある行為が国家公務員法第102条第1項にいう「政治的行為」に該当するか否かの判断についてどのような枠組みを示していますか。
          u: ウ．同項にいう「政治的行為」の意義を，公務員の職務の遂行の政治的中立性を損なうおそれが実質的に認められるものと解した上，その判断においては，当該公務員の地位，その職務の内容や権限等，当該公務員がした行為の性質，態様，目的，内容等の諸般の事情を総合して判断するのが相当であると判示しています。［№3］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      2:
        questions: 法の下の平等に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．子にとって自ら選択できないような事柄を理由に不利益を及ぼすことは許されず，子を個人として尊重し，その権利を保障すべきであるという考えが確立されてきたという事情は，嫡出子と嫡出でない子の法定相続分を区別する合理的な根拠が失われたと判断すべき根拠となる。
          i: イ．憲法第14条第1項は国民に対し法の下の平等を保障した規定であり，平等の要請は，事柄の性質に即応した合理的な根拠に基づくものでない限り，差別的な取扱いをすることを禁止する趣旨と解され，特に同項後段の事項は，合憲性の推定が排除される事項を限定列挙したものである。
          u: ウ．地方公共団体が法律の範囲内で条例を制定することができるとしている条例制定権の規定（憲法第94条）に照らすと，地方公共団体が売春の取締りについて各別に条例を制定する結果，その取扱いに差別を生ずることがあっても，地域差の故をもって憲法第14条第1項に反するとはいえない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      3:
        questions: 思想・良心の自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．良心の自由とは是非弁別の判断に関する事項を外部に表現する自由及び表現しない自由をも広く含むと解されるが，裁判所が謝罪広告を強制したとしても，単に事態の真相を告白し，陳謝の意を表明するにとどまる限りは，良心の自由を不当に制限するものではない。
          i: イ．司法書士会が大震災で被災した他県の司法書士会に復興支援拠出金を寄付することは，司法書士会の目的の範囲を逸脱せず，また，司法書士会がその寄付のために会員から負担金を徴収することは，強制加入団体であることを考慮しても，会員の政治的又は宗教的立場や思想，信条の自由を害するものではない。
          u: ウ．破壊活動防止法第39条及び第40条のせん動罪は，政治目的をもって，所定の犯罪のせん動をすることを処罰するものであるが，せん動として外形に現れた客観的な行為を処罰の対象とするもので，行為の基礎となった思想，信条を処罰するものではないから，せん動罪が政治思想を処罰するもので憲法第19条に違反するとの主張は前提を欠く。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      4:
        questions: 信教の自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．輸血以外に救命手段がない場合には輸血を拒否するという意思決定を尊重すべきとはいえないので，患者が，輸血を受けることは自己の宗教上の信念に反するとして，輸血を伴う医療行為を拒否するとの明確な意思を有していたとしても，このような意思決定をする権利は，人格権としての保護に値しない。［№6］
          i: イ．信仰上の理由から剣道実技の履修を拒否した高等専門学校の生徒に対して学校長が行った原級留置処分及び退学処分は，履修拒否が生徒の信仰の核心部分と密接に関連する真しな理由からのものであり，代替措置の申入れに対して学校側はそれが不可能でないのに何ら検討することなく拒否したなどという事情の下では，裁量権の範囲を超えて違法である。［№7］
          u: ウ．宗教法人に対する解散命令のような法的規制は，たとえ信者の宗教上の行為を法的に制約する効果を伴わないとしても，これに何らかの支障を生じさせることがあり得ることから，信教の自由の重要性に鑑み，憲法上，そのような規制が許容されるものであるかどうかは慎重に吟味しなければならない。［№8］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      5:
        questions: 次の見解は，インターネット上の名誉毀損罪の成否と表現の自由について論じたものである。この見解に関する次のアからエまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。「インターネットの利用者は，自己の見解を外部に向かって発信することができるから，インターネットを利用している被害者は，自己に向けられた加害者のインターネット上の表現行為に対し，言論による反論が可能である。したがって，インターネットの利用者が名誉毀損の表現行為をした場合には，新聞などのマス・メディアを通じた表現の場合よりも，名誉毀損罪の成立する範囲を限定すべきである。」
        answer:
          a: ア．この見解に対しては，インターネット上の全ての情報を知ることは不可能であり，自己の名誉を毀損する表現が存在することを知らない被害者に対して反論を要求すること自体，そもそも不可能である，という批判があり得る。［№9］
          i: イ．言論の応酬により当不当を判断することができるのは意見や論評であって，事実の摘示による名誉毀損の場合には，被害者と加害者が言論の応酬をしても，インターネット利用者は真偽を判断することができないという指摘は，この見解の根拠となり得る。［№10］
          u: ウ．この見解に対しては，インターネット上に載せた情報は，不特定多数の利用者が瞬時に閲覧可能となり，全世界に伝播される可能性もあることから，被害者のインターネット上の反論によって名誉の回復が図られる保証もない，という批判があり得る。［№11］
          e: エ．言論による侵害に対しては，言論で対抗するのが表現の自由の基本原則であり，被害者が加害者に対し十分な反論ができ，功を奏するのであれば，被害者の社会的評価が害されるおそれはないという指摘は，この見解の根拠となり得る。［№12］
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      6:
        questions: 集会の自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。］
        answer:
          a: ア．市民会館は，集会をするために必須の施設であるから，その使用について，届出制ではなく，許可制を採ることは，集会の自由を不当に制限することになる。［№13］
          i: イ．道路については，交通の安全と円滑を図るという機能面が重視される結果，道路における集団行動の規制は，集会の自由に対する制限には当たらない。［№14］
          u: ウ．市の管理する公園について，人の生命，身体又は財産が侵害され，公共の安全が損なわれる，明らかな差し迫った危険の発生が具体的に予見される場合でないのに，その使用を規制するのは，集会の自由を不当に制限することになる。［№15］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      7:
        questions: 学問の自由及び教育の自由に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．大学における学生の集会が，大学の公認した団体が大学の許可を得て開催したものであれば，真に学問的な研究又はその結果の発表のためのものでなく，実社会の政治的社会的活動に当たる場合であっても，同集会への警察官の立入りは，大学の有する学問の自由と自治を侵害することとなる。
          i: イ．学問の自由は，学問研究の自由とその研究結果の発表の自由だけでなく，その研究結果を教授する自由をも含むところ，教育の本質上，教師は，高等学校以下の普通教育においても，教授の自由を有し，自らの判断で教育内容を決定することができるのであって，国が教育内容の決定に介入することは許されない。
          u: ウ．親は，子の将来に関して最も深い関心を持ち，かつ，配慮をすべき立場にある者として，子に対する教育の自由を有しており，このような親の教育の自由は，主として家庭教育等学校外における教育や学校選択の自由にあらわれるところ，親の学校選択の自由は，特定の学校の選択を強要又は妨害された場合，その侵害が問題となり得る。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      8:
        questions: 居住・移転の自由に関する次のアからエまでの各記述について，明らかに誤っているものの組合せを，後記1から6までの中から選びなさい。
        answer:
          a: ア．自衛官につき，防衛大臣が指定する場所に居住しなければならないとする法律の規定は，当該国民が自ら自衛官に志願した結果として課される制約であるところ，我が国の防衛のためいつでも職務に従事できる態勢にあることが求められるという自衛官の職務の性質に照らし，このような居住地の制限は合理的な制限であって合憲と解される。
          i: イ．外務大臣において，著しくかつ直接に日本国の利益又は公安を害するおそれがあると認めるに足りる相当な理由がある者につき一般旅券を発給しないことができるとする法律の規定は，単に旅券の発給を制限するに過ぎず，海外渡航の自由を制約するものではないため合憲と解される。
          u: ウ．住民が住所を変更したときには市町村長に届け出なければならない旨を義務付ける法律の規定は，住所・居所の決定や移転それ自体を制限するものではなく，規制態様が軽微である反面，住民票の整備により得られる公益が大きいことから合憲と解される。
          e: エ．破産手続中の破産者につき，裁判所の許可なく居住地を離れることを禁止する法律の規定は，破産手続という限られた期間内にのみ適用されるものに過ぎず，仮に裁判所の許可が得られなくても破産手続が終結すれば自由に居住地を離れることができるため，居住・移転の自由に対する制約が認められず合憲と解される。
          o:
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．アエ
          4: 4．イウ
          5: 5．イエ
          6: 6．ウエ
          7:
          8:
      9:
        questions: 労働基本権に関する次のアからエまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．憲法上，国は，労働基本権をむやみに制約する立法等の措置を行うことは許されず，また同時に，国は，労働者の労働基本権を保障する措置を講じる義務があり，その意味で，労働基本権には自由権としての側面と社会権としての側面があるといえる。［№18］
          i: イ．労働基本権には，団結権，団体交渉権及び団体行動権があるが，これらのうち団結権は最も重要かつ基本的な権利であるから，団体交渉権や団体行動権について現行法上特別な制約に服している自衛官や警察官にも団結権は認められている。［№19］
          u: ウ．判例は，労働基本権について，公務員にもその保障が及ぶとし，その制約の合憲性を判断する上で，職務の公共性は考慮されるべきではないとする一方，人事院が設けられていることなどの代替措置が整備されていることを重視して，一般私企業とは異なる制約に服するものとする。［№20］
          e: エ．憲法第28条は，その性質上，私人間の関係に適用される余地はなく，そのため，判例は，労働組合への加入を強制するために使用者と労働組合との間に締結されるユニオン・ショップ協定の効力を団結権との関係で判断する場合にも，憲法を直接適用していない。［№21］
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      10:
        questions: 憲法第24条に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。］
        answer:
          a: ア．憲法第24条第1項は，婚姻については当事者間の自由かつ平等な意思決定に委ねられるべきであるとの趣旨を明らかにしたものであるから，婚姻に関する法制度の内容が意に沿わないことを理由として婚姻しない者が生じるのであれば，その法制度を定めた法律は，憲法第24条第1項の趣旨に沿わない制約を課しているものとの評価を免れないことになる。
          i: イ．憲法第24条第2項は，婚姻及び家族に関する事項について，具体的な制度の構築を第一次的には国会の合理的な立法裁量に委ねるとともに，その立法に当たっては，個人の尊厳と両性の本質的平等に立脚すべきであるとする要請，指針を示すことによって，その裁量の限界を画したものである。
          u: ウ．憲法第24条は，婚姻及び家族に関する立法において，憲法上の権利として保障される人格権を不当に侵害せず，かつ，両性の形式的な平等が保たれた内容の法律の制定を求めるにとどまらず，憲法上直接保障された権利とまではいえない人格的利益をも尊重すべきこと，両性の実質的な平等が保たれるように図ること等についても十分に配慮した法律の制定を求めるものである。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      11:
        questions: 憲法の最高法規性に関する次のアからエまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．憲法第97条は，憲法の保障する基本的人権を侵すことのできない永久の権利と位置付けており，憲法の最高法規性を実質的に根拠付けるものと見ることができる。［№23］
          i: イ．日本国憲法において抵抗権が認められているという見解は，憲法が最高法規であることと矛盾する。［№24］
          u: ウ．憲法がその国の法体系において最高法規と位置付けられる場合において，国家緊急権がその中に明文で規定されることはあり得ない。［№25］
          e: エ．抽象的違憲審査制と付随的違憲審査制のうちいずれの違憲審査制を採るかは，憲法の最高法規性から当然に導かれるわけではない。［№26］
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      12:
        questions: 天皇及び皇室に関する次のアからエまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．天皇が，法律の定めるところにより，国事行為を委任する場合，この委任行為自体は明らかに国事行為ではないから，内閣の助言と承認を要しない。［№27］
          i: イ．国事行為は，形式的・儀礼的な行為であるため，国事行為としての天皇の行為がなくても，政令の公布や国会の召集の法的効力は発生する。［№28］
          u: ウ．摂政は，天皇の名で国事行為を行う天皇の法定代理機関であり，天皇が未成年のときなど皇室典範に定める原因が生じることにより設置される。［№29］
          e: エ．憲法第88条は，すべて皇室財産は国に属すると規定しており，皇室が私有財産を保有したり運用したりすることは禁じられている。［№30］
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      13:
        questions: 選挙に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．判例は，参議院議員選挙における定数不均衡の問題について，参議院の半数改選制の要請を踏まえれば投票価値の平等が一定の限度で譲歩を求められても憲法に違反するとはいえないとして，衆議院の場合よりも広い立法裁量を認めてきており，これまで違憲状態を認定したことはない。［№31］
          i: イ．判例は，衆議院議員選挙におけるいわゆる1人別枠方式について，小選挙区比例代表並立制の導入に当たり，直ちに人口比例のみに基づいて定数配分を行った場合の影響に配慮するための方策であり，新選挙制度が定着し運用が安定すればその合理性は失われるとしている。［№32］
          u: ウ．判例は，公職選挙法による選挙運動用の文書図画の頒布・掲示の規制について，表現の自由に対する最小限の制約とはいえないが，憲法第47条の趣旨に照らせば，国会の定めた選挙運動のルールは合理的と考えられないような特段の事情のない限り尊重されなければならず，当該規制は立法裁量の範囲を逸脱しているとまではいえないので合憲であるとしている。［№33］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      14:
        questions: 憲法第9条に関する次のアからウまでの各記述について，最高裁判所の判例の趣旨に照らして，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。］
        answer:
          a: ア．憲法第9条第2項が保持を禁止した戦力とは，我が国がその主体となってこれに指揮権，管理権を行使し得る戦力に限られず，我が国との安全保障条約に基づき我が国に駐留する外国の軍隊も，我が国の要請に応じて武力を行使する可能性があるので，同項の戦力に該当し得る。
          i: イ．憲法前文が定める平和的生存権は，憲法第9条及び第3章の規定によって具体化され，裁判規範として現実的・個別的内容を持つものであるから，森林法上の保安林指定の解除処分が自衛隊の基地の建設を目的とするものである場合，周辺の住民は，同処分の取消訴訟において，平和的生存権の侵害のおそれを根拠として原告適格を有する。
          u: ウ．国が自衛隊の用地を取得するために私人と締結した土地売買契約は，当該契約が実質的にみて公権力の発動たる行為と何ら変わりがないといえるような特段の事情のない限り，憲法第9条の直接適用を受けず，私人間の利害関係の公平な調整を目的とする私法の適用を受けるに過ぎない。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      15:
        questions: 衆議院の優越に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。
        answer:
          a: ア．条約の承認に関する衆議院の優越の程度は，法律案の議決，予算の議決のいずれの場合と比べても小さい。［№35］
          i: イ．参議院と比べて衆議院の方が議員の任期が短いこと，衆議院に解散の制度があることは，衆議院の優越の根拠とはならない。［№36］
          u: ウ．憲法改正の発議及び予備費支出の承諾については，議決において衆議院の優越はなく，両議院の議決は対等である。［№37］
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      16:
        questions: 弾劾裁判所に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．弾劾裁判所に対し裁判官の罷免を求める訴追は，国会の両議院において当該裁判官の罷免を求める議案が可決されることにより，国会が行う。
          i: イ．国会の両議院の議員で組織される弾劾裁判所は，国会が閉会中であっても活動することができる。
          u: ウ．弾劾裁判所により罷免の裁判の宣告を受けた裁判官は，最高裁判所に対し，その裁判を不服として取消しを求めることができる。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
      17:
        questions: 司法審査が団体の内部事項に関する行為に及ぶかに関する次の学生アからエまでの各発言について，正しいものの組合せを，後記1から6までの中から選びなさい。
        answer:
          a: ア．「自律的な団体の内部紛争に対して司法審査が及ぶかという問題に関して，地方議会には，国会の両議院のような自律権はないものの，地方議会議員に対する懲罰としての除名処分は，内部規律の問題であるから，司法審査の対象とはならないとした判例があるよ。」
          i: イ．「判例の考え方からすると，発声障害により自ら発声することができない地方議会議員が，第三者による代読等，自らの発声以外の方法による発言を希望したのに対し，これを認めないという地方議会の決定は，純然たる内部規律の問題であるから，司法審査の対象にはならないことになるね。」
          u: ウ．「大学の単位認定行為は，特段の事情のない限り，純然たる大学内部の問題であって，大学の自主的な判断に委ねられるべきだから，司法審査の対象とならないとした判例もあったな。」
          e: エ．「判例の考え方からすると，特定の授業科目の単位の取得が国家資格取得の前提要件とされている場合には，大学の単位認定行為が司法審査の対象になる可能性もあるね。」
          o:
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．アエ
          4: 4．イウ
          5: 5．イエ
          6: 6．ウエ
          7:
          8:
      18:
        questions: '旭川市国民健康保険条例違憲訴訟判決（最高裁判所平成18年3月1日大法廷判決，民集60巻2号587頁）に関する次のアからウまでの各記述について，それぞれ正しい場合には1を，誤っている場合には2を選びなさい。ア.憲法第84条は「あらたに租税を課し，又は現行の租税を変更するには，法律又は法律の定める条件によることを必要とする。」と定めているところ，同条にいう「法律」には条例も含まれるとする見解は，この判決と矛盾抵触する。［№40］イ.この判決によれば，租税以外の公課であっても，租税に類似する性質を有するものについては，憲法第84条の趣旨が及ぶところ，その賦課徴収の強制の度合いは，当該公課と租税との類似性を検討するときの要素となる。［№41］ウ.この判決は，法律の委任に基づき保険料の賦課要件を定めるべき条例が保険料率の決定等を市長に委任していることにつき，委任された事項の内容や保険料率に係る算定基準の定め方等を検討して，憲法第84条の趣旨に反しないものと判断した。［№42］

          '
        answer:
          a:
          i:
          u:
          e:
          o:
        additional_answer:
          1:
          2:
          3:
          4:
          5:
          6:
          7:
          8:
      19:
        questions: 次の文章は，憲法上の地方公共団体の意義について述べた最高裁判所の判決（最高裁判所昭和38年3月27日大法廷判決，刑集17巻2号121頁）の判示を要約したものである。この判決に関する次のアからエまでの各記述について，明らかに誤っているものの組合せを，後記1から6までの中から選びなさい。「憲法が特に一章を設けて地方自治を保障するにいたったのは，新憲法の基調とする政治民主化の一環として，住民の日常生活に密接な関連をもつ公共的事務は，その地方の住民の手でその住民の団体が主体となって処理する政治形態を保障しようとする趣旨からである。この趣旨に徴するときは，憲法第93条第2項にいう地方公共団体といい得るためには，単に法律で地方公共団体として取り扱われているということだけでは足らず，事実上住民が経済的文化的に密接な共同生活を営み，共同体意識をもっているという社会的基盤が存在し，沿革的にみても，また現実の行政の上においても，相当程度の自主立法権，自主行政権，自主財政権等地方自治の基本的権能を附与された地域団体であることを必要とするものというべきである。」
        answer:
          a: ア．この判決は，憲法によって保障された地方自治がどのような性質を有するかという問題について，個人が国家に対して固有かつ不可侵の権利を持つのと同様に，地方公共団体もまた固有の前国家的な基本権を有するという立場に立つものである。
          i: イ．この判決は，「事実上住民が経済的文化的に密接な共同生活を営み，共同体意識をもっているという社会的基盤」の存在を地方公共団体の要件として挙げるが，｢共同体意識｣というのは測定不能で漠然とした概念ではないかとの批判がある。
          u: ウ．この判決のように，沿革上及び行政上の実態を基準に，憲法上の地方公共団体に当たるか否かを判断することは，憲法の下位規範である地方自治法によって憲法の解釈を行うこととなるとの指摘がある。
          e: エ．この判決には，憲法第92条にいう｢地方自治の本旨｣が，第93条で具体化されている住民自治と第94条で具体化されている団体自治によって構成されていると解する余地がなくなるという問題点がある。
          o:
        additional_answer:
          1: 1．アイ
          2: 2．アウ
          3: 3．アエ
          4: 4．イウ
          5: 5．イエ
          6: 6．ウエ
          7:
          8:
      20:
        questions: 憲法改正に関する次のアからウまでの各記述について，正しいものには○，誤っているものには×を付した場合の組合せを，後記1から8までの中から選びなさい。
        answer:
          a: ア．国会法によれば，議員が憲法改正原案を発議するには，衆議院においては議員100人以上，参議院においては議員50人以上の賛成を要するが，その発議に当たっては，内容において関連する事項ごとに区分して行うものとされている。
          i: イ．国会が発議した憲法改正に関する国民の承認は，衆議院議員総選挙又は参議院議員通常選挙の際に行われる国民投票によることも可能であるが，これらの選挙の際に行われる場合は日本国憲法の改正手続に関する法律は適用されない。
          u: ウ．日本国憲法の改正手続に関する法律では，憲法改正案に対する国民投票運動に関し，公職選挙法により規制される選挙運動と比較すると，戸別訪問の禁止がないなど規制が緩和されている。
          e:
          o:
        additional_answer:
          1: 1．ア○イ○ウ○
          2: 2．ア○イ○ウ×
          3: 3．ア○イ×ウ○
          4: 4．ア○イ×ウ×
          5: 5．ア×イ○ウ○
          6: 6．ア×イ○ウ×
          7: 7．ア×イ×ウ○
          8: 8．ア×イ×ウ×
