development:
  domain: <%= ENV.fetch('AUTH0_DOMAIN'), "xxxxx" %>
  audience: <%= ENV.fetch('AUTH0_AUDIENCE'), "xxxxx" %>

production:
  domain: <%= ENV.fetch('AUTH0_DOMAIN') %>
  audience: <%= ENV.fetch('AUTH0_AUDIENCE') %>
